#!/usr/bin/env python3
"""Verify formula 0x42's paired target/caster recoil result transaction."""
from __future__ import annotations

import argparse
import csv
import hashlib
import struct
import time
from pathlib import Path

import pefile

import analyze_dcl_reaction_dispatch as dispatch


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = dispatch.DEFAULT_EXE
DEFAULT_CATALOG = ROOT / "work" / "wotl_ability_action_baseline.csv"
TABLE_RVA = 0x682BC8
HANDLER_RVA = 0x308B78

ANCHORS = (
    (0x308B78,
     "48 83 EC 28 48 8B 05 F5 23 56 01 0F B6 48 3E 0F B6 05 10 7C 4A 00 66 89 05 DD 7B 4A 00 66 89 0D D4 7B 4A 00 E8 D3 C5 FF FF",
     "formula loads PA/Y and computes the target amount"),
    (0x308BA1,
     "0F BF 05 C8 7B 4A 00 0F BF 0D C3 7B 4A 00 4C 8B 05 BA 23 56 01 0F AF C8 66 41 89 48 06",
     "target result qword[0x14186AF70] receives PA*Y at result+0x06"),
    (0x308BBE,
     "0F BF C1 0F B6 0D D5 7B 4A 00 99 F7 F9 48 8B 0D 8E 23 56 01 66 89 41 06 C6 01 01",
     "caster result qword[0x14186AF60] receives trunc(targetDebit/X) and is activated"),
    (0x308BD9,
     "41 C6 40 27 80 C6 41 27 80",
     "both result records receive the same native transaction/presentation flag"),
)


def render(exe: Path, catalog: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    target = struct.unpack("<Q", dispatch.rva_bytes(pe, raw, TABLE_RVA + 0x42 * 8, 8))[0] - pe.OPTIONAL_HEADER.ImageBase
    with catalog.open(encoding="utf-8-sig", newline="") as handle:
        ids = tuple(int(row["id_dec"]) for row in csv.DictReader(handle) if row.get("formula_hex", "").upper() == "0X42")

    checks = []
    for rva, expected_hex, meaning in ANCHORS:
        expected = bytes.fromhex(expected_hex)
        actual = dispatch.rva_bytes(pe, raw, rva, len(expected))
        checks.append((rva, actual == expected, meaning, " ".join(f"{b:02X}" for b in actual)))

    lines = [
        "# DCL recoil paired-result analysis", "",
        "Generated by `tools/analyze_dcl_recoil_transaction.py`.", "",
        "## Inputs", "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Ability catalog: `{catalog}`",
        f"- Output: `{output}`", "",
        "## Checks", "",
        f"- Formula `0x42` handler `0x{target:X}` (expected `0x{HANDLER_RVA:X}`): **{'PASS' if target == HANDLER_RVA else 'FAIL'}**.",
        f"- Catalog ids `{ids}` (expected `(351, 352, 353, 354)`): **{'PASS' if ids == (351, 352, 353, 354) else 'FAIL'}**.",
        "", "| RVA | Result | Meaning |", "| ---: | --- | --- |",
    ]
    for rva, passed, meaning, actual in checks:
        lines.append(f"| `0x{rva:X}` | {'PASS' if passed else f'FAIL (`{actual}`)'} | {meaning} |")

    lines.extend([
        "", "## Static interpretation", "",
        "- **Strong:** formula `0x42` explicitly stages two active result records in one calculation:",
        "  the target record at `qword[0x14186AF70]` and caster/self record at",
        "  `qword[0x14186AF60]`.",
        "- **Strong:** target `result+0x06 = PA*Y`; caster `result+0x06 = trunc((PA*Y)/X)`.",
        "  Both receive result flag `0x80`, so native application owns two HP debits with ordinary",
        "  clamp/KO lifecycle.",
        "- **Implementation consequence:** DCL recoil does not need a late direct self-HP write. At the",
        "  calculation/post-calculation boundary it can author both paired staged debits, or repoint",
        "  the action if the final design removes recoil. Amount and avoidance remain per-ability design.",
        "- **Live gate:** verify one execution yields one target apply and one caster apply after authored",
        "  paired rewrites; the record identities and fields themselves are closed offline.", "",
    ])

    ok = target == HANDLER_RVA and ids == (351, 352, 353, 354) and all(passed for _, passed, _, _ in checks)
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-recoil-paired-result-analysis.md"
    report, ok = render(args.exe, args.catalog, output)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all recoil paired-result checks PASS" if ok else "one or more recoil checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
