#!/usr/bin/env python3
"""Verify Self-Destruct's split victim/caster result and victim-only Oil rider."""
from __future__ import annotations

import argparse
import csv
import hashlib
import struct
import time
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_64, Cs

import analyze_dcl_reaction_dispatch as dispatch
import build_neuter_data as neuter


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = dispatch.DEFAULT_EXE
DEFAULT_CATALOG = ROOT / "work" / "wotl_ability_action_baseline.csv"
DISPATCH_TABLE_RVA = 0x682BC8
FORMULA_ID = 0x52
HANDLER_RVA = 0x308EE0
HANDLER_BYTES = bytes.fromhex(
    "48 83 EC 28 4C 8B 05 7D 20 56 01 48 8B 15 86 20 56 01 48 8B 0D 77 20 56 01 "
    "4C 3B C2 74 0A 0F B7 42 32 66 2B 42 30 EB 04 0F B7 42 30 C6 41 27 80 "
    "66 89 41 06 4C 3B C2 74 05 E8 22 DA FF FF 48 83 C4 28 C3"
)


def dispatch_target(pe: pefile.PE, raw: bytes) -> int:
    entry = dispatch.rva_bytes(pe, raw, DISPATCH_TABLE_RVA + FORMULA_ID * 8, 8)
    return struct.unpack("<Q", entry)[0] - pe.OPTIONAL_HEADER.ImageBase


def render(exe: Path, catalog_path: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    md = Cs(CS_ARCH_X86, CS_MODE_64)
    target = dispatch_target(pe, raw)
    actual = dispatch.rva_bytes(pe, raw, HANDLER_RVA, len(HANDLER_BYTES))
    with catalog_path.open(encoding="utf-8-sig", newline="") as handle:
        rows = [row for row in csv.DictReader(handle) if row.get("formula_hex", "").upper() == "0X52"]
    catalog_ok = (
        len(rows) == 1 and rows[0]["id_dec"] == "277" and rows[0]["aoe"] == "2"
        and rows[0]["inflict_status_mode"] == "AllOrNothing"
        and rows[0]["inflict_statuses"] == "Oil"
        and rows[0]["HitCaster"] == "1"
    )
    allowlist_ok = neuter.DCL_CONDITIONAL_STATUS_RIDER_ABILITY_IDS == (277,)
    dispatch_ok = target == HANDLER_RVA
    bytes_ok = actual == HANDLER_BYTES
    lines = [
        "# DCL Self-Destruct split-result analysis", "",
        "Generated by `tools/analyze_dcl_self_destruct.py`.", "",
        "## Inputs", "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Ability catalog: `{catalog_path}`",
        f"- Output: `{output}`", "",
        "## Mechanical checks", "",
        f"- Formula `0x52` dispatches to `0x{HANDLER_RVA:X}`: **{'PASS' if dispatch_ok else 'FAIL'}**.",
        f"- The complete handler byte window matches the current build: **{'PASS' if bytes_ok else 'FAIL'}**.",
        f"- The catalog has exactly ability 277, AoE 2, HitCaster, and AllOrNothing Oil: **{'PASS' if catalog_ok else 'FAIL'}**.",
        f"- The conditional-rider allowlist contains exactly ability 277: **{'PASS' if allowlist_ok else 'FAIL'}**.",
        "", "## Static interpretation", "",
        "- **Strong:** when target and caster differ, the victim HP debit is `caster.maxHp - caster.hp` and the handler calls the status finalizer.",
        "- **Strong:** when target and caster are the same unit, the HP debit is `caster.hp` and the handler skips the status finalizer.",
        "- Clearing only `InflictStatus` preserves both native numeric branches. The managed Oil rule must use `dcl.isSelf == 0`, so the caster's lethal self-result cannot acquire the victim-only rider.",
        "", "## Handler disassembly", "",
        *dispatch.disassembly(md, pe, raw, HANDLER_RVA, len(HANDLER_BYTES)), "",
    ]
    return "\n".join(lines), dispatch_ok and bytes_ok and catalog_ok and allowlist_ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()
    if not args.exe.exists():
        raise SystemExit(f"executable not found: {args.exe}")
    if not args.catalog.exists():
        raise SystemExit(f"ability catalog not found: {args.catalog}")
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-self-destruct-analysis.md"
    report, ok = render(args.exe, args.catalog, output)
    if not args.check_only:
        output.write_text(report, encoding="utf-8", newline="\n")
        print(f"wrote {output}")
    print("all Self-Destruct checks PASS" if ok else "one or more Self-Destruct checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
