#!/usr/bin/env python3
"""Verify the current-build Counter Tackle delivery and Rush payload contract."""
from __future__ import annotations

import argparse
import csv
import hashlib
import sqlite3
import time
from pathlib import Path

import pefile


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = Path(
    r"D:/SteamLibrary/steamapps/common/FINAL FANTASY TACTICS - The Ivalice Chronicles/FFT_enhanced.exe"
)
DEFAULT_CATALOG = ROOT / "work" / "wotl_ability_action_baseline.csv"
DEFAULT_OVERRIDE_DB = ROOT / "work" / "override_ability.neuter.sqlite"

ANCHORS = (
    (0x30B8B4, "8A 81 95 00 00 00", "loads reaction-set byte unit+0x95"),
    (0x30B8E0, "41 B2 02 41 84 C2", "tests unit+0x95 bit 0x02 for Counter Tackle"),
    (0x30B8E8, "80 3D 87 4E 4A 00 15", "rejects the disallowed incoming action class"),
    (0x30B8F5, "44 84 2D 9E 4E 4A 00", "requires incoming result flag 0x10"),
    (0x30B902, "B8 B4 01 00 00", "selects exact reaction id 436"),
    (0x282F46, "41 2B CC 0F 84 C8 01 00 00", "routes id 436 to its explicit pass-2 branch"),
    (0x283117, "41 B8 93 00 00 00", "selects payload ability 147 (Rush)"),
    (0x28311D, "45 8B CC", "requests source-target validation"),
    (0x283120, "BA 0B 00 00 00", "selects typed order 0x0B"),
    (0x283125, "E9 E7 FE FF FF", "enters the shared source-target order helper"),
    (0x283294, "48 63 1D 59 7D 5E 01", "helper loads source index RVA 0x186AFF4"),
    (0x283321, "88 47 0B", "helper writes source index into the target descriptor"),
)


def rva_bytes(pe: pefile.PE, raw: bytes, rva: int, size: int) -> bytes:
    offset = pe.get_offset_from_rva(rva)
    return raw[offset : offset + size]


def catalog_row(path: Path, ability_id: int) -> dict[str, str]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            if int(row["id_dec"]) == ability_id:
                return row
    raise ValueError(f"ability {ability_id} is missing from {path}")


def override_row(path: Path, ability_id: int) -> tuple[int, int, int] | None:
    if not path.exists():
        return None
    with sqlite3.connect(path) as connection:
        row = connection.execute(
            "SELECT Formula, X, Y FROM OverrideAbilityActionData WHERE Key=?", (ability_id,)
        ).fetchone()
    return None if row is None else tuple(int(value) for value in row)


def render(exe: Path, catalog: Path, override_db: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    checks = []
    for rva, expected_hex, meaning in ANCHORS:
        expected = bytes.fromhex(expected_hex)
        checks.append((rva, meaning, rva_bytes(pe, raw, rva, len(expected)) == expected))

    rush = catalog_row(catalog, 147)
    override = override_row(override_db, 147)
    catalog_ok = rush.get("name_ivc") == "Rush" and rush.get("formula_hex") == "0x37"
    override_preserves_formula = override is not None and override[0] == -1
    ok = all(passed for _, _, passed in checks) and catalog_ok and override_preserves_formula

    lines = [
        "# DCL native Counter Tackle analysis",
        "",
        "Generated by `tools/analyze_dcl_counter_tackle.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Ability catalog: `{catalog}`",
        f"- Active-data source: `{override_db}`",
        f"- Output: `{output}`",
        "",
        "## Anchor verification",
        "",
        "| RVA | Result | Meaning |",
        "| ---: | --- | --- |",
    ]
    for rva, meaning, passed in checks:
        lines.append(f"| `0x{rva:X}` | {'PASS' if passed else 'FAIL'} | {meaning} |")
    lines.extend(
        [
            f"| catalog `147` | {'PASS' if catalog_ok else 'FAIL'} | `{rush.get('name_ivc')}` uses formula `{rush.get('formula_hex')}`: {rush.get('formula_text')} |",
            f"| override `147` | {'PASS' if override_preserves_formula else 'FAIL'} | `Formula/X/Y={override}`; formula `-1` preserves native 0x37 |",
            "",
            "## Native contract",
            "",
            "Counter Tackle `436` is a real-code Courage reaction. Its pass-2 selector does not emit an",
            "abstract shove: it emits a validated source-target typed order `(type=0x0B, payload=147)`,",
            "where ability `147` is Rush. Formula `0x37` owns `random(1..Y) * PA` plus knockback. The",
            "current neuter data preserves formula `0x37` and only reduces its X/Y magnitude, so the",
            "knockback carrier remains intact while DCL damage can be rewritten downstream.",
            "",
            "## DCL boundary",
            "",
            "The final Squire Counter Tackle can retain native delivery. Its custom work is limited to",
            "the trigger policy: landed melee weapon strike, adjacency, Courage chance, and any chosen",
            "multi-hit cadence. The existing exact-id reaction filter can suppress nonqualifying native",
            "evaluations without replacing Rush or synthesizing displacement. Live proof is bounded to",
            "one accepted reaction confirming IVC knockback and source lifetime; no new effect mechanism",
            "is required offline.",
            "",
        ]
    )
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--override-db", type=Path, default=DEFAULT_OVERRIDE_DB)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-counter-tackle-analysis.md"
    report, ok = render(args.exe, args.catalog, args.override_db, output)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all Counter Tackle checks PASS" if ok else "one or more Counter Tackle checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
