#!/usr/bin/env python3
"""Prove the three native special-Reaction delivery validation boundaries."""
from __future__ import annotations

import argparse
import hashlib
import time
from dataclasses import dataclass
from pathlib import Path

import pefile

import analyze_dcl_reaction_dispatch as dispatch


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = dispatch.DEFAULT_EXE
MOD = ROOT / "codemod" / "fftivc.generic.chronicle.codemod" / "Mod.cs"
VALIDATOR = ROOT / "codemod" / "fftivc.generic.chronicle.codemod" / "RuntimeSettingsValidator.cs"


@dataclass(frozen=True)
class ByteAnchor:
    name: str
    rva: int
    expected: str
    meaning: str


BYTE_ANCHORS = (
    ByteAnchor(
        "typed-family-result",
        0x283019,
        "85 C0 0F 84 33 01 00 00 E9 3A 01 00 00",
        "ids 435/436/437/442 require zero from the shared typed-order helper; nonzero restores",
    ),
    ByteAnchor(
        "typed-bonecrusher-result",
        0x283148,
        "85 C0 75 14 44 88 67 01 C6 47 0A 05",
        "id 434 requires zero from its separate typed-order call; nonzero restores",
    ),
    ByteAnchor(
        "final-result",
        0x28315C,
        "85 C0 74 5D BA 14 00 00 00",
        "final VM-owned validator must return zero; nonzero falls through to restore",
    ),
    ByteAnchor(
        "failure-restore",
        0x283160,
        "BA 14 00 00 00 4C 8D 05 1C 7E 5E 01 44 8B CA 48 8B CF E8 95 31 DA FF",
        "failed delivery restores the previous 20-byte order and resumes scanning",
    ),
    ByteAnchor(
        "accepted-boundary",
        0x2831BD,
        "48 8B CB E8 6F F0 FF FF",
        "only a delivery that passes its path-specific typed check and final validation reaches accepted materialization",
    ),
)


SOURCE_ANCHORS = (
    (MOD, "public bool DclReactionDeliveryValidationProbeEnabled { get; set; } = false;", "disabled-by-default setting"),
    (MOD, "InstallDclReactionDeliveryValidationProbeIfEnabled(baseAddr);", "startup installation"),
    (MOD, "DCL_REACTION_TYPED_FAMILY_VALIDATION_RVA = 0x283019", "shared typed-family result hook binding"),
    (MOD, "DCL_REACTION_BONECRUSHER_VALIDATION_RVA = 0x283148", "Bonecrusher result hook binding"),
    (MOD, "DCL_REACTION_FINAL_VALIDATION_HOOK_RVA = 0x283157", "safe final-result hook begins at the validator call"),
    (MOD, "DCL_REACTION_FINAL_VALIDATION_HOOK_LENGTH = 7", "final hook relocates exactly call plus test"),
    (MOD, "DCL_REACTION_FINAL_RESTORE_RVA = 0x283160", "external typed-rejection restore target is outside the final hook"),
    (MOD, "AsmHookBehaviour.ExecuteAfter, DCL_REACTION_FINAL_VALIDATION_HOOK_LENGTH", "final result capture runs after the relocated call and test"),
    (MOD, "var hook = site.HookLength > 0", "only the final site passes an explicit relocation length"),
    (MOD, "site.Behaviour).Activate();", "typed sites use Reloaded.Hooks automatic instruction sizing"),
    (MOD, "SRP_STATE_DELIVERY_REJECTED = 6", "private rejected mailbox state"),
    (MOD, "[DCL-REACTION-DELIVERY-VALIDATION]", "bounded live evidence row"),
    (VALIDATOR, "live synthetic Reaction requires native delivery-validation capture", "fail-closed live composition"),
)


def render_report(exe: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    byte_rows: list[str] = []
    byte_ok = True
    for anchor in BYTE_ANCHORS:
        expected = bytes.fromhex(anchor.expected)
        actual = dispatch.rva_bytes(pe, raw, anchor.rva, len(expected))
        passed = actual == expected
        byte_ok &= passed
        actual_text = "PASS" if passed else "FAIL (`" + " ".join(f"{byte:02X}" for byte in actual) + "`)"
        byte_rows.append(
            f"| `{anchor.name}` | `0x{anchor.rva:X}` | {actual_text} | `{anchor.expected}` | {anchor.meaning} |"
        )

    source_cache = {path: path.read_text(encoding="utf-8") for path, _, _ in SOURCE_ANCHORS}
    source_rows: list[str] = []
    source_ok = True
    for path, token, meaning in SOURCE_ANCHORS:
        passed = token in source_cache[path]
        source_ok &= passed
        source_rows.append(f"| `{path.relative_to(ROOT)}` | {'PASS' if passed else 'FAIL'} | {meaning} |")

    ok = byte_ok and source_ok
    lines = [
        "# DCL Reaction native-delivery validation analysis",
        "",
        "Generated by `tools/analyze_dcl_reaction_delivery_validation.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Output: `{output}`",
        "",
        "## Native byte anchors",
        "",
        "| Name | RVA | Result | Expected bytes | Meaning |",
        "| --- | ---: | --- | --- | --- |",
        *byte_rows,
        "",
        "## Runtime source anchors",
        "",
        "| Source | Result | Meaning |",
        "| --- | --- | --- |",
        *source_rows,
        "",
        "## Transaction boundary",
        "",
        "The selector clears `unit+0x1CE` before native special-delivery validation. A consumed",
        "candidate is therefore not an accepted Reaction. The selector dispatches ids `435/436/437/442`",
        "through the typed helper whose result is tested at `0x283019`; Bonecrusher `434` uses a",
        "separate call/result at `0x283148`. Nonzero at either path-specific site restores the old",
        "order at `0x283160`. A surviving order then reaches the common final validator; nonzero at",
        "`0x28315C` also restores. Only a zero path-specific result followed by a zero final result can",
        "reach `0x2831BD`, pass-2 commit, and state-`0x2C` delivery.",
        "The final probe starts at `0x283157`, executes after exactly the seven-byte call+test span,",
        "and leaves the external restore entry at `0x283160` unmodified.",
        "",
        "The runtime probe records both results and changes only its private staged-mailbox byte to",
        "`rejected` on an exact synthetic failure. Game order, candidate, cadence, and effects remain",
        "native-owned. A later action may reserve a new request, while replay of the rejected action",
        "cannot masquerade as an accepted commit.",
        "",
        f"Overall static gate: **{'PASS' if ok else 'FAIL'}**.",
        "",
    ]
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-reaction-delivery-validation-analysis.md"
    report, ok = render_report(args.exe, output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("reaction delivery validation PASS" if ok else "reaction delivery validation FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
