#!/usr/bin/env python3
"""Verify the current-build native weapon line-of-fire dispatch and resolver contracts."""
from __future__ import annotations

import argparse
import csv
import hashlib
import time
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_64, Cs

import analyze_dcl_reaction_dispatch as dispatch


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = dispatch.DEFAULT_EXE
DEFAULT_ITEMS = ROOT / "work" / "item_catalog.csv"


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected: str
    meaning: str


ANCHORS = (
    Anchor("weapon-flags-read", 0x2802BC, "44 8A 68 01", "reads ITEM_WEAPON_DATA.AttackFlags from the selected hand"),
    Anchor("arc-test", 0x2802F5, "41 F6 C5 10", "tests WeaponAttackFlags.Arc"),
    Anchor("arc-resolver-call", 0x280306, "E8 D1 26 09 00", "calls the Arc projectile resolver at 0x3129DC"),
    Anchor("arc-target-compare", 0x28030D, "85 F6 78 08 85 C0 78 07 3B F0", "accepts only when candidate and Arc resolver result agree"),
    Anchor("direct-test", 0x28032F, "41 F6 C5 20", "tests WeaponAttackFlags.Direct"),
    Anchor("direct-resolver-call", 0x28039E, "E8 29 2B 09 00", "calls the Direct projectile resolver at 0x312ECC"),
    Anchor("direct-target-compare", 0x2803A5, "85 F6 78 08 85 C0 78 07 3B F0", "accepts only when candidate and Direct resolver result agree"),
    Anchor("lunging-test", 0x2803C7, "41 F6 C5 40", "tests WeaponAttackFlags.Lunging"),
    Anchor("lunging-resolver-call", 0x2803ED, "E8 E6 00 00 00", "calls the straight terrain resolver at 0x2804D8"),
    Anchor("direct-vm-entry", 0x312ECC, "E9 7C F1 2C 10", "Direct resolver enters protected VM code"),
)


def load_weapons(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return [row for row in csv.DictReader(handle) if row.get("secondary_kind") == "weapon"]


def render_report(exe: Path, items_path: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    md = Cs(CS_ARCH_X86, CS_MODE_64)
    weapons = load_weapons(items_path)

    rows: list[str] = []
    anchors_ok = True
    for anchor in ANCHORS:
        expected = bytes.fromhex(anchor.expected)
        actual = dispatch.rva_bytes(pe, raw, anchor.rva, len(expected))
        ok = actual == expected
        anchors_ok &= ok
        rows.append(
            f"| `{anchor.name}` | `0x{anchor.rva:X}` | {'PASS' if ok else 'FAIL'} | "
            f"`{dispatch.hex_bytes(actual)}` | {anchor.meaning} |"
        )

    families = ("Gun", "Crossbow", "Bow", "Pole")
    family_rows: list[str] = []
    family_expected = {
        "Gun": "Direct",
        "Crossbow": "Direct",
        "Bow": "Arc",
        "Pole": "Lunging",
    }
    family_ok = True
    for family in families:
        members = [row for row in weapons if row.get("item_category") == family]
        flags = Counter(row.get("weapon_attack_flags", "") for row in members)
        expected_flag = family_expected[family]
        ok = bool(members) and all(expected_flag in row.get("weapon_attack_flags", "").split(", ") for row in members)
        family_ok &= ok
        family_rows.append(
            f"| {family} | {len(members)} | `{expected_flag}` | "
            f"{'; '.join(f'`{name}` × {count}' for name, count in sorted(flags.items()))} | {'PASS' if ok else 'FAIL'} |"
        )

    arc_callers = dispatch.direct_callers(pe, raw, 0x3129DC)
    direct_callers = dispatch.direct_callers(pe, raw, 0x312ECC)
    lunging_callers = dispatch.direct_callers(pe, raw, 0x2804D8)
    caller_ok = 0x280306 in arc_callers and 0x28039E in direct_callers and 0x2803ED in lunging_callers

    lines = [
        "# DCL native weapon line-of-fire analysis",
        "",
        "Generated by `tools/analyze_dcl_weapon_line_of_fire.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Item catalog: `{items_path}`",
        f"- Output: `{output}`",
        "",
        "## Byte anchors",
        "",
        "| Name | RVA | Result | Actual bytes | Meaning |",
        "| --- | ---: | --- | --- | --- |",
        *rows,
        "",
        "## Weapon-family dispatch data",
        "",
        "| Family | Weapons | Required flag | Catalog flag sets | Result |",
        "| --- | ---: | --- | --- | --- |",
        *family_rows,
        "",
        "`WeaponAttackFlags` is the byte at `ITEM_WEAPON_DATA+1`: `Arc=0x10`, `Direct=0x20`,",
        "and `Lunging=0x40`. Guns and crossbows therefore share Direct line-of-fire; bows use the",
        "Arc resolver; poles use the straight Lunging terrain resolver.",
        "",
        "## Resolver call contract",
        "",
        "The weapon-target evaluator obtains the acting unit index from the 20-byte order context,",
        "selects the equipped hand, reads the weapon AttackFlags, and resolves the candidate unit at",
        "the staged target coordinates. The projectile calls use:",
        "",
        "```text",
        "rcx = acting unit index",
        "rdx = pointer to staged target coordinates (unit/order +0x1AC, +0x1AE, +0x1B0)",
        "r8d = candidate unit index resolved at those coordinates",
        "eax = projectile resolver's actual reached/intercepted unit index, or a negative failure",
        "```",
        "",
        "For both Arc and Direct, the call site accepts the candidate only when both indices are",
        "nonnegative and `candidate == resolver_result`. This equality is the native authoritative",
        "target-inclusion/line-of-fire verdict for the selected weapon trajectory.",
        "",
        f"- Arc resolver callers: {', '.join(f'`0x{rva:X}`' for rva in arc_callers) or 'none'}.",
        f"- Direct resolver callers: {', '.join(f'`0x{rva:X}`' for rva in direct_callers) or 'none'}.",
        f"- Lunging resolver callers: {', '.join(f'`0x{rva:X}`' for rva in lunging_callers) or 'none'}.",
        "",
        "## Weapon-target dispatch window",
        "",
        *dispatch.disassembly(md, pe, raw, 0x2802BC, 0x198),
        "",
        "## Lunging terrain resolver",
        "",
        *dispatch.disassembly(md, pe, raw, 0x2804D8, 0x371),
        "",
        "## Arc projectile resolver",
        "",
        *dispatch.disassembly(md, pe, raw, 0x3129DC, 0x36A),
        "",
        "## Static interpretation",
        "",
        "- **Strong:** the engine has a native weapon-specific line-of-fire authority, selected from",
        "  the weapon's `AttackFlags`; Euclidean/Manhattan distance is not a substitute.",
        "- **Strong:** Arc and Direct return the actually reached/intercepted unit index. Comparing",
        "  that result with the intended source is the authoritative inclusion test needed by",
        "  Countershot and other returned weapon attacks.",
        "- **Strong:** the Arc resolver is real code and performs trajectory/collision work; the Direct",
        "  resolver immediately enters protected VM code, so its internal obstacle algorithm cannot",
        "  be reconstructed completely offline from aligned real code.",
        "- **Strong:** `0x2804D8` is not generic projectile LoS. It is selected specifically by the",
        "  `Lunging` flag and rejects non-cardinal paths while recursively testing intermediate terrain.",
        "- **Implementation boundary:** invoking Arc/Direct from an unrelated poller is unsafe because",
        "  both participate in mutable targeting globals. Reuse must occur synchronously on the game",
        "  thread at a native targeting/Reaction boundary, or the DCL must let a synthesized native",
        "  basic weapon order run the same resolver. A dedicated observe-only proof must establish",
        "  which option preserves target/source identity without redirecting into an interceptor.",
        "",
    ]
    return "\n".join(lines), anchors_ok and family_ok and caller_ok


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--items", type=Path, default=DEFAULT_ITEMS)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check-only", action="store_true", help="validate anchors without writing a report")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-weapon-line-of-fire-analysis.md"
    report, ok = render_report(args.exe, args.items, output)
    if args.check_only:
        print(f"checked {args.exe}")
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(report, encoding="utf-8", newline="\n")
        print(f"wrote {output}")
    print("all line-of-fire anchors, family flags, and caller checks PASS" if ok else "one or more line-of-fire checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
