#!/usr/bin/env python3
"""Verify formula-0x20's damage carrier and Muramasa's grouped rider replacement."""
from __future__ import annotations

import argparse
import csv
import hashlib
import time
from pathlib import Path

import pefile

import analyze_dcl_status_transactions as status_tx
import build_neuter_data as neuter


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = status_tx.DEFAULT_EXE
DEFAULT_CATALOG = status_tx.DEFAULT_CATALOG
GROUPED_SOURCE = ROOT / "codemod" / "fftivc.generic.chronicle.codemod" / "DclStatusGroupedCarrier.cs"
FORMULA_ID = 0x20
HANDLER_RVA = 0x307D4C
STATUS_BUILDER_RVA = 0x306558
DAMAGE_TAIL_RVA = 0x306F48
HANDLER_BYTES = bytes.fromhex(
    "48 83 EC 28 E8 03 E8 FF FF 48 8B 05 1C 32 56 01 0F B6 48 3F "
    "0F B6 05 37 8A 4A 00 66 89 05 04 8A 4A 00 66 89 0D FB 89 4A 00 "
    "48 83 C4 28 E9 CA F1 FF FF"
)


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def render(exe: Path, catalog_path: Path, grouped_source: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    target = status_tx.dispatch_targets(pe, raw)[FORMULA_ID]
    dispatch_ok = target == HANDLER_RVA
    actual = status_tx.rva_bytes(pe, raw, HANDLER_RVA, len(HANDLER_BYTES))
    handler_ok = actual == HANDLER_BYTES

    rows = [
        row for row in load_rows(catalog_path)
        if row["formula_hex"].upper() == "0X20" and row["inflict_statuses"].strip()
    ]
    by_id = {int(row["id_dec"]): row for row in rows}
    catalog_ok = (
        set(by_id) == {80, 82}
        and by_id[80]["inflict_status_mode"] == "AllOrNothing"
        and by_id[80]["inflict_statuses"] == "Slow"
        and by_id[82]["inflict_status_mode"] == "Random"
        and by_id[82]["inflict_statuses"] == "Confusion|DeathSentence"
    )
    data_allowlist_ok = {80, 82}.issubset(neuter.DCL_STATUS_RIDER_ABILITY_IDS)
    source = " ".join(grouped_source.read_text(encoding="utf-8").split())
    grouped_mapping_ok = all(token in source for token in (
        "new(1, 0x10)",
        "new(4, 0x01)",
        "82 => MuramasaBits",
        "82 => DclStatusGroups.RandomOne",
    ))

    lines = [
        "# DCL formula-0x20 Muramasa carrier analysis",
        "",
        "Generated by `tools/analyze_dcl_formula20_muramasa.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Ability catalog: `{catalog_path}`",
        f"- Output: `{output}`",
        "",
        "## Native contract",
        "",
        f"- Formula `0x20` dispatch target: `0x{target:X}`: **{'PASS' if dispatch_ok else 'FAIL'}**.",
        f"- Handler bytes at `0x{HANDLER_RVA:X}`: **{'PASS' if handler_ok else 'FAIL'}**.",
        f"- Shared status-result builder call target: `0x{STATUS_BUILDER_RVA:X}`.",
        f"- Unconditional damage-tail jump target: `0x{DAMAGE_TAIL_RVA:X}`.",
        "",
        "The handler first delegates InflictStatus interpretation to the common status builder,",
        "copies MA and Y, and then unconditionally jumps into the non-Faith `MA * Y` damage tail.",
        "Clearing only InflictStatus therefore removes Muramasa's native random rider without",
        "removing the HP result that carries execution into the managed pre-clamp callback.",
        "",
        "## Exact rider inventory",
        "",
        "| Ability | Native mode | Native statuses | Managed ownership |",
        "| ---: | --- | --- | --- |",
        "| 80 Ame-no-Murakumo | AllOrNothing | Slow | independent data-suppressed rider |",
        "| 82 Muramasa | Random | Confusion / Death Sentence | `random-one` data-suppressed group |",
        "",
        f"- Exact catalog inventory: **{'PASS' if catalog_ok else 'FAIL'}**.",
        f"- Both ids are in the data-suppression allowlist: **{'PASS' if data_allowlist_ok else 'FAIL'}**.",
        f"- Muramasa's exact two-bit C# group/mode mapping: **{'PASS' if grouped_mapping_ok else 'FAIL'}**.",
        "",
        "Muramasa requires two `suppressed-by-data`, `ActionType=-1` rules in one `random-one`",
        "ContestGroup. The runtime selects one member, rolls resistance once, clears the unselected",
        "bit, and lets the native packet validator/committer apply the selected non-resisted bit.",
        "",
    ]
    ok = dispatch_ok and handler_ok and catalog_ok and data_allowlist_ok and grouped_mapping_ok
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--grouped-source", type=Path, default=GROUPED_SOURCE)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()
    for path, label in ((args.exe, "executable"), (args.catalog, "ability catalog"), (args.grouped_source, "grouped carrier source")):
        if not path.exists():
            raise SystemExit(f"{label} not found: {path}")
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-formula20-muramasa-analysis.md"
    report, ok = render(args.exe, args.catalog, args.grouped_source, output)
    if not args.check_only:
        output.write_text(report, encoding="utf-8", newline="\n")
        print(f"wrote {output}")
    print("all formula-0x20 Muramasa checks PASS" if ok else "one or more formula-0x20 Muramasa checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
