#!/usr/bin/env python3
"""Verify native Critical: Recover HP trigger staging and full-heal effect construction."""
from __future__ import annotations

import argparse
import hashlib
import time
from pathlib import Path

import pefile


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = Path(
    r"D:/SteamLibrary/steamapps/common/FINAL FANTASY TACTICS - The Ivalice Chronicles/FFT_enhanced.exe"
)

ANCHORS = (
    (0x30AAC5, "48 8B 05 9C 04 56 01", "loads the post-hit reaction unit"),
    (0x30AACC, "8A 88 95 00 00 00", "loads reaction-set byte unit+0x95"),
    (0x30AAD2, "84 CA", "tests unit+0x95 bit 0x40"),
    (0x30AAD6, "B9 AF 01 00 00", "selects exact reaction id 431"),
    (0x30AAFF, "E8 60 13 00 00", "enters the real-code Brave gate"),
    (0x30974E, "81 E9 AF 01 00 00", "reaction-effect switch begins at id 431"),
    (0x309754, "0F 84 17 01 00 00", "routes id 431 to its effect body"),
    (0x309871, "48 8B 05 F0 16 56 01", "loads the reaction unit for HP recovery"),
    (0x30987F, "0F B7 48 32", "loads MaxHP from unit+0x32"),
    (0x309883, "66 2B 48 30", "subtracts current HP from unit+0x30"),
    (0x309887, "66 89 4B 08", "writes the entire missing-HP amount to result+0x08"),
    (0x30988B, "40 B7 40", "selects HP-credit result flag 0x40"),
)


def rva_bytes(pe: pefile.PE, raw: bytes, rva: int, size: int) -> bytes:
    offset = pe.get_offset_from_rva(rva)
    return raw[offset : offset + size]


def render(exe: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    checks = []
    for rva, expected_hex, meaning in ANCHORS:
        expected = bytes.fromhex(expected_hex)
        checks.append((rva, meaning, rva_bytes(pe, raw, rva, len(expected)) == expected))
    ok = all(passed for _, _, passed in checks)

    lines = [
        "# DCL native Critical: Recover HP analysis",
        "",
        "Generated by `tools/analyze_dcl_critical_recover_hp.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Output: `{output}`",
        "",
        "## Anchor verification",
        "",
        "| RVA | Result | Meaning |",
        "| ---: | --- | --- |",
    ]
    for rva, meaning, passed in checks:
        lines.append(f"| `0x{rva:X}` | {'PASS' if passed else 'FAIL'} | {meaning} |")
    lines.extend(
        [
            "",
            "## Native contract",
            "",
            "The post-hit real-code selector tests `unit+0x95 & 0x40`, evaluates exact reaction id",
            "`431`, and routes an accepted result through the reaction queue. Its effect body computes",
            "`MaxHP - currentHP`, writes that complete missing-HP amount to the HP-credit field, and sets",
            "the native HP-credit result flag. Native Critical: Recover HP is therefore a full heal to",
            "maximum at effect calculation time, not a small fixed or proportional clutch heal.",
            "",
            "## DCL boundary",
            "",
            "The Squire's Grit text calls for a minor low-HP clutch bonus and leaves the exact payoff",
            "open. Record `431` supplies an appropriate post-hit presentation/HP-credit lifecycle but",
            "its native amount is too large for that contract. If Grit chooses healing, the DCL must",
            "retain the native carrier and replace only the reaction HP credit through reaction-aware",
            "formula provenance. The exact amount, threshold, cadence, and whether healing is the final",
            "payoff remain design decisions rather than engine questions.",
            "",
        ]
    )
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-critical-recover-hp-analysis.md"
    report, ok = render(args.exe, output)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all Critical: Recover HP checks PASS" if ok else "one or more Critical: Recover HP checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
