#!/usr/bin/env python3
"""Verify the native surfaces used to compose Fear flee plus one legal action."""
from __future__ import annotations

import argparse
import hashlib
import time
from dataclasses import dataclass
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_64, Cs
from capstone.x86 import X86_OP_MEM, X86_REG_RIP

import analyze_dcl_reaction_dispatch as dispatch


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = dispatch.DEFAULT_EXE


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected: str
    meaning: str


ANCHORS = (
    Anchor(
        "forced-control-caller-contract",
        0x1098B8B5,
        "E8 42 03 A0 EF 39 D8 75 0E 44 88 25 48 6A EE F0 89 D8 E9 90 00 00 00 85 C0 0F 85 86 00 00 00",
        "-1 fails, nonzero is handled, and zero alone enters ordinary planning",
    ),
    Anchor(
        "immobilize-reachability-gate",
        0x31FA96,
        "48 8B 05 03 34 55 01 F6 40 65 08 0F 85 F0 00 00 00",
        "effective Don't Move bypasses movement-range expansion",
    ),
    Anchor(
        "immobilize-current-tile-only",
        0x31FB97,
        "0F B6 05 33 29 55 01 8A 0D 2C 29 55 01 D3 FF 48 8D 0C C0 0F B6 05 21 29 55 01 48 8D 14 48 66 41 89 BC 55 14 21 87 01",
        "the bypass records only the active unit's current tile in reachability",
    ),
    Anchor(
        "ordinary-action-planner",
        0x38D658,
        "48 8B C4 48 89 58 08 48 89 70 10 48 89 78 18 4C 89 70 20 41 57 48 83 EC 20",
        "ordinary AI action-plan owner",
    ),
    Anchor(
        "ordinary-planner-selector",
        0x38D71E,
        "E8 F9 09 00 00 41 3B C6 75 04 33 DB EB 11",
        "ordinary planner invokes the same movement candidate selector",
    ),
    Anchor(
        "ordinary-planner-winner",
        0x38D752,
        "33 D2 B9 FF 00 00 00 E8 32 3C F9 FF",
        "ordinary planner chooses a winner after action evaluation",
    ),
    Anchor(
        "composed-plan-publication",
        0x38D87F,
        "0F B6 05 47 4C 4E 01 B9 DF 01 00 00 C6 05 16 56 4E 01 00 41 8B 84 87 64 23 87 01 89 05 0C 56 4E 01",
        "the winning X/Y/layer record is published to the executable plan slot",
    ),
)


CALLS = {
    0x1098B8B5: 0x38BBFC,
    0x38D71E: 0x38E11C,
    0x38D759: 0x321390,
}


def _hex_bytes(value: bytes) -> str:
    return " ".join(f"{byte:02X}" for byte in value)


def _direct_target(rva: int, encoded: bytes) -> int:
    if len(encoded) != 5 or encoded[0] != 0xE8:
        raise ValueError(f"RVA 0x{rva:X} is not a direct call")
    return rva + 5 + int.from_bytes(encoded[1:], "little", signed=True)


def render_report(exe: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    image_base = pe.OPTIONAL_HEADER.ImageBase
    md = Cs(CS_ARCH_X86, CS_MODE_64)
    md.detail = True

    rows: list[str] = []
    anchors_ok = True
    for anchor in ANCHORS:
        expected = bytes.fromhex(anchor.expected)
        actual = dispatch.rva_bytes(pe, raw, anchor.rva, len(expected))
        passed = actual == expected
        anchors_ok &= passed
        rows.append(
            f"| `{anchor.name}` | `0x{anchor.rva:X}` | "
            f"{'PASS' if passed else f'FAIL (`{_hex_bytes(actual)}`)'} | {anchor.meaning} |"
        )

    call_rows: list[str] = []
    calls_ok = True
    for site, expected in CALLS.items():
        encoded = dispatch.rva_bytes(pe, raw, site, 5)
        try:
            actual = _direct_target(site, encoded)
        except ValueError:
            actual = -1
        passed = actual == expected
        calls_ok &= passed
        call_rows.append(
            f"| `0x{site:X}` | `{('invalid' if actual < 0 else f'0x{actual:X}')}` | "
            f"`0x{expected:X}` | {'PASS' if passed else 'FAIL'} |"
        )

    publish_instruction = next(
        md.disasm(dispatch.rva_bytes(pe, raw, 0x38D89A, 6), image_base + 0x38D89A), None
    )
    publish_rva = -1
    if publish_instruction is not None:
        for operand in publish_instruction.operands:
            if operand.type == X86_OP_MEM and operand.mem.base == X86_REG_RIP:
                publish_rva = (
                    publish_instruction.address
                    + publish_instruction.size
                    + operand.mem.disp
                    - image_base
                )
    publication_ok = publish_rva == 0x1872EAC

    overall = anchors_ok and calls_ok and publication_ok
    lines = [
        "# DCL Fear plan-composition analysis",
        "",
        "Generated by `tools/analyze_dcl_fear_plan_composition.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Output: `{output}`",
        "",
        "## Byte anchors",
        "",
        "| Name | RVA | Result | Meaning |",
        "| --- | ---: | --- | --- |",
        *rows,
        "",
        "## Native call edges",
        "",
        "| Source | Actual target | Expected target | Result |",
        "| ---: | ---: | ---: | --- |",
        *call_rows,
        "",
        f"- Composed-plan publication target: `0x{publish_rva:X}`; expected `0x1872EAC`: "
        f"**{'PASS' if publication_ok else 'FAIL'}**.",
        "",
        "## Settled composition contract",
        "",
        "The forced-control caller treats a nonzero resolver result as a complete plan and skips",
        "ordinary planning. Fear must therefore compose its legal action before returning handled.",
        "The native movement builder tests effective Immobilize at `unit+0x65 & 0x08`; that branch",
        "skips range expansion and records only the current tile. The coordinator may synchronously",
        "lend the chosen flee tile, clear effective Chicken, set effective Immobilize, and call the",
        "ordinary planner. Managed Fear ownership remains active for target authorization during",
        "that loan. The ordinary planner reuses the movement selector, chooses an action-plan winner,",
        "and publishes its X/Y/layer tuple at `0x1872EAC`.",
        "",
        "A valid composition restores the original coordinate tuple and both effective-status bytes",
        "byte-exactly, requires the published plan tile to equal the selected flee tile, and returns",
        "through the native handled epilogue. Any mismatch restores every loan and falls back to the",
        "untouched Chicken branch.",
        "",
        "## Remaining live falsifier",
        "",
        "Static evidence proves the bounded planning transaction but not the executor's visible",
        "ordering. A live run must show one Fear status roll, one composed plan with equal selected",
        "and planned tiles, exact restoration, forced movement, and either one legal non-hostile",
        "action or native Wait. No opposing-target action may execute.",
        "",
        f"Overall static gate: **{'PASS' if overall else 'FAIL'}**.",
        "",
    ]
    return "\n".join(lines), overall


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-fear-plan-composition-analysis.md"
    report, ok = render_report(args.exe, output)
    if not args.check_only:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(report, encoding="utf-8", newline="\n")
        print(f"wrote {output}")
    print("DCL Fear plan composition PASS" if ok else "DCL Fear plan composition FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
