#!/usr/bin/env python3
"""Verify the current-build native Golem pool transaction."""
from __future__ import annotations

import argparse
import csv
import hashlib
import struct
import time
from dataclasses import dataclass
from pathlib import Path

import pefile

import analyze_dcl_reaction_dispatch as dispatch


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = dispatch.DEFAULT_EXE
DEFAULT_CATALOG = ROOT / "work" / "wotl_ability_action_baseline.csv"
DISPATCH_TABLE_RVA = 0x682BC8
FORMULA_ID = 0x14
FORMULA_HANDLER_RVA = 0x307848
POOL_RVA = 0x186B020


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected: str
    meaning: str


ANCHORS = (
    Anchor(
        "formula-success-marker",
        0x3078D4,
        "48 8B 05 95 36 56 01 40 38 38 74 0C B9 01 00 00 00 66 89 48 12 88 48 27",
        "a successful formula-0x14 calculation stages result+0x12=1 and result+0x27=1",
    ),
    Anchor(
        "pool-debit-selector",
        0x30A561,
        "0F B7 41 12 66 85 C0 79 34 48 8B 05 F7 09 56 01 0F B6 90 EE 01 00 00 0F BF 41 06 48 C1 EA 04 83 E2 03",
        "a negative result+0x12 selects one of four pools from target unit+0x1EE high bits",
    ),
    Anchor(
        "pool-saturating-debit",
        0x30A583,
        "0F B7 8C 57 20 B0 86 01 2B C8 66 0F 49 D9 66 89 9C 57 20 B0 86 01 E9 7B FF FF FF",
        "the pool becomes max(pool-result+0x06,0), and the ordinary HP debit is skipped",
    ),
    Anchor(
        "pool-initialize-from-max-hp",
        0x30A59E,
        "41 84 C5 74 21 48 8B 05 BE 09 56 01 41 8B F5 0F B6 48 05 0F B7 40 32 48 C1 E9 04 83 E1 03 66 89 84 4F 20 B0 86 01",
        "result bit 1 initializes the selected team pool from unit+0x32 MaxHP",
    ),
    Anchor(
        "pool-state-import",
        0x30D855,
        "48 8B 41 18 48 89 05 C0 D7 55 01",
        "the native battle-state importer copies the packed four-pool qword into the static pool block",
    ),
    Anchor(
        "pool-state-export",
        0x30DA63,
        "48 8B 05 B6 D5 55 01 48 89 41 18",
        "the matching exporter copies the packed four-pool qword out of the static pool block",
    ),
)


def dispatch_target(pe: pefile.PE, raw: bytes) -> int:
    entry = dispatch.rva_bytes(pe, raw, DISPATCH_TABLE_RVA + FORMULA_ID * 8, 8)
    return struct.unpack("<Q", entry)[0] - pe.OPTIONAL_HEADER.ImageBase


def catalog_rows(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return [row for row in csv.DictReader(handle) if row.get("formula_hex", "").upper() == "0X14"]


def render(exe: Path, catalog_path: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    target = dispatch_target(pe, raw)
    rows = catalog_rows(catalog_path)
    catalog_ok = len(rows) == 1 and rows[0].get("id_dec") == "65" and rows[0].get("name_ivc") == "Golem"

    anchor_rows: list[tuple[Anchor, bool, str]] = []
    for anchor in ANCHORS:
        expected = bytes.fromhex(anchor.expected)
        actual = dispatch.rva_bytes(pe, raw, anchor.rva, len(expected))
        anchor_rows.append((anchor, actual == expected, " ".join(f"{value:02X}" for value in actual)))

    lines = [
        "# DCL Golem pool analysis", "",
        "Generated by `tools/analyze_dcl_golem_pool.py`.", "",
        "## Inputs", "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Ability catalog: `{catalog_path}`",
        f"- Pool block: RVA `0x{POOL_RVA:X}` / VA `0x{pe.OPTIONAL_HEADER.ImageBase + POOL_RVA:X}`",
        f"- Output: `{output}`", "",
        "## Dispatch and catalog", "",
        f"- Formula `0x14` handler: `0x{target:X}` (expected `0x{FORMULA_HANDLER_RVA:X}`): "
        f"**{'PASS' if target == FORMULA_HANDLER_RVA else 'FAIL'}**.",
        f"- Formula catalog contains only ability 65 Golem: **{'PASS' if catalog_ok else 'FAIL'}**.",
        "", "## Byte anchors", "",
        "| Name | RVA | Result | Meaning |", "| --- | ---: | --- | --- |",
    ]
    for anchor, passed, actual in anchor_rows:
        result = "PASS" if passed else f"FAIL (`{actual}`)"
        lines.append(f"| `{anchor.name}` | `0x{anchor.rva:X}` | {result} | {anchor.meaning} |")

    lines.extend([
        "", "## Static interpretation", "",
        "- **Strong:** the native state is four unsigned 16-bit pools packed at RVA `0x186B020`;",
        "  both the initializer and consumer select an entry from a two-bit team/faction index.",
        "- **Strong:** successful Golem application writes the selected unit's MaxHP into its pool.",
        "  Golem is self-targeted in the catalog, so stock activation seeds the caster's team pool",
        "  from the caster's MaxHP.",
        "- **Strong:** an intercepted result is marked by a negative `result+0x12`. The state apply",
        "  path subtracts the staged HP debit at `result+0x06`, clamps the pool to zero, and skips",
        "  the ordinary HP debit entirely. An overkill hit therefore empties the remaining pool but",
        "  does not spill residual damage through that same hit.",
        "- **Strong:** the packed pool participates in the native battle-state import/export block.",
        "  The DCL can reuse the native lifecycle and author activation magnitude at the mapped pool",
        "  write; it does not need a separate managed barrier store.",
        "- **Live gate:** confirm which incoming action families receive the negative interception",
        "  marker and that recasting overwrites the active team pool exactly once.", "",
    ])

    ok = target == FORMULA_HANDLER_RVA and catalog_ok and all(passed for _, passed, _ in anchor_rows)
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    if not args.exe.exists():
        raise SystemExit(f"executable not found: {args.exe}")
    if not args.catalog.exists():
        raise SystemExit(f"ability catalog not found: {args.catalog}")
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-golem-pool-analysis.md"
    report, ok = render(args.exe, args.catalog, output)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all Golem pool checks PASS" if ok else "one or more Golem pool checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
