#!/usr/bin/env python3
"""Verify the current-build native equipment-break selector and result carriers."""
from __future__ import annotations

import argparse
import csv
import hashlib
import struct
import time
from dataclasses import dataclass
from pathlib import Path

import pefile

import analyze_dcl_reaction_dispatch as dispatch


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = dispatch.DEFAULT_EXE
DEFAULT_CATALOG = ROOT / "work" / "wotl_ability_action_baseline.csv"
DISPATCH_TABLE_RVA = 0x682BC8
TARGETS = {0x25: 0x307E70, 0x2E: 0x308534}
EXPECTED_IDS = {0x25: (138, 139, 140, 141), 0x2E: (160, 161, 162, 163)}


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected: str
    meaning: str


ANCHORS = (
    Anchor(
        "shared-selector-entry",
        0x3065C0,
        "40 53 48 83 EC 20 4C 8B 05 A3 49 56 01 4C 8B 0D 94 49 56 01 41 C6 40 1B FE",
        "the shared exact-id selector starts with result+0x1B invalid and reads the target equipment block",
    ),
    Anchor(
        "accessory-slot",
        0x3066AB,
        "41 C6 40 1B 20 41 0F B7 41 1E E9 03 01 00 00",
        "Accessory selects target+0x1E and mask 0x20",
    ),
    Anchor(
        "shield-slots",
        0x3066D1,
        "41 C6 40 1B 08 41 0F B7 41 22 E9 DD 00 00 00",
        "Shield first selects target+0x22 and mask 0x08; the alternate branch uses +0x26/mask 0x02",
    ),
    Anchor(
        "armor-slot",
        0x306725,
        "41 C6 40 1B 40 41 0F B7 41 1C E9 89 00 00 00",
        "Armor selects target+0x1C and mask 0x40",
    ),
    Anchor(
        "weapon-slots",
        0x30677B,
        "41 C6 40 1B 10 41 0F B7 41 20 EB 36 41 C6 40 1B 04 41 0F B7 41 24 EB 2A",
        "Weapon selects target+0x20/mask 0x10 or target+0x24/mask 0x04",
    ),
    Anchor(
        "helm-slot-and-selector-output",
        0x3067B3,
        "41 C6 40 1B 80 41 0F B7 41 1A 66 41 89 40 04 33 C0",
        "Helm selects target+0x1A/mask 0x80; valid selection writes item id to result+0x04 and returns zero",
    ),
    Anchor(
        "rend-nested-attack",
        0x307EA7,
        "40 8A B1 A1 01 00 00 0F B7 B9 A2 01 00 00 C6 81 A1 01 00 00 01 66 89 A9 A2 01 00 00 48 81 C1 A0 01 00 00 8A 15 91 88 4A 00 E8 D7 1A 00 00",
        "formula 0x25 temporarily writes order type 1/action 0 and re-enters computeActionResult when no selected equipment exists",
    ),
    Anchor(
        "rend-break-marker",
        0x307FA7,
        "B8 04 00 00 00 66 41 89 42 12",
        "successful formula-0x25 equipment break stages result+0x12 bit 0x0004",
    ),
    Anchor(
        "crush-break-marker-and-damage-tail",
        0x3085C2,
        "E8 B1 DE FF FF 4C 8B 15 A2 29 56 01 41 80 3A 00 75 15 83 3D A5 29 56 01 00 75 7D B8 00 20 00 00 66 41 09 42 12 EB 71 B8 04 00 00 00 66 41 89 42 12 48 8B 05 7E 29 56 01",
        "formula 0x2E stages break bit 0x0004 for a valid selected item, then continues into its physical damage chain",
    ),
    Anchor(
        "protected-side-effect-before-resource-apply",
        0x30A5C4,
        "E8 97 16 00 00 48 8B 2D A0 09 56 01 48 8B 3D 91 09 56 01 0F BF 45 06",
        "the protected native side-effect applicator runs before ordinary staged HP/MP application",
    ),
)


def dispatch_target(pe: pefile.PE, raw: bytes, formula_id: int) -> int:
    entry = dispatch.rva_bytes(pe, raw, DISPATCH_TABLE_RVA + formula_id * 8, 8)
    return struct.unpack("<Q", entry)[0] - pe.OPTIONAL_HEADER.ImageBase


def catalog_ids(path: Path) -> dict[int, tuple[int, ...]]:
    found: dict[int, list[int]] = {formula: [] for formula in TARGETS}
    with path.open(encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            value = row.get("formula_hex", "").upper()
            for formula in TARGETS:
                if value == f"0X{formula:02X}":
                    found[formula].append(int(row["id_dec"]))
    return {formula: tuple(ids) for formula, ids in found.items()}


def render(exe: Path, catalog_path: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    actual_targets = {formula: dispatch_target(pe, raw, formula) for formula in TARGETS}
    actual_ids = catalog_ids(catalog_path)

    anchor_rows: list[tuple[Anchor, bool, str]] = []
    for anchor in ANCHORS:
        expected = bytes.fromhex(anchor.expected)
        actual = dispatch.rva_bytes(pe, raw, anchor.rva, len(expected))
        anchor_rows.append((anchor, actual == expected, " ".join(f"{value:02X}" for value in actual)))

    lines = [
        "# DCL equipment-break transaction analysis", "",
        "Generated by `tools/analyze_dcl_equipment_break.py`.", "",
        "## Inputs", "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Ability catalog: `{catalog_path}`",
        f"- Output: `{output}`", "",
        "## Dispatch and catalog", "",
        "| Formula | Handler | Expected | Catalog ids | Expected ids | Result |",
        "| --- | ---: | ---: | --- | --- | --- |",
    ]
    for formula, expected_target in TARGETS.items():
        passed = actual_targets[formula] == expected_target and actual_ids[formula] == EXPECTED_IDS[formula]
        lines.append(
            f"| `0x{formula:02X}` | `0x{actual_targets[formula]:X}` | `0x{expected_target:X}` | "
            f"`{actual_ids[formula]}` | `{EXPECTED_IDS[formula]}` | {'PASS' if passed else 'FAIL'} |"
        )

    lines.extend(["", "## Byte anchors", "", "| Name | RVA | Result | Meaning |", "| --- | ---: | --- | --- |"])
    for anchor, passed, actual in anchor_rows:
        result = "PASS" if passed else f"FAIL (`{actual}`)"
        lines.append(f"| `{anchor.name}` | `0x{anchor.rva:X}` | {result} | {anchor.meaning} |")

    lines.extend([
        "", "## Static interpretation", "",
        "- **Strong:** formulas `0x25` and `0x2E` share the exact-id equipment selector already used",
        "  by Steal/Plunder. A valid selection stages the item at `result+0x04`, its concrete slot mask",
        "  at `result+0x1B`, and returns zero.",
        "- **Strong:** successful native equipment destruction is carried by `result+0x12` bit",
        "  `0x0004`. Formula `0x2E` retains its ordinary physical damage chain after staging that bit.",
        "- **Strong:** formula `0x25` is re-entrant: without matching equipment it temporarily replaces",
        "  the outer order with Basic Attack `(type=1,id=0)`, calls the universal calculation entry,",
        "  then restores the Rend order. Repointing the ability away from `0x25` removes this nested",
        "  provenance hazard.",
        "- **Strong:** the DCL Knight definition rejects permanent equipment loss in favor of reversible",
        "  Guard Break and Bind Weapon. The data-first implementation is to repoint the reused action",
        "  records to an ordinary authored physical/status formula. If a native break formula must be",
        "  retained for presentation, clear result bit `0x0004` at the post-calculation boundary before",
        "  the protected side-effect applicator; preserve or replace the numeric damage independently.",
        "- **Live gate:** native destruction cardinality matters only for abilities intentionally left on",
        "  the vanilla break transaction. The DCL replacement itself needs physical/status integration",
        "  tests, not a reverse-engineering test of permanent inventory loss.", "",
    ])

    dispatch_ok = all(actual_targets[f] == TARGETS[f] and actual_ids[f] == EXPECTED_IDS[f] for f in TARGETS)
    ok = dispatch_ok and all(passed for _, passed, _ in anchor_rows)
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    if not args.exe.exists():
        raise SystemExit(f"executable not found: {args.exe}")
    if not args.catalog.exists():
        raise SystemExit(f"ability catalog not found: {args.catalog}")
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-equipment-break-analysis.md"
    report, ok = render(args.exe, args.catalog, output)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all equipment-break checks PASS" if ok else "one or more equipment-break checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
