#!/usr/bin/env python3
"""Verify the current-build state-0x2C executed-Reaction boundary before cleanup."""
from __future__ import annotations

import argparse
import hashlib
import time
from dataclasses import dataclass
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_64, Cs

import analyze_dcl_reaction_dispatch as dispatch


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = dispatch.DEFAULT_EXE


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected: str
    meaning: str


ANCHORS = (
    Anchor("state-2b-vm-poll", 0x212D50, "E8 CF 15 06 00", "state 0x2B calls the VM execution poll worker"),
    Anchor("state-2b-vm-apply", 0x212D69, "E8 EA 39 FF FF", "state 0x2B calls the VM apply worker"),
    Anchor("state-2c-actor-resolve", 0x212C29, "E8 6E DB 04 00", "state 0x2C resolves the executed actor into rax"),
    Anchor("state-2c-effect-boundary", 0x212C2E, "66 44 01 70 0C", "first instruction after actor resolution"),
    Anchor("state-2c-to-2d", 0x212C3A, "C7 05 88 85 A5 00 2D 00 00 00", "state 0x2C advances to cleanup state 0x2D"),
    Anchor("state-2c-action-id", 0x212C9B, "44 0F B7 88 42 01 00 00", "state 0x2C still reads actor+0x142"),
    Anchor("state-2d-cleanup", 0x212C1F, "E8 2C A0 FF FF", "state 0x2D calls real-code cleanup"),
    Anchor("cleanup-target-count", 0x20CCCD, "8A 83 A9 01 00 00", "cleanup consumes actor+0x1A9"),
    Anchor("cleanup-target-list", 0x20CCDA, "48 8D B3 AA 01 00 00", "cleanup consumes actor+0x1AA"),
    Anchor("cleanup-action-id", 0x20CD17, "0F B7 93 42 01 00 00", "cleanup consumes actor+0x142"),
)


def rva_bytes(pe: pefile.PE, raw: bytes, rva: int, size: int) -> bytes:
    return raw[pe.get_offset_from_rva(rva):pe.get_offset_from_rva(rva) + size]


def render(exe: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    rows: list[str] = []
    ok = True
    for anchor in ANCHORS:
        expected = bytes.fromhex(anchor.expected)
        actual = rva_bytes(pe, raw, anchor.rva, len(expected))
        passed = actual == expected
        ok &= passed
        result = "PASS" if passed else "FAIL (`" + " ".join(f"{b:02X}" for b in actual) + "`)"
        rows.append(f"| `{anchor.name}` | `0x{anchor.rva:X}` | {result} | `{anchor.expected}` | {anchor.meaning} |")

    md = Cs(CS_ARCH_X86, CS_MODE_64)
    lines = [
        "# DCL Reaction effect-completion boundary analysis",
        "",
        "Generated by `tools/analyze_dcl_reaction_effect_boundary.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Output: `{output}`",
        "",
        "## Byte anchors",
        "",
        "| Name | RVA | Result | Expected bytes | Meaning |",
        "| --- | ---: | --- | --- | --- |",
        *rows,
        "",
        "## State `0x2B` VM execution",
        "",
        *dispatch.disassembly(md, pe, raw, 0x212D50, 0x28),
        "",
        "## State `0x2C` actor resolution and transition",
        "",
        *dispatch.disassembly(md, pe, raw, 0x212C29, 0x88),
        "",
        "## State `0x2D` cleanup inputs",
        "",
        *dispatch.disassembly(md, pe, raw, 0x20CCCD, 0x65),
        "",
        "## Interpretation",
        "",
        "- **Strong:** state `0x2B` owns the two VM execution workers. State `0x2C` is the next",
        "  real-code state and resolves the current executed actor before advancing to cleanup state `0x2D`.",
        "- **Strong:** RVA `0x212C2E` is the first instruction after that actor resolver. `rax` is the",
        "  executed actor, and its presentation id `+0x18C`, executable id `+0x142`, and target list",
        "  `+0x1A9/+0x1AA` have not yet been cleaned.",
        "- **Strong:** the following state-`0x2D` cleanup reads the same executable id and target list.",
        "- **Proven live boundary:** the hook at `0x212C2E` is later than accepted queue commit and VM",
        "  execution but earlier than cleanup. It fires per delivered transaction/strike: a Dual Wield",
        "  Counter produces two matching rows for one accepted pass-2 commit.",
        "- This boundary owns effect auditing and may host idempotent per-strike delivery. Once-per-",
        "  Reaction cadence must deduplicate against the earlier pass-2 commit rather than count these",
        "  rows directly.",
        "",
    ]
    return "\n".join(lines), ok


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-reaction-effect-boundary-analysis.md"
    report, ok = render(args.exe, output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all Reaction effect-boundary checks PASS" if ok else "one or more Reaction effect-boundary checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
