#!/usr/bin/env python3
"""Verify the current-build real-code Earplugs trigger family."""
from __future__ import annotations

import argparse
import csv
import hashlib
import time
from pathlib import Path

import pefile


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = Path(
    r"D:/SteamLibrary/steamapps/common/FINAL FANTASY TACTICS - The Ivalice Chronicles/FFT_enhanced.exe"
)
DEFAULT_CATALOG = ROOT / "work" / "wotl_ability_action_baseline.csv"

ANCHORS = (
    (0x30B774, "8A 05 0E 50 4A 00", "reads current formula id from byte RVA 0x7B0788"),
    (0x30B77A, "3C 2A 74 45", "routes formula 0x2A to the Earplugs branch"),
    (0x30B7C3, "48 8B 05 9E F7 55 01", "loads the current reaction unit"),
    (0x30B7CA, "F6 80 97 00 00 00 20", "tests unit+0x97 bit 0x20 for reaction id 448"),
    (0x30B7DA, "B9 C0 01 00 00", "stages exact reaction id 448"),
    (0x30B7E2, "66 89 48 10", "writes id 448 to result-record+0x10 = unit+0x1CE"),
    (0x30B7E6, "C6 40 02 0B", "selects native reaction delivery kind 0x0B"),
)


def rva_bytes(pe: pefile.PE, raw: bytes, rva: int, size: int) -> bytes:
    return raw[pe.get_offset_from_rva(rva) : pe.get_offset_from_rva(rva) + size]


def load_catalog(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def render(exe: Path, catalog_path: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    catalog = load_catalog(catalog_path)
    checks = []
    for rva, expected_hex, meaning in ANCHORS:
        expected = bytes.fromhex(expected_hex)
        checks.append((rva, meaning, rva_bytes(pe, raw, rva, len(expected)) == expected))

    families = {
        formula: [row for row in catalog if row.get("formula_hex") == formula]
        for formula in ("0x1C", "0x1D", "0x2A")
    }
    speech_ids = [int(row["id_dec"]) for row in families["0x2A"]]
    catalog_ok = speech_ids == list(range(116, 126))
    ok = all(passed for _, _, passed in checks) and catalog_ok

    lines = [
        "# DCL native Earplugs real-code scope analysis",
        "",
        "Generated by `tools/analyze_dcl_earplugs.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Ability catalog: `{catalog_path}`",
        f"- Output: `{output}`",
        "",
        "## Anchor verification",
        "",
        "| RVA | Result | Meaning |",
        "| ---: | --- | --- |",
    ]
    for rva, meaning, passed in checks:
        lines.append(f"| `0x{rva:X}` | {'PASS' if passed else 'FAIL'} | {meaning} |")

    lines.extend(
        [
            "",
            "## Formula families",
            "",
            "| Formula | Catalog abilities | Current real-code Earplugs branch |",
            "| --- | --- | --- |",
        ]
    )
    for formula, rows in families.items():
        abilities = ", ".join(f"{row['id_dec']}:{row.get('name_ivc') or row.get('name_wotl')}" for row in rows)
        lines.append(f"| `{formula}` | {abilities} | {'yes' if formula == '0x2A' else 'not this branch'} |")

    lines.extend(
        [
            "",
            "## Native contract and boundary",
            "",
            "The hookable real-code Earplugs path is keyed by current formula id `0x2A`. In the ability",
            "catalog that family is exactly actions `116..125`, the Speechcraft/morale set. If the",
            "reactor owns reaction bit `unit+0x97 & 0x20`, the branch stages exact reaction id `448` at",
            "`unit+0x1CE` with delivery kind `0x0B`.",
            "",
            "Bardsong `86..92` uses formula `0x1C` and Dance `93..99` uses formula `0x1D`; neither is",
            "routed through this real-code branch. This does not prove that the VM lacks a separate",
            "Earplugs check for those families, but it proves that the visible real-code trigger cannot",
            "by itself implement the final DCL scope of performance, speech, and morale effects.",
            "",
            "A final implementation needs an authored action-family membership map and either native/VM",
            "proof for `0x1C/0x1D` or a DCL effect-suppression producer. Exact action ids are preferable",
            "to a broad formula-only immunity because the design explicitly forbids broad status immunity.",
            "",
        ]
    )
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-earplugs-analysis.md"
    report, ok = render(args.exe, args.catalog, output)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all Earplugs checks PASS" if ok else "one or more Earplugs checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
