#!/usr/bin/env python3
"""Analyze [ACTOR-PROBE] logs and rederive attacker candidates from CT.

The code mod logs actor probes as:

    [ACTOR-PROBE tgt=0x1E off=0x40-0x52] 01@0A4600... 80@100C00...

Within that configured window, +0x40 is Speed and +0x41 is CT. This tool is intentionally
offline-only: it lets us validate the CT attacker-resolution model against captured logs without
touching the live runtime.
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


DEFAULT_LOG = Path(
    r"D:\SteamLibrary\steamapps\common\FINAL FANTASY TACTICS - The Ivalice Chronicles\battleprobe_log.txt"
)
DEFAULT_OUT = Path(__file__).resolve().parents[1] / "work/actor_probe_ct_analysis.md"
ACTOR_PROBE_RE = re.compile(
    r"\[ACTOR-PROBE\s+tgt=(0x[0-9A-Fa-f]+)\s+off=(0x[0-9A-Fa-f]+)-(0x[0-9A-Fa-f]+)\]\s*(?P<body>.*)"
)
SAMPLE_RE = re.compile(r"\b(?P<id>[0-9A-Fa-f]{2})@(?P<hex>[0-9A-Fa-f]+)\b")


@dataclass(frozen=True)
class ActorProbeSample:
    unit_id: int
    raw: bytes
    speed: int | None
    ct: int | None


@dataclass(frozen=True)
class ActorProbeEvent:
    line_no: int
    target_id: int
    start: int
    end: int
    samples: tuple[ActorProbeSample, ...]


@dataclass(frozen=True)
class CtCandidate:
    unit_id: int
    speed: int | None
    ct: int
    previous_ct: int | None
    ct_drop: int


@dataclass(frozen=True)
class CtResolution:
    event: ActorProbeEvent
    attacker_id: int | None
    source: str
    candidates: tuple[CtCandidate, ...]


def parse_actor_probe_line(line: str, line_no: int = 0) -> ActorProbeEvent | None:
    match = ACTOR_PROBE_RE.search(line)
    if not match:
        return None

    target_id = int(match.group(1), 16)
    start = int(match.group(2), 16)
    end = int(match.group(3), 16)
    samples: list[ActorProbeSample] = []
    for sample_match in SAMPLE_RE.finditer(match.group("body")):
        unit_id = int(sample_match.group("id"), 16)
        try:
            raw = bytes.fromhex(sample_match.group("hex"))
        except ValueError:
            continue
        speed = read_window_byte(raw, start, 0x40)
        ct = read_window_byte(raw, start, 0x41)
        samples.append(ActorProbeSample(unit_id, raw, speed, ct))

    return ActorProbeEvent(line_no, target_id, start, end, tuple(samples))


def parse_actor_probes(lines: Iterable[str]) -> list[ActorProbeEvent]:
    events: list[ActorProbeEvent] = []
    for line_no, line in enumerate(lines, start=1):
        event = parse_actor_probe_line(line, line_no)
        if event is not None:
            events.append(event)
    return events


def resolve_ct_attackers(events: Iterable[ActorProbeEvent]) -> list[CtResolution]:
    previous_ct_by_unit: dict[int, int] = {}
    resolutions: list[CtResolution] = []

    for event in events:
        candidates = build_candidates(event, previous_ct_by_unit)
        attacker_id: int | None = None
        source = "none"
        if candidates:
            drop_candidates = [candidate for candidate in candidates if candidate.ct_drop > 0]
            if drop_candidates:
                best = sorted(
                    drop_candidates,
                    key=lambda candidate: (-candidate.ct_drop, candidate.ct, candidate.unit_id),
                )[0]
                attacker_id = best.unit_id
                source = "ct-drop"
            else:
                best = sorted(candidates, key=lambda candidate: (candidate.ct, candidate.unit_id))[0]
                attacker_id = best.unit_id
                source = "ct-lowest"

        resolutions.append(CtResolution(event, attacker_id, source, tuple(candidates)))

        for sample in event.samples:
            if sample.ct is not None:
                previous_ct_by_unit[sample.unit_id] = sample.ct

    return resolutions


def build_candidates(event: ActorProbeEvent, previous_ct_by_unit: dict[int, int]) -> list[CtCandidate]:
    candidates: list[CtCandidate] = []
    for sample in event.samples:
        if sample.unit_id == event.target_id:
            continue
        if sample.ct is None:
            continue
        previous_ct = previous_ct_by_unit.get(sample.unit_id)
        ct_drop = max(0, previous_ct - sample.ct) if previous_ct is not None else 0
        candidates.append(CtCandidate(sample.unit_id, sample.speed, sample.ct, previous_ct, ct_drop))
    return candidates


def render_markdown(resolutions: list[CtResolution]) -> str:
    lines = [
        "# Actor Probe CT Analysis",
        "",
        "Generated by `tools/analyze_actor_probe_ct.py`. Do not hand-edit.",
        "",
        f"Actor probe events: {len(resolutions)}",
        "",
    ]
    if not resolutions:
        lines.extend(
            [
                "No `[ACTOR-PROBE]` events were found.",
                "",
            ]
        )
        return "\n".join(lines)

    resolved = sum(1 for resolution in resolutions if resolution.attacker_id is not None)
    by_source: dict[str, int] = {}
    for resolution in resolutions:
        by_source[resolution.source] = by_source.get(resolution.source, 0) + 1
    source_text = ", ".join(f"`{source}`={count}" for source, count in sorted(by_source.items()))
    lines.extend(
        [
            f"Resolved events: {resolved}/{len(resolutions)}",
            f"Sources: {source_text}",
            "",
            "| # | Line | Target | Resolved Attacker | Source | Top candidates |",
            "| --- | ---: | --- | --- | --- | --- |",
        ]
    )

    for index, resolution in enumerate(resolutions, start=1):
        attacker = format_id(resolution.attacker_id)
        lines.append(
            "| "
            + " | ".join(
                [
                    str(index),
                    str(resolution.event.line_no),
                    format_id(resolution.event.target_id),
                    attacker,
                    f"`{resolution.source}`",
                    format_candidates(resolution.candidates),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "Rule: exclude the target, prefer the largest recent CT drop, otherwise choose the lowest",
            "absolute CT. This mirrors the live Test 4 finding that `+0x41` is Charge Time.",
            "",
        ]
    )
    return "\n".join(lines)


def read_window_byte(raw: bytes, start: int, absolute_offset: int) -> int | None:
    index = absolute_offset - start
    if index < 0 or index >= len(raw):
        return None
    return raw[index]


def format_candidates(candidates: tuple[CtCandidate, ...]) -> str:
    if not candidates:
        return "`none`"
    ordered = sorted(candidates, key=lambda candidate: (-candidate.ct_drop, candidate.ct, candidate.unit_id))
    parts: list[str] = []
    for candidate in ordered[:5]:
        previous = "-" if candidate.previous_ct is None else str(candidate.previous_ct)
        speed = "-" if candidate.speed is None else str(candidate.speed)
        parts.append(
            f"{format_id(candidate.unit_id)}(ct={candidate.ct},prev={previous},drop={candidate.ct_drop},spd={speed})"
        )
    if len(ordered) > 5:
        parts.append(f"+{len(ordered) - 5} more")
    return "`" + " ".join(parts) + "`"


def format_id(value: int | None) -> str:
    return "none" if value is None else f"0x{value:02X}"


def main() -> int:
    parser = argparse.ArgumentParser(description="Analyze [ACTOR-PROBE] CT attacker evidence.")
    parser.add_argument("log", nargs="?", type=Path, default=DEFAULT_LOG, help=f"Log path. Default: {DEFAULT_LOG}")
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUT, help=f"Markdown output. Default: {DEFAULT_OUT}")
    parser.add_argument("--check", action="store_true", help="Fail if no actor probes can be resolved.")
    args = parser.parse_args()

    if not args.log.exists():
        print(f"missing log: {args.log}", file=sys.stderr)
        return 1

    events = parse_actor_probes(args.log.read_text(encoding="utf-8", errors="replace").splitlines())
    resolutions = resolve_ct_attackers(events)
    report = render_markdown(resolutions)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(f"wrote {args.output}")

    if args.check and not any(resolution.attacker_id is not None for resolution in resolutions):
        print("no CT attacker candidates resolved", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
