#!/usr/bin/env python3
"""Verify the current-build reaction action-queue commit candidate.

The chance callbacks are unsafe for cadence consumption because forecast and AI evaluation can run
them. This analysis follows the native reaction selector into the battle-state function that creates
an actor for an accepted reaction and mirrors the exact Reaction id into that actor.
"""
from __future__ import annotations

import argparse
import hashlib
import time
from dataclasses import dataclass
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_64, Cs

import analyze_dcl_reaction_dispatch as dispatch


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = dispatch.DEFAULT_EXE
SELECTOR_ENTRY_RVA = 0x282E38
SELECTOR_RETURN_RVA = 0x2831BC
QUEUE_ENTRY_RVA = 0x206344
QUEUE_CALL_RVA = 0x2063AD
QUEUE_ACCEPT_RVA = 0x2063BD
QUEUE_COMMIT_CANDIDATE_RVA = 0x206421
STATE_CALLER_RVA = 0x2121F7


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected: str
    meaning: str


ANCHORS = (
    Anchor("reaction-selector-entry", SELECTOR_ENTRY_RVA, "48 8B C4 48 89 58 08 48 89 68 10", "selector function entry"),
    Anchor("selector-stage-exact-id", 0x282F1E, "66 89 77 02", "writes exact Reaction id to the candidate order record"),
    Anchor("selector-output-id-read", 0x2831C5, "0F B7 35 24 7E 5E 01", "loads the accepted exact Reaction id"),
    Anchor("selector-output-id-write", 0x2831CC, "66 41 89 36", "writes the accepted id through the caller output pointer"),
    Anchor("selector-output-unit-index", 0x2831D0, "8B C5", "returns the accepted reacting unit index in eax"),
    Anchor("reaction-queue-selector-call", QUEUE_CALL_RVA, "E8 86 CA 07 00", "calls the selector with a stack-local id output"),
    Anchor("reaction-queue-accepted-branch", QUEUE_ACCEPT_RVA, "0F B7 C8 C7 05 02 4E A6 00 29 00 00 00", "nonnegative selector result enters reaction actor construction and state 0x29"),
    Anchor("reaction-queue-id-local-read", 0x2063FA, "0F B7 45 D2", "loads the exact selected Reaction id from the output local"),
    Anchor("reaction-actor-id-18c", 0x206414, "89 83 8C 01 00 00", "mirrors the exact Reaction id to actor+0x18C"),
    Anchor("reaction-actor-id-142", 0x20641A, "66 89 83 42 01 00 00", "mirrors the exact Reaction id to actor+0x142"),
    Anchor("reaction-actor-commit-candidate", QUEUE_COMMIT_CANDIDATE_RVA, "40 88 B3 D3 01 00 00", "first instruction after actor creation and both exact-id stores"),
    Anchor("reaction-queue-state-caller", STATE_CALLER_RVA, "E8 48 41 FF FF", "battle-state dispatcher calls the reaction queue function"),
)


def parse_hex(value: str) -> bytes:
    return bytes.fromhex(value)


def hex_bytes(value: bytes) -> str:
    return " ".join(f"{byte:02X}" for byte in value)


def render_report(exe: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    image_base = pe.OPTIONAL_HEADER.ImageBase
    md = Cs(CS_ARCH_X86, CS_MODE_64)

    rows: list[str] = []
    anchors_ok = True
    for anchor in ANCHORS:
        expected = parse_hex(anchor.expected)
        actual = dispatch.rva_bytes(pe, raw, anchor.rva, len(expected))
        ok = actual == expected
        anchors_ok &= ok
        result = "PASS" if ok else f"FAIL (`{hex_bytes(actual)}`)"
        rows.append(
            f"| `{anchor.name}` | `0x{anchor.rva:X}` | {result} | `{anchor.expected}` | {anchor.meaning} |"
        )

    selector_callers = dispatch.direct_callers(pe, raw, SELECTOR_ENTRY_RVA)
    queue_callers = dispatch.direct_callers(pe, raw, QUEUE_ENTRY_RVA)
    call_graph_ok = selector_callers == [QUEUE_CALL_RVA] and queue_callers == [STATE_CALLER_RVA]

    selector_body = dispatch.rva_bytes(
        pe, raw, SELECTOR_ENTRY_RVA, SELECTOR_RETURN_RVA - SELECTOR_ENTRY_RVA + 1
    )
    instructions = list(md.disasm(selector_body, image_base + SELECTOR_ENTRY_RVA))
    contiguous = bool(instructions) and instructions[-1].address + instructions[-1].size == image_base + SELECTOR_RETURN_RVA + 1
    return_rvas = [
        instruction.address - image_base for instruction in instructions if instruction.mnemonic.startswith("ret")
    ]
    selector_boundary_ok = contiguous and return_rvas == [SELECTOR_RETURN_RVA]

    lines = [
        "# DCL reaction action-queue commit analysis",
        "",
        "Generated by `tools/analyze_dcl_reaction_commit.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- PE image base: `0x{image_base:X}`",
        f"- Output: `{output}`",
        "",
        "## Byte anchors",
        "",
        "| Name | RVA | Result | Expected bytes | Meaning |",
        "| --- | ---: | --- | --- | --- |",
        *rows,
        "",
        "## Call graph",
        "",
        f"- Selector `0x{SELECTOR_ENTRY_RVA:X}` direct callers: " +
        (", ".join(f"`0x{rva:X}`" for rva in selector_callers) or "none") + ".",
        f"- Queue function `0x{QUEUE_ENTRY_RVA:X}` direct callers: " +
        (", ".join(f"`0x{rva:X}`" for rva in queue_callers) or "none") + ".",
        f"- Expected one-edge chain `0x{STATE_CALLER_RVA:X} -> 0x{QUEUE_ENTRY_RVA:X} -> 0x{SELECTOR_ENTRY_RVA:X}`: **{'PASS' if call_graph_ok else 'FAIL'}**.",
        "",
        "## Selector boundary",
        "",
        f"- Linear decode reaches `0x{SELECTOR_RETURN_RVA:X}` without a gap: **{'PASS' if contiguous else 'FAIL'}**.",
        f"- Return instructions: {', '.join(f'`0x{rva:X}`' for rva in return_rvas) or 'none'}.",
        f"- Sole selector return: **{'PASS' if selector_boundary_ok else 'FAIL'}**.",
        "",
        "## Accepted-reaction path",
        "",
        *dispatch.disassembly(md, pe, raw, 0x2063A9, 0x80),
        "",
        "## Selector accepted-output path",
        "",
        *dispatch.disassembly(md, pe, raw, 0x2831BD, 0x20),
        "",
        "## Static interpretation",
        "",
        "- **Strong:** the selector has one direct caller. Its accepted path writes the exact Reaction",
        "  id through the caller's output pointer and returns the selected reacting unit index in `eax`.",
        "- **Strong:** the caller rejects `eax == -1`. A nonnegative result creates an actor for that",
        "  unit, changes the battle state to `0x29`, and mirrors the exact Reaction id to both",
        "  `actor+0x18C` and `actor+0x142`.",
        f"- **Strong candidate:** `0x{QUEUE_COMMIT_CANDIDATE_RVA:X}` is the first instruction after actor",
        "  creation and both exact-id stores. At that point `rbx` is the reaction actor and `ax` /",
        "  `[rbp-0x2E]` is the exact Reaction id; `actor+8` carries the selected unit index.",
        "- This boundary is downstream of chance evaluation and upstream of reaction action execution.",
        "  It is therefore the accepted-Reaction cardinality authority and the correct cadence key.",
        "  It is not an executable-action or final-target rewrite site.",
        "- Special carriers `434/435/436/437/440/441/442` expose their complete order at `0x2831BD`",
        "  before helper call `0x2831C0`. Generic carriers such as `443` skip both and join common",
        "  finalization at `0x2831CC`. The post-selector boundary at `0x2063BD` remains useful for",
        "  observation, while this commit remains the deduplication authority",
        "  for once-per-action/own-cycle state.",
        "",
    ]
    return "\n".join(lines), anchors_ok and call_graph_ok and selector_boundary_ok


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-reaction-commit-analysis.md"
    report, ok = render_report(args.exe, output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all reaction-commit anchors and scope checks PASS" if ok else "one or more reaction-commit checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
