#!/usr/bin/env python3
"""Map native status-only roll gates and the safe retained-carrier boundary."""
from __future__ import annotations

import argparse
import csv
import hashlib
import struct
import time
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

import pefile

import analyze_dcl_status_transactions as status_tx


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = status_tx.DEFAULT_EXE
DEFAULT_CATALOG = status_tx.DEFAULT_CATALOG
FORMULA_A = 0x0A
FORMULA_B = 0x0B
FORMULA_IAIDO = 0x22
FORMULA_A_HANDLER = 0x3074E8
FORMULA_B_HANDLER = 0x307508
FORMULA_IAIDO_HANDLER = 0x307DE4
STATUS_RESULT_BUILDER = 0x306558
STATUS_FINALIZER = 0x306988


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected_hex: str
    meaning: str

    @property
    def expected(self) -> bytes:
        return bytes.fromhex(self.expected_hex)


ANCHORS = (
    Anchor(
        "formula-0a-conditional-finalizer",
        FORMULA_A_HANDLER,
        "48 83 EC 28 E8 7B F8 FF FF 85 C0 75 0E E8 2A FB FF FF 85 C0 75 05 E8 85 F4 FF FF 48 83 C4 28 C3",
        "formula 0x0A skips the status finalizer when either native prerequisite/roll helper reports failure",
    ),
    Anchor(
        "formula-0b-conditional-finalizer",
        0x30754A,
        "48 8B 05 1F 3A 56 01 80 38 00 74 05 E8 2D F4 FF FF 48 83 C4 28 C3",
        "formula 0x0B calls the status finalizer only when the native result flag is nonzero",
    ),
    Anchor(
        "formula-22-builder-finalizer",
        FORMULA_IAIDO_HANDLER,
        "48 83 EC 28 E8 6B E7 FF FF 48 83 C4 28 E9 92 EB FF FF",
        "formula 0x22 unconditionally delegates to the shared result builder then the status finalizer",
    ),
    Anchor(
        "shared-builder-native-roll",
        0x306594,
        "0F B6 15 11 A2 4A 00 8D 4B 5C E8 C5 28 F7 FF 85 C0 74 07",
        "the shared builder loads the native status chance and rolls before writing its success result",
    ),
)


def rva_bytes(pe: pefile.PE, raw: bytes, rva: int, size: int) -> bytes:
    return status_tx.rva_bytes(pe, raw, rva, size)


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def render(exe: Path, catalog_path: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    targets = status_tx.dispatch_targets(pe, raw)
    target_ok = (
        targets[FORMULA_A] == FORMULA_A_HANDLER
        and targets[FORMULA_B] == FORMULA_B_HANDLER
        and targets[FORMULA_IAIDO] == FORMULA_IAIDO_HANDLER
    )

    anchor_results = []
    for anchor in ANCHORS:
        actual = rva_bytes(pe, raw, anchor.rva, len(anchor.expected))
        anchor_results.append((anchor, actual == anchor.expected, actual))

    builder_callers = status_tx.direct_callers(pe, STATUS_RESULT_BUILDER)
    expected_builder_callers = [0x307D50, 0x307D84, 0x307DE8, 0x307DFC]
    builder_scope_ok = builder_callers == expected_builder_callers

    finalizer_formulas = status_tx.formulas_calling(pe, raw, STATUS_FINALIZER)
    # 0x0A/0x0B call the thunk; 0x22 tail-jumps to it, which is guarded separately by the
    # formula-22-builder-finalizer byte anchor rather than appearing in the E8-only caller scan.
    finalizer_ok = all(formula in finalizer_formulas for formula in (FORMULA_A, FORMULA_B))

    rows = load_rows(catalog_path)
    family_rows = [row for row in rows if row["formula_hex"].upper() in {"0X0A", "0X0B", "0X22"}]
    counts = Counter(row["formula_hex"].upper() for row in family_rows)
    mode_counts = Counter((row["formula_hex"].upper(), row["inflict_status_mode"]) for row in family_rows)
    iaido_rows = [row for row in family_rows if row["formula_hex"].upper() == "0X22"]
    catalog_ok = (
        counts == Counter({"0X0A": 38, "0X0B": 15, "0X22": 2})
        and mode_counts[("0X0A", "AllOrNothing")] == 35
        and mode_counts[("0X0A", "Cancel")] == 3
        and mode_counts[("0X0B", "AllOrNothing")] == 13
        and mode_counts[("0X0B", "Cancel")] == 2
        and [(int(row["id_dec"]), row["inflict_statuses"]) for row in iaido_rows]
        == [(81, "Protect|Shell"), (84, "Regen|Haste")]
    )

    lines = [
        "# DCL status-roll carrier analysis",
        "",
        "Generated by `tools/analyze_dcl_status_roll_carriers.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Ability catalog: `{catalog_path}`",
        f"- Output: `{output}`",
        "",
        "## Current-build anchors",
        "",
        "| Anchor | RVA | Result | Meaning |",
        "| --- | ---: | --- | --- |",
    ]
    for anchor, passed, actual in anchor_results:
        result = "PASS" if passed else f"FAIL (`{actual.hex(' ').upper()}`)"
        lines.append(f"| `{anchor.name}` | `0x{anchor.rva:X}` | {result} | {anchor.meaning} |")

    lines.extend([
        "",
        "## Dispatch and call-scope checks",
        "",
        f"- Formula targets: `0x0A -> 0x{targets[FORMULA_A]:X}`, "
        f"`0x0B -> 0x{targets[FORMULA_B]:X}`, `0x22 -> 0x{targets[FORMULA_IAIDO]:X}`: "
        f"**{'PASS' if target_ok else 'FAIL'}**.",
        "- Shared status-result builder direct callers: "
        + ", ".join(f"`0x{caller:X}`" for caller in builder_callers)
        + f" (**{'PASS' if builder_scope_ok else 'FAIL'}**).",
        "- Formula `0x0A/0x0B` call and formula `0x22` tail-jumps to the common packet finalizer: "
        f"**{'PASS' if finalizer_ok else 'FAIL'}**.",
        "",
        "The legacy `StatusChanceControl` site inside the shared result builder is not a universal",
        "formula-`0x0A/0x0B` status-roll input. Its exact direct-caller scope excludes both handlers.",
        "A final DCL contest cannot use that control as a global shortcut.",
        "",
        "## Catalog inventory",
        "",
        "| Formula | All-or-nothing add | Cancel/remove | Total |",
        "| --- | ---: | ---: | ---: |",
        f"| `0x0A` | {mode_counts[(('0X0A'), 'AllOrNothing')]} | {mode_counts[(('0X0A'), 'Cancel')]} | {counts['0X0A']} |",
        f"| `0x0B` | {mode_counts[(('0X0B'), 'AllOrNothing')]} | {mode_counts[(('0X0B'), 'Cancel')]} | {counts['0X0B']} |",
        f"| `0x22` | {mode_counts[(('0X22'), 'AllOrNothing')]} | {mode_counts[(('0X22'), 'Cancel')]} | {counts['0X22']} |",
        "",
        f"Catalog counts and exact Iaido payloads: **{'PASS' if catalog_ok else 'FAIL'}**.",
        "",
        "Formula `0x0A` ids:",
        "",
        "`" + ", ".join(row["id_dec"] for row in family_rows if row["formula_hex"].upper() == "0X0A") + "`.",
        "",
        "Formula `0x0B` ids:",
        "",
        "`" + ", ".join(row["id_dec"] for row in family_rows if row["formula_hex"].upper() == "0X0B") + "`.",
        "",
        "## Integration boundary",
        "",
        "- Formula `0x22` is the bounded retained-carrier subset. Its two catalog actions have fixed",
        "  native status bundles and an unconditional builder/finalizer wrapper. The runtime keeps",
        "  those bundles only to preserve result production and replaces every inherited packet bit",
        "  at pre-clamp.",
        "- Formula `0x0A` can skip the finalizer at either of two native gates. Formula `0x0B` skips",
        "  it when its native result flag is zero. A rule evaluated only at pre-clamp therefore cannot",
        "  turn a native miss into a DCL success: that action never reaches packet replacement.",
        "- Forcing a shared chance to 100 globally is invalid. It would affect unauthored actions and",
        "  still would not provide execution-only 3d6 ownership, forecast probability, or AI scoring.",
        "- The post-calc producer is exact-action and per-target. It accepts only the proven outer-sweep",
        "  return plus execution state, stages the complete managed packet, and caches that exact 3d6",
        "  decision for pre-clamp reuse. Forecast/AI remain read-only and cannot consume the decision.",
        "",
        "The execution output-production gap is closed offline. Live carrier validation and authored",
        "forecast/AI probability remain separate integration gates.",
        "",
    ])
    ok = (
        target_ok
        and all(passed for _, passed, _ in anchor_results)
        and builder_scope_ok
        and finalizer_ok
        and catalog_ok
    )
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()
    if not args.exe.exists():
        raise SystemExit(f"executable not found: {args.exe}")
    if not args.catalog.exists():
        raise SystemExit(f"ability catalog not found: {args.catalog}")
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-status-roll-carrier-analysis.md"
    report, ok = render(args.exe, args.catalog, output)
    if not args.check_only:
        output.write_text(report, encoding="utf-8", newline="\n")
        print(f"wrote {output}")
    print("all status-roll carrier checks PASS" if ok else "one or more status-roll carrier checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
