#!/usr/bin/env python3
"""Map the three current-build reaction-queue passes and their commit boundaries."""
from __future__ import annotations

import argparse
import hashlib
import time
from dataclasses import dataclass
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_64, Cs

import analyze_dcl_reaction_dispatch as dispatch


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = dispatch.DEFAULT_EXE
QUEUE_ENTRY_RVA = 0x206344
QUEUE_RETURN_RVA = 0x206754
PHASE0_SELECTOR_RVA = 0x282BDC
PHASE1_CLASSIFIER_RVA = 0x28198C
PHASE2_SELECTOR_RVA = 0x282E38


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected: str
    meaning: str


ANCHORS = (
    Anchor("phase-counter-load", 0x206376, "8B 0D 00 85 DC 02", "loads the 0..2 queue-pass counter"),
    Anchor("phase2-selector-call", 0x2063AD, "E8 86 CA 07 00", "pass 2 calls the real-code exact-id selector"),
    Anchor("phase2-id-18c", 0x206414, "89 83 8C 01 00 00", "pass 2 stores the selected id at actor+0x18C"),
    Anchor("phase2-id-142", 0x20641A, "66 89 83 42 01 00 00", "pass 2 stores the selected id at actor+0x142"),
    Anchor("phase2-commit", 0x206421, "40 88 B3 D3 01 00 00", "first instruction after the pass-2 id stores"),
    Anchor("phase1-classifier-call", 0x2064A1, "E8 E6 B4 07 00", "pass 1 calls the VM-owned classifier"),
    Anchor("phase0-selector-call", 0x206615, "E8 C2 C5 07 00", "pass 0 calls the VM-owned selector"),
    Anchor("phase0-id-18c", 0x2066A1, "89 8B 8C 01 00 00", "pass 0 stores the selected id at actor+0x18C"),
    Anchor("phase0-id-142", 0x2066A7, "66 89 8B 42 01 00 00", "pass 0 stores the selected id at actor+0x142"),
    Anchor("phase0-commit", 0x2066AE, "40 88 B3 D3 01 00 00", "first instruction after the pass-0 id stores"),
    Anchor("phase1-id-source", 0x20672F, "0F BF 8F 7A 01 00 00", "pass 1 reads the reused actor order payload at +0x17A"),
    Anchor("phase1-id-18c", 0x206736, "89 8F 8C 01 00 00", "pass 1 mirrors the payload at actor+0x18C"),
    Anchor("phase1-id-142", 0x20673C, "66 89 8F 42 01 00 00", "pass 1 mirrors the payload at actor+0x142"),
    Anchor("phase1-commit", 0x206743, "40 88 B7 D3 01 00 00", "first instruction after the pass-1 id stores"),
    Anchor("phase2-unit-reaction-id", 0x282E9A, "48 0F BF B3 CE 01 00 00", "selector reads signed word unit+0x1CE"),
    Anchor("phase2-consume-reaction-id", 0x282F29, "66 44 89 BB CE 01 00 00", "selector clears unit+0x1CE after staging"),
    Anchor("source-exclusion-write", 0x30C72D, "89 05 C1 E8 55 01", "counter path writes the source/excluded unit index global"),
)


SPECIAL_IDS = (
    (434, "Bonecrusher", "typed order: type 1, payload 0, source-target validation"),
    (435, "Magick Counter", "typed order: type 0x0B, payload reactor unit+0x1E6"),
    (436, "Counter Tackle", "typed order: type 0x0B, payload 0x93"),
    (437, "Nature's Wrath", "typed order: type 0x11, tile-derived payload"),
    (440, "Reflect (reserved)", "special real-code branch"),
    (441, "Auto-Potion", "special item-selection branch"),
    (442, "Counter", "typed order: type 1, payload 0, source-target validation"),
)


def parse_hex(value: str) -> bytes:
    return bytes.fromhex(value)


def hex_bytes(value: bytes) -> str:
    return " ".join(f"{byte:02X}" for byte in value)


def render_report(exe: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    image_base = pe.OPTIONAL_HEADER.ImageBase
    md = Cs(CS_ARCH_X86, CS_MODE_64)

    rows: list[str] = []
    anchors_ok = True
    for anchor in ANCHORS:
        expected = parse_hex(anchor.expected)
        actual = dispatch.rva_bytes(pe, raw, anchor.rva, len(expected))
        ok = actual == expected
        anchors_ok &= ok
        result = "PASS" if ok else f"FAIL (`{hex_bytes(actual)}`)"
        rows.append(
            f"| `{anchor.name}` | `0x{anchor.rva:X}` | {result} | `{anchor.expected}` | {anchor.meaning} |"
        )

    queue_callers = dispatch.direct_callers(pe, raw, QUEUE_ENTRY_RVA)
    selector_callers = {
        "pass 0": dispatch.direct_callers(pe, raw, PHASE0_SELECTOR_RVA),
        "pass 1": dispatch.direct_callers(pe, raw, PHASE1_CLASSIFIER_RVA),
        "pass 2": dispatch.direct_callers(pe, raw, PHASE2_SELECTOR_RVA),
    }
    callers_ok = queue_callers == [0x2121F7] and all(
        callers == [expected]
        for callers, expected in zip(selector_callers.values(), (0x206615, 0x2064A1, 0x2063AD))
    )

    lines = [
        "# DCL reaction queue-pass analysis",
        "",
        "Generated by `tools/analyze_dcl_reaction_queue.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Output: `{output}`",
        "",
        "## Byte anchors",
        "",
        "| Name | RVA | Result | Expected bytes | Meaning |",
        "| --- | ---: | --- | --- | --- |",
        *rows,
        "",
        "## Call graph",
        "",
        f"- Queue callers: {', '.join(f'`0x{rva:X}`' for rva in queue_callers) or 'none'}.",
    ]
    for name, callers in selector_callers.items():
        lines.append(f"- {name} helper callers: {', '.join(f'`0x{rva:X}`' for rva in callers) or 'none'}.")
    lines.extend([
        f"- Expected single-caller graph: **{'PASS' if callers_ok else 'FAIL'}**.",
        "",
        "## Three queue passes",
        "",
        "| Pass | Selection surface | Actor | Exact action-id source | Post-store boundary | Static scope |",
        "| ---: | --- | --- | --- | ---: | --- |",
        "| `0` | VM-owned selector `0x282BDC` | newly resolved actor in `rbx` | selector out-param `[rbp-0x2E]` | `0x2066AE` | separate accepted-reaction family |",
        "| `1` | VM-owned classifier `0x28198C` | reuses incoming actor in `rdi` | existing order payload `actor+0x17A` | `0x206743` | separate reuse/resume family |",
        "| `2` | real-code selector `0x282E38` | newly resolved actor in `rbx` | selected unit's `unit+0x1CE` | `0x206421` | exact Reaction-id family |",
        "",
        "The queue iterates its pass counter from 0 through 2. A successful pass changes battle state",
        "to `0x29`; all three accepted paths mirror an action id to `actor+0x18C` and `actor+0x142`.",
        "Therefore a probe at only `0x206421` observes pass 2, not the complete queue.",
        "",
        "## Pass-2 special deliveries",
        "",
        "The real-code selector has explicit branches for these exact ids:",
        "",
        "| Id | Native name | Selector behavior |",
        "| ---: | --- | --- |",
    ])
    for ability_id, name, behavior in SPECIAL_IDS:
        lines.append(f"| `{ability_id}` | {name} | {behavior} |")

    lines.extend([
        "",
        "Pass 2 walks the 21-unit battle array with stride `0x200`, reads the candidate exact id from",
        "`unit+0x1CE`, stages an order at `unit+0x1A0`, then clears `unit+0x1CE`. The selector excludes",
        "the unit index held in global RVA `0x186AFF4`; the counter path writes that global from its",
        "current result context. The special branches show that writing an id alone is not yet proven",
        "sufficient for every carrier: delivery helpers also consume current action globals/unit fields.",
        "The typed-order helper at `0x283280` reads the source-index global and copies that unit's tile",
        "coordinates into the reactor's order record. Counter `442` therefore supplies the native basic",
        "attack-against-source carrier shape, subject to a live source-lifetime gate.",
        "",
        "## Queue window",
        "",
        *dispatch.disassembly(md, pe, raw, 0x20638C, 0x3C8),
        "",
        "## Pass-2 selector window",
        "",
        *dispatch.disassembly(md, pe, raw, 0x282E38, 0x385),
        "",
        "## Static interpretation",
        "",
        "- **Strong:** there are three structurally distinct accepted queue paths, each with its own",
        "  first instruction after the exact action-id mirrors.",
        "- **Strong:** pass 2 is the native surface that consumes an exact Reaction id from a unit and",
        "  contains hard-coded delivery behavior for the counter-style carriers relevant to the DCL.",
        "- **Proven live:** the bounded pass-2 producer can stage an empty `unit+0x1CE` slot and the",
        "  pass-2 commit identifies accepted Reaction cardinality; pass 1 remains generic queue noise.",
        "- **Proven static:** the accepted selector output leaves the carrier-specific 20-byte order at",
        "  `unit+0x1A0`. RVA `0x2063BD` exposes it before actor construction and is the next observe-only",
        "  correlation point for executable type/payload and final target coordinates.",
        "",
    ])
    return "\n".join(lines), anchors_ok and callers_ok


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-reaction-queue-analysis.md"
    report, ok = render_report(args.exe, output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all reaction-queue anchors and call-graph checks PASS" if ok else "one or more reaction-queue checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
