#!/usr/bin/env python3
"""Verify the current-build native Malboro Spores transformation transaction."""
from __future__ import annotations

import argparse
import csv
import hashlib
import struct
import time
from dataclasses import dataclass
from pathlib import Path

import pefile

import analyze_dcl_reaction_dispatch as dispatch


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = dispatch.DEFAULT_EXE
DEFAULT_CATALOG = ROOT / "work" / "wotl_ability_action_baseline.csv"
DISPATCH_TABLE_RVA = 0x682BC8
FORMULA_ID = 0x58
FORMULA_HANDLER_RVA = 0x3090F0


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected: str
    meaning: str


ANCHORS = (
    Anchor(
        "transformation-eligibility",
        0x30913C,
        "48 8B 15 25 1E 56 01 F6 42 05 04 75 2B 44 38 82 B4 01 00 00 75 22 8A 02 45 8D 48 02 2C 80 41 3A C1 77 15 8A 42 03 04 7E 41 3A C1 76 0B",
        "requires a generic character id 0x80..0x82 and rejects special flags plus jobs 0x82..0x84",
    ),
    Anchor(
        "transformation-success-marker",
        0x309169,
        "66 44 89 49 12 C6 41 27 01 EB 0C",
        "stages result+0x12 bit 1 (word value 2) and marks a successful result",
    ),
    Anchor(
        "transformation-ineligible-result",
        0x309174,
        "44 88 01 C6 41 02 07 66 44 89 41 2C",
        "ineligible targets are converted to the native failure result rather than a status bundle",
    ),
    Anchor(
        "transformation-state-branch",
        0x30A80A,
        "41 F6 40 12 02 74 78 39 1D 69 07 56 01 75 6D",
        "state apply recognizes result+0x12 bit 1 as the transformation transaction",
    ),
    Anchor(
        "transformation-status-reset",
        0x30A857,
        "4C 8B 05 12 07 56 01 0F 57 C0 89 5F 57 41 B4 20 88 5F 5B 89 5F 5C 88 5F 60 89 5F 61 88 5F 65 0F 11 47 66 89 9F EF 01 00 00 88 9F F3 01 00 00",
        "the native branch clears the target's staged/current status and effect state during transformation",
    ),
)


def dispatch_target(pe: pefile.PE, raw: bytes) -> int:
    entry = dispatch.rva_bytes(pe, raw, DISPATCH_TABLE_RVA + FORMULA_ID * 8, 8)
    return struct.unpack("<Q", entry)[0] - pe.OPTIONAL_HEADER.ImageBase


def catalog_rows(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return [row for row in csv.DictReader(handle) if row.get("formula_hex", "").upper() == "0X58"]


def render(exe: Path, catalog_path: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    target = dispatch_target(pe, raw)
    rows = catalog_rows(catalog_path)
    catalog_ok = (
        len(rows) == 1
        and rows[0].get("id_dec") == "329"
        and rows[0].get("name_ivc") == "Malboro Spores"
        and rows[0].get("inflict_status_hex") == "0x00"
    )

    anchor_rows: list[tuple[Anchor, bool, str]] = []
    for anchor in ANCHORS:
        expected = bytes.fromhex(anchor.expected)
        actual = dispatch.rva_bytes(pe, raw, anchor.rva, len(expected))
        anchor_rows.append((anchor, actual == expected, " ".join(f"{value:02X}" for value in actual)))

    lines = [
        "# DCL Malboro Spores transformation analysis", "",
        "Generated by `tools/analyze_dcl_malboro_transformation.py`.", "",
        "## Inputs", "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Ability catalog: `{catalog_path}`",
        f"- Output: `{output}`", "",
        "## Dispatch and catalog", "",
        f"- Formula `0x58` handler: `0x{target:X}` (expected `0x{FORMULA_HANDLER_RVA:X}`): "
        f"**{'PASS' if target == FORMULA_HANDLER_RVA else 'FAIL'}**.",
        f"- Formula catalog contains only ability 329 Malboro Spores with no status payload: "
        f"**{'PASS' if catalog_ok else 'FAIL'}**.",
        "", "## Byte anchors", "",
        "| Name | RVA | Result | Meaning |", "| --- | ---: | --- | --- |",
    ]
    for anchor, passed, actual in anchor_rows:
        result = "PASS" if passed else f"FAIL (`{actual}`)"
        lines.append(f"| `{anchor.name}` | `0x{anchor.rva:X}` | {result} | {anchor.meaning} |")

    lines.extend([
        "", "## Static interpretation", "",
        "- **Strong:** formula `0x58` is a native unit-transformation transaction, not an InflictStatus",
        "  bundle. Its only catalog member has no status payload, and success stages dedicated result",
        "  bit `0x0002`.",
        "- **Strong:** eligibility requires character id `0x80..0x82`, rejects `unit+0x05 & 0x04`,",
        "  rejects nonzero `unit+0x1B4`, and rejects job ids `0x82..0x84`. The last range is a",
        "  rejection: byte addition wraps those three values to `0..2`, which takes the failure branch.",
        "- **Strong:** native state apply recognizes the dedicated bit and clears the unit's existing",
        "  statuses/effects as part of transformation. The protected native continuation owns the job/",
        "  appearance transition, so DCL should preserve it rather than synthesize status writes.",
        "- **Live gate:** only campaign/battle persistence and the exact transformed job presentation",
        "  remain observable integration checks; no custom DCL commit mechanism is required.", "",
    ])

    ok = target == FORMULA_HANDLER_RVA and catalog_ok and all(passed for _, passed, _ in anchor_rows)
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    if not args.exe.exists():
        raise SystemExit(f"executable not found: {args.exe}")
    if not args.catalog.exists():
        raise SystemExit(f"ability catalog not found: {args.catalog}")
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-malboro-transformation-analysis.md"
    report, ok = render(args.exe, args.catalog, output)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all Malboro transformation checks PASS" if ok else "one or more Malboro checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
