#!/usr/bin/env python3
"""Verify the paired live instant-KO compute-point resistance and lethal transactions."""
from __future__ import annotations

import argparse
import hashlib
import re
import time
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RESIST = ROOT / "work" / "1784093540-lt37a-dcl-instant-ko-compute-resist-resolved-live.log"
DEFAULT_KO = ROOT / "work" / "1784093827-lt37b-dcl-instant-ko-compute-ko-resolved-live.log"


def has(text: str, pattern: str) -> bool:
    return re.search(pattern, text, flags=re.MULTILINE) is not None


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


def checks(resist: str, ko: str) -> dict[str, bool]:
    expected_ai = (
        r"\[DCL-KO-COMPUTE\] phase=ai-expected .*target=0x82 ability=30 "
        r"resistance=14 successPermille=93 debit=40 credit=0"
    )
    expected_ai_bundle = (
        r"\[DCL-COMPUTE-POINT\].*battleState=0x5 .*target=0x82 ability=30 .*"
        r"hp=3/0->40/0 .*cached=0"
    )
    return {
        "resistance pass exposes exact expected lethal debit to AI": has(resist, expected_ai),
        "resistance pass publishes the AI bundle at compute point": has(resist, expected_ai_bundle),
        "resistance execution rolls exactly once and resists": len(re.findall(
            r"\[DCL-KO-COMPUTE\] phase=execution .*ability=30 .*roll=3 outcome=resisted debit=0 credit=0",
            resist,
        )) == 1,
        "resistance execution is cached at compute point": has(
            resist,
            r"\[DCL-COMPUTE-POINT\].*battleState=0x2A .*target=0x82 ability=30 .*"
            r"hp=3/0->0/0 .*flags=0x81->0x01 cached=1",
        ),
        "resistance pre-clamp consumes the zero debit": has(
            resist,
            r"\[DCL\].*target=0x82 abilityId=30 .*debit=0 oldDebit=3 .*computePoint=1",
        ),
        "resistance does not use the legacy instant-KO path": "[DCL-KO]" not in resist,
        "lethal pass exposes the same expected debit to AI": has(ko, expected_ai),
        "lethal pass publishes the same AI bundle at compute point": has(ko, expected_ai_bundle),
        "lethal execution rolls exactly once and owns KO": len(re.findall(
            r"\[DCL-KO-COMPUTE\] phase=execution .*ability=30 .*roll=18 "
            r"outcome=engine-owned-ko debit=430 credit=0",
            ko,
        )) == 1,
        "lethal execution is cached at compute point": has(
            ko,
            r"\[DCL-COMPUTE-POINT\].*battleState=0x2A .*target=0x82 ability=30 .*"
            r"hp=3/0->430/0 .*cached=1",
        ),
        "lethal pre-clamp consumes the exact cached debit": has(
            ko,
            r"\[DCL\].*target=0x82 abilityId=30 .*debit=430 oldDebit=3 .*computePoint=1",
        ),
        "native HP apply performs the KO transition": has(ko, r"\[DAMAGE .*id=0x82\] 430 -> 0 = 430"),
        "lethal pass does not use the legacy instant-KO path": "[DCL-KO]" not in ko,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--resist-log", type=Path, default=DEFAULT_RESIST)
    parser.add_argument("--ko-log", type=Path, default=DEFAULT_KO)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    resist_path = args.resist_log.resolve()
    ko_path = args.ko_log.resolve()
    resist = resist_path.read_text(encoding="utf-8", errors="replace")
    ko = ko_path.read_text(encoding="utf-8", errors="replace")
    results = checks(resist, ko)
    success = all(results.values())
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-instant-ko-compute-live-analysis.md"

    lines = [
        "# DCL instant-KO compute-point live analysis",
        "",
        "Generated by `tools/analyze_dcl_instant_ko_compute.py`.",
        "",
        "## Inputs",
        "",
        f"- Resistance log: `{resist_path}` (`SHA-256 {sha256(resist_path)}`).",
        f"- Lethal log: `{ko_path}` (`SHA-256 {sha256(ko_path)}`).",
        "",
        "## Checks",
        "",
        *[f"- **{'PASS' if ok else 'FAIL'}:** {name}." for name, ok in results.items()],
        "",
        f"Overall: **{'PASS' if success else 'FAIL'}**.",
        "",
        "## Interpretation",
        "",
        "- AI evaluation receives probability-weighted lethal debit without sampling execution RNG.",
        "- Confirmed charged-action execution samples one 3d6 contest and caches the final bundle.",
        "- Pre-clamp consumes the cached resistance or lethal result without a second contest.",
        "- Successful lethal debit reaches native HP apply; resisted delivery leaves HP ownership untouched.",
        "- The legacy instant-KO delivery path is absent from both transactions.",
        "",
    ]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    print(output)
    return 0 if success else 1


if __name__ == "__main__":
    raise SystemExit(main())
