#!/usr/bin/env python3
"""Verify the calc-order payload that identifies the weapon used by an Attack."""
from __future__ import annotations

import argparse
import hashlib
import time
from dataclasses import dataclass
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_64, Cs

import analyze_dcl_reaction_dispatch as dispatch


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = dispatch.DEFAULT_EXE


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected: str
    meaning: str


ANCHORS = (
    Anchor("order-copy-size", 0x3099CF, "B8 14 00 00 00", "copy exactly 0x14 bytes from the order record"),
    Anchor("order-copy-source", 0x3099D7, "4C 8B C1", "preserve incoming order-record pointer as copy source"),
    Anchor("order-copy-call", 0x3099E4, "E8 23 C9 D1 FF", "copy order record to the local stack record"),
    Anchor("payload-load", 0x309AF1, "0F B7 74 24 28", "load local order+8 word into SI"),
    Anchor("weapon-kind", 0x309E38, "BA 06 00 00 00", "select protected lookup kind 6 for the Attack payload"),
    Anchor("payload-validator", 0x309E3D, "0F B7 CE E8 9F F0 FA FF", "validate the payload carried in SI"),
    Anchor("payload-stage", 0x309E52, "66 89 35 21 69 4A 00", "stage the exact payload for weapon calculation"),
    Anchor("weapon-resolver", 0x309E5F, "E8 9C EF FA FF", "resolve the weapon row from the payload"),
    Anchor("weapon-formula", 0x309E7F, "8A 08", "read formula byte +0 from the resolved weapon row"),
    Anchor("formula-dispatch", 0x309F4B, "40 0F B6 C7 41 FF 94 C4 C8 2B 68 00", "dispatch the selected weapon formula"),
)


def parse_hex(value: str) -> bytes:
    return bytes.fromhex(value)


def hex_bytes(value: bytes) -> str:
    return " ".join(f"{byte:02X}" for byte in value)


def render_report(exe: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    md = Cs(CS_ARCH_X86, CS_MODE_64)

    rows: list[str] = []
    anchors_ok = True
    for anchor in ANCHORS:
        expected = parse_hex(anchor.expected)
        actual = dispatch.rva_bytes(pe, raw, anchor.rva, len(expected))
        ok = actual == expected
        anchors_ok &= ok
        result = "PASS" if ok else f"FAIL (`{hex_bytes(actual)}`)"
        rows.append(
            f"| `{anchor.name}` | `0x{anchor.rva:X}` | {result} | `{anchor.expected}` | {anchor.meaning} |"
        )

    mod_source = (ROOT / "codemod" / "fftivc.generic.chronicle.codemod" / "Mod.cs").read_text(encoding="utf-8")
    context_source = (ROOT / "codemod" / "fftivc.generic.chronicle.codemod" / "FormulaRuntimeContextBuilder.cs").read_text(encoding="utf-8")
    cache_source = (ROOT / "codemod" / "fftivc.generic.chronicle.codemod" / "DclHitDecisionCache.cs").read_text(encoding="utf-8")
    integration_checks = {
        "calc hook captures `word [rcx+8]`": '"movzx ebx, word [rcx+8]"' in mod_source,
        "ring slot persists payload at `+36`": '"mov dword [rsi+36], ebx"' in mod_source,
        "formula context publishes exact weapon item": 'context.Set("action.weaponItemId"' in context_source,
        "formula context publishes weapon-side match flags": 'context.Set("action.weaponMatchesRight"' in context_source and 'context.Set("action.weaponMatchesLeft"' in context_source,
        "hit-decision cache keys on payload": "entry.ActionPayload != actionPayload" in cache_source,
    }
    integration_ok = all(integration_checks.values())

    lines = [
        "# DCL active-weapon payload analysis",
        "",
        "Generated by `tools/analyze_dcl_active_weapon_payload.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Output: `{output}`",
        "",
        "## Native byte anchors",
        "",
        "| Name | RVA | Result | Expected bytes | Meaning |",
        "| --- | ---: | --- | --- | --- |",
        *rows,
        "",
        "## Managed integration",
        "",
        *[f"- **{'PASS' if ok else 'FAIL'}:** {name}." for name, ok in integration_checks.items()],
        "",
        "## Relevant native flow",
        "",
        *dispatch.disassembly(md, pe, raw, 0x3099CF, 0x130),
        "",
        *dispatch.disassembly(md, pe, raw, 0x309E38, 0x54),
        "",
        "## Static interpretation",
        "",
        "- **Proven:** `computeActionResult` copies the 20-byte order record and loads the word at",
        "  local `+8` into `SI`. The Attack branch validates that same value as protected kind 6,",
        "  resolves a weapon row from it, reads the row's formula byte, and dispatches that formula.",
        "- **Proven:** for action type 1, `orderRecord+8` is the selected weapon item ID. It is not a",
        "  hit ordinal or a right-hand assumption; it is the identity used by native weapon math.",
        "- **Proven:** the calc-entry hook captures the payload synchronously, carries it through the",
        "  DCL action cache, publishes `action.weapon.*`, and includes it in the hit-decision key.",
        "- **Strong:** comparing the payload with unit slots `+0x20` and `+0x24` identifies right or",
        "  left when equipped item IDs differ. If both IDs are equal, the side is ambiguous but the",
        "  exact weapon family and skill route are identical, so DCL weapon calculation is unaffected.",
        "- **Live boundary:** native Dual Wield cadence still needs a controlled battle capture to",
        "  prove that both strikes arrive as separate result transactions and retain their own payload.",
        "",
    ]
    return "\n".join(lines), anchors_ok and integration_ok


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check-only", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-active-weapon-payload-analysis.md"
    report, ok = render_report(args.exe, output)
    if not args.check_only:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(report, encoding="utf-8", newline="\n")
        print(f"wrote {output}")
    print("all active-weapon payload checks PASS" if ok else "one or more active-weapon payload checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
