#!/usr/bin/env python3
"""Verify the post-calc producer for 82 conditional, two performance, and two RandomFire status actions."""
from __future__ import annotations

import argparse
import csv
import hashlib
import re
import time
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

import pefile

import analyze_dcl_status_authority as authority
import analyze_dcl_status_transactions as status_tx


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = status_tx.DEFAULT_EXE
DEFAULT_CATALOG = status_tx.DEFAULT_CATALOG
PRODUCER_SOURCE = ROOT / "codemod" / "fftivc.generic.chronicle.codemod" / "DclStatusConditionalProducer.cs"
MOD_SOURCE = ROOT / "codemod" / "fftivc.generic.chronicle.codemod" / "Mod.cs"
CACHE_SOURCE = ROOT / "codemod" / "fftivc.generic.chronicle.codemod" / "DclActionContextCache.cs"


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected: bytes
    meaning: str


ANCHORS = (
    Anchor("calc-entry", 0x3099AC, bytes.fromhex("48 89 5C 24 18 55 56 57"), "universal per-action/target calculation entry"),
    Anchor("outer-calc-call", 0x281F0D, bytes.fromhex("E8 9A 7A 08 00"), "ordinary target sweep calls calc"),
    Anchor("post-calc-producer-host", 0x281F12, bytes.fromhex("48 FF C3 48 83 FB 15"), "outer calculation has completed before loop advance"),
)


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def parse_supported_formulas(source: str) -> set[int]:
    match = re.search(r"SupportedFormulas\s*=\s*\[(?P<body>.*?)\];", source, re.DOTALL)
    if not match:
        return set()
    return {int(token, 16) for token in re.findall(r"0x[0-9A-Fa-f]+", match.group("body"))}


def render(exe: Path, catalog_path: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    producer_source = PRODUCER_SOURCE.read_text(encoding="utf-8")
    mod_source = MOD_SOURCE.read_text(encoding="utf-8")
    cache_source = CACHE_SOURCE.read_text(encoding="utf-8")

    supported_formulas = parse_supported_formulas(producer_source)
    expected_formulas = set(
        authority.CONDITIONAL_FORMULAS | authority.PERFORMANCE_FORMULAS | authority.RANDOM_FIRE_FORMULAS
    )
    formula_set_ok = supported_formulas == expected_formulas

    rows = read_rows(catalog_path)
    conditional = [
        row for row in rows
        if row["inflict_statuses"].strip() and int(row["formula_hex"], 16) in supported_formulas
    ]
    mode_counts = Counter(row["inflict_status_mode"] for row in conditional)
    inventory_ok = len(conditional) == 86 and {int(row["id_dec"]) for row in conditional} == {
        int(row["id_dec"]) for row in rows
        if row["inflict_statuses"].strip() and int(row["formula_hex"], 16) in expected_formulas
    }

    anchor_rows = []
    for anchor in ANCHORS:
        actual = status_tx.rva_bytes(pe, raw, anchor.rva, len(anchor.expected))
        anchor_rows.append((anchor, actual == anchor.expected, actual))

    producer_tokens = (
        "UsesPostCalcProducer",
        "packet ownership mismatch",
        "NativePacketBit",
        "RequiredContestMode",
        "IsBlockedByNativeEligibility",
        "IsRandomFireFormula",
    )
    # RequiredContestMode is represented by the local requiredContestMode identifier, not a method.
    producer_token_ok = all(token in producer_source for token in producer_tokens[:3]) and \
        "requiredContestMode" in producer_source and all(token in producer_source for token in producer_tokens[4:])
    mod_tokens = (
        "BuildDclStatusProducerShimLines",
        "DclStatusProducerCallbackImpl",
        "TryGetLatestConfirmedExecution",
        "DclPreparedStatusPlan",
        "suppressedByHit",
        "StageDclStatusPacket",
    )
    mod_ok = all(token in mod_source for token in mod_tokens)
    cache_ok = all(token in cache_source for token in (
        "OuterSweepReturnRva = 0x281F12",
        "ForecastTraceReturnRva = 0xEF53F14",
        "ConfirmedExecutionBattleState = 0x2A",
        "NativeRepeatExecutionBattleState = 0x2F",
        "IsExecutionBattleState",
        "origin == DclCalcOrigin.NestedRendAttack",
    ))

    lines = [
        "# DCL conditional-status producer analysis",
        "",
        "Generated by `tools/analyze_dcl_status_conditional_producer.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Ability catalog: `{catalog_path}`",
        f"- Output: `{output}`",
        "",
        "## Native anchors",
        "",
        "| Anchor | RVA | Result | Meaning |",
        "| --- | ---: | --- | --- |",
    ]
    for anchor, passed, actual in anchor_rows:
        result = "PASS" if passed else f"FAIL (`{actual.hex(' ').upper()}`)"
        lines.append(f"| `{anchor.name}` | `0x{anchor.rva:X}` | {result} | {anchor.meaning} |")

    lines.extend([
        "",
        "## Inventory and implementation contract",
        "",
        f"- C# formula allowlist equals 12 conditional, two performance, and two RandomFire families: **{'PASS' if formula_set_ok else 'FAIL'}**.",
        f"- Catalog rows owned by those families: `{len(conditional)}` (expected `86`): **{'PASS' if inventory_ok else 'FAIL'}**.",
        f"- Native-mode counts: `{dict(sorted(mode_counts.items()))}`.",
        f"- Producer source enforces exact policy and complete packet ownership: **{'PASS' if producer_token_ok else 'FAIL'}**.",
        f"- Runtime source binds the post-calc callback, one cached plan, hit suppression, and native packet staging: **{'PASS' if mod_ok else 'FAIL'}**.",
        f"- Calc cache binds LT28 provenance and refuses the nested Rend overwrite: **{'PASS' if cache_ok else 'FAIL'}**.",
        "",
        "## Boundary",
        "",
        "The producer runs at outer-sweep return `0x281F12` and requires fire-time battle state `0x2A`.",
        "Forecast calls return through `.trace` at `0xEF53F14` in state `0x19`, so they cannot consume",
        "the execution 3d6 decision. Formula-`0x25` nested Attack rows are retained as evidence but do",
        "not replace the outer action identity in the apply cache.",
        "Formula `0x1C/0x1D` performance ticks use the same packet producer and exact catalog-derived",
        "random-one ownership. Their native caster-Sleep eligibility check remains mandatory before",
        "the managed contest; native cadence and cleanup remain live-gated.",
        "Formula `0x1E/0x1F` RandomFire actions also use exact catalog-derived random-one ownership.",
        "The native carrier selects and calculates one target per repeat; the producer therefore stages",
        "one fresh status packet per repeat while the hit cache retains spell-level Magic Evade per target.",
        "",
        "For each configured post-calc action the loaded catalog supplies the complete native packet",
        "bit set and native bundle mode. Ordinary replacement derives ownership from output bits; an",
        "explicit reskin proves a separate native source bit for every DCL output. The producer clears",
        "every owned source bit before applying output writes, stages the",
        "result through the native five-byte add/remove transaction, and caches that exact decision for",
        "pre-clamp reuse. A fully resisted or ineligible status-only action clears the packet and never",
        "needs to reach pre-clamp. Forecast percentage and AI scoring still use native read-only behavior",
        "until their authored-probability presentation layer is implemented.",
        "",
    ])

    ok = all(passed for _, passed, _ in anchor_rows) and formula_set_ok and inventory_ok and producer_token_ok and mod_ok and cache_ok
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-status-conditional-producer-analysis.md"
    report, ok = render(args.exe, args.catalog, output)
    if not args.check_only:
        output.write_text(report, encoding="utf-8", newline="\n")
        print(f"wrote {output}")
    print("all conditional-status producer checks PASS" if ok else "one or more conditional-status producer checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
