#!/usr/bin/env python3
"""Verify the current-build Bequeath Bacon/Crystal native ownership boundary."""
from __future__ import annotations

import argparse
import hashlib
import struct
import time
from dataclasses import dataclass
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_64, Cs


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = Path(
    r"D:/SteamLibrary/steamapps/common/FINAL FANTASY TACTICS - The Ivalice Chronicles/FFT_enhanced.exe"
)
FORMULA_TABLE_RVA = 0x682BC8
FORMULA_ID = 0x57
EXPECTED_HANDLER_RVA = 0x30905C


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected: str
    meaning: str


@dataclass(frozen=True)
class Window:
    name: str
    rva: int
    size: int


ANCHORS = (
    Anchor("formula-57-handler", 0x30905C, "48 89 5C 24 08", "formula 0x57 handler prologue"),
    Anchor("level-cap-99", 0x30908D, "80 7F 29 63", "rejects a target already at level 99"),
    Anchor("stage-level-up-flag", 0x3090A4, "B8 80 00 00 00", "loads native level-up flag 0x80"),
    Anchor("stage-success", 0x3090A9, "C6 43 27 01", "marks the native result successful"),
    Anchor("write-level-up-flag", 0x3090AD, "66 89 43 12", "writes flag 0x80 to result+0x12"),
    Anchor("select-special-actor", 0x3090CD, "C6 00 01", "selects the special actor before native finalization"),
    Anchor("native-special-finalizer", 0x3090D0, "E8 B3 D8 FF FF", "calls the protected native finalizer"),
    Anchor("read-current-level", 0x30A7AF, "0F B6 4F 29", "reads unit level during state apply"),
    Anchor("increment-level", 0x30A7B8, "FF C1", "increments the staged level"),
    Anchor("write-level", 0x30A7E8, "88 4F 29", "writes the bounded level to unit+0x29"),
    Anchor("status-apply-gate", 0x30A80A, "41 F6 40 12 02", "enters native status processing when result bit 0x02 is set"),
    Anchor("status-table-loop", 0x30A83C, "84 54 38 61", "reads native status bits through the 40-entry status loop"),
    Anchor("crystal-ko-lifecycle-gate", 0x30A895, "F6 47 61 60", "treats Crystal/KO as protected lifecycle states"),
)

WINDOWS = (
    Window("formula-57-handler", 0x30905C, 0x92),
    Window("level-and-status-apply", 0x30A7A0, 0x104),
)


def parse_hex(value: str) -> bytes:
    return bytes.fromhex(value)


def hex_bytes(value: bytes) -> str:
    return " ".join(f"{byte:02X}" for byte in value)


def rva_bytes(pe: pefile.PE, raw: bytes, rva: int, size: int) -> bytes:
    offset = pe.get_offset_from_rva(rva)
    return raw[offset : offset + size]


def disassemble_window(md: Cs, pe: pefile.PE, raw: bytes, image_base: int, window: Window) -> list[str]:
    blob = rva_bytes(pe, raw, window.rva, window.size)
    rows = [f"### {window.name}", "", "```text"]
    for instruction in md.disasm(blob, image_base + window.rva):
        rva = instruction.address - image_base
        rendered = f"{instruction.mnemonic} {instruction.op_str}".strip()
        marker = " ; ANCHOR" if any(anchor.rva == rva for anchor in ANCHORS) else ""
        rows.append(f"{rva:08X}: {hex_bytes(instruction.bytes):<28} {rendered}{marker}")
    rows.extend(["```", ""])
    return rows


def render_report(exe: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    image_base = pe.OPTIONAL_HEADER.ImageBase
    entry_rva = FORMULA_TABLE_RVA + FORMULA_ID * 8
    entry = struct.unpack("<Q", rva_bytes(pe, raw, entry_rva, 8))[0]
    handler_rva = entry - image_base
    dispatch_ok = handler_rva == EXPECTED_HANDLER_RVA

    anchor_rows: list[str] = []
    anchors_ok = True
    for anchor in ANCHORS:
        expected = parse_hex(anchor.expected)
        actual = rva_bytes(pe, raw, anchor.rva, len(expected))
        ok = actual == expected
        anchors_ok &= ok
        status = "PASS" if ok else f"FAIL (`{hex_bytes(actual)}`)"
        anchor_rows.append(
            f"| `{anchor.name}` | `0x{anchor.rva:X}` | {status} | `{anchor.expected}` | {anchor.meaning} |"
        )

    lines = [
        "# Bequeath Bacon / Crystal Disassembly Analysis",
        "",
        "Generated by `tools/analyze_bequeath_crystal_disasm.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- PE image base: `0x{image_base:X}`",
        f"- Output: `{output}`",
        "",
        "## Formula dispatch",
        "",
        f"- Formula table: RVA `0x{FORMULA_TABLE_RVA:X}`.",
        f"- Entry `0x{FORMULA_ID:02X}`: RVA `0x{handler_rva:X}` ({'PASS' if dispatch_ok else 'FAIL'}; expected `0x{EXPECTED_HANDLER_RVA:X}`).",
        "- The older `0x3090F4` mapping does not belong to formula `0x57` in this executable.",
        "",
        "## Byte anchors",
        "",
        "| Name | RVA | Result | Expected bytes | Meaning |",
        "| --- | ---: | --- | --- | --- |",
        *anchor_rows,
        "",
        "## Static interpretation",
        "",
        "- **Strong:** formula `0x57` has a dedicated current-build handler. It reads the target level at",
        "  `unit+0x29`, rejects level 99, and stages result bit `0x80` at `result+0x12`.",
        "- **Strong:** the native state-apply routine interprets that bit as level +1, caps the result at",
        "  99, writes `unit+0x29`, and then processes status metadata through the native 40-status loop.",
        "- **Strong:** the ability data names Crystal as the caster-side status, while the formula handler",
        "  redirects the special actor/result globals before entering the protected native finalizer.",
        "  The finalizer itself is virtualized, so this is not promoted to Proven without a live trace.",
        "- **Strong:** the state-apply tail treats `unit+0x61 & 0x60` (Crystal or KO) as a lifecycle gate,",
        "  rather than as an ordinary temporary status.",
        "",
        "## DCL ownership consequence",
        "",
        "Bequeath Bacon remains native and unchanged. The DCL does not replace formula `0x57`, does not",
        "rewrite its level mutation, and never writes or clears Crystal directly. This preserves the native",
        "level-gain plus caster-crystallization/campaign lifecycle selected by the DCL design. A live test is",
        "a regression gate only if formula `0x57`, its status data, or the lifecycle tail is later modified.",
        "",
    ]
    md = Cs(CS_ARCH_X86, CS_MODE_64)
    for window in WINDOWS:
        lines.extend(disassemble_window(md, pe, raw, image_base, window))
    return "\n".join(lines), dispatch_ok and anchors_ok


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-bequeath-crystal-disassembly-analysis.md"
    report, ok = render_report(args.exe, output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report, encoding="utf-8")
    print(f"wrote {output}")
    print("all anchors PASS" if ok else "one or more anchors FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
