#!/usr/bin/env python3
"""Verify the formula-0x38 direct-finalizer carrier and its fail-closed DCL subset."""
from __future__ import annotations

import argparse
import csv
import hashlib
import time
from pathlib import Path

import pefile

import analyze_dcl_status_transactions as status_tx


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = status_tx.DEFAULT_EXE
DEFAULT_CATALOG = status_tx.DEFAULT_CATALOG
FORMULA_ID = 0x38
FINALIZER_RVA = 0x306988

SAFE_IDS = {
    149, 181, 182, 187, 188, 189, 190, 191, 192, 193, 195,
    194, 287, 313, 326, 327, 328, 346, 350, 356,
}
BLOCKED = {
    183: "Dead lifecycle",
    262: "Dead lifecycle plus random one-of bundle",
}


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def status_tokens(row: dict[str, str]) -> list[str]:
    return [token for token in row["inflict_statuses"].split("|") if token]


def render(exe: Path, catalog_path: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    target = status_tx.dispatch_targets(pe, raw)[FORMULA_ID]
    dispatch_ok = target == FINALIZER_RVA
    finalizer_anchor = status_tx.rva_bytes(pe, raw, FINALIZER_RVA, 5)
    finalizer_ok = finalizer_anchor == bytes.fromhex("E9 43 4E F0 0F")

    rows = [
        row for row in load_rows(catalog_path)
        if row["formula_hex"].upper() == "0X38" and row["inflict_statuses"].strip()
    ]
    ids = {int(row["id_dec"]) for row in rows}
    inventory_ok = len(rows) == 22 and ids == SAFE_IDS | set(BLOCKED)
    formula_text_ok = all("Hit_(100%) Status" in row["formula_text"] for row in rows)

    derived_safe = set()
    derived_blocked: dict[int, str] = {}
    for row in rows:
        ability_id = int(row["id_dec"])
        tokens = status_tokens(row)
        mode = row["inflict_status_mode"]
        if "Dead" in tokens:
            derived_blocked[ability_id] = "Dead lifecycle"
        elif mode in {"AllOrNothing", "Cancel", "Separate", "Random"}:
            derived_safe.add(ability_id)
        else:
            derived_blocked[ability_id] = f"unsupported mode {mode}"
    partition_ok = derived_safe == SAFE_IDS and set(derived_blocked) == set(BLOCKED)

    lines = [
        "# DCL formula-0x38 retained-carrier analysis",
        "",
        "Generated by `tools/analyze_dcl_formula38_carriers.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Ability catalog: `{catalog_path}`",
        f"- Output: `{output}`",
        "",
        "## Native contract",
        "",
        f"- Formula `0x38` dispatch target: `0x{target:X}` "
        f"(**{'PASS' if dispatch_ok else 'FAIL'}**; expected the status finalizer itself).",
        f"- Finalizer thunk bytes: `{finalizer_anchor.hex(' ').upper()}`: "
        f"**{'PASS' if finalizer_ok else 'FAIL'}**.",
        f"- All 22 formula rows declare `Hit_(100%) Status`: **{'PASS' if formula_text_ok else 'FAIL'}**.",
        "",
        "Formula `0x38` has no real-code prerequisite/chance wrapper before the common finalizer. Its",
        "native status payload is therefore sufficient to preserve result production while pre-clamp",
        "replaces every owned packet bit.",
        "",
        "## Fail-closed partition",
        "",
        "| Ability | Name | Mode | Native statuses | DCL carrier result |",
        "| ---: | --- | --- | --- | --- |",
    ]
    for row in rows:
        ability_id = int(row["id_dec"])
        if ability_id in SAFE_IDS:
            result = "approved retained carrier"
        else:
            result = "blocked — " + BLOCKED[ability_id]
        lines.append(
            f"| {ability_id} | {row['name_ivc'] or '<blank>'} | {row['inflict_status_mode']} | "
            f"{row['inflict_statuses']} | {result} |"
        )

    lines.extend([
        "",
        f"Exact 22-row inventory: **{'PASS' if inventory_ok else 'FAIL'}**.",
        f"Derived safe/blocked partition: **{'PASS' if partition_ok else 'FAIL'}**.",
        "",
        "## Ownership semantics",
        "",
        "The approved 20-action subset contains only:",
        "",
        "- one-bit all-or-nothing actions, which map to one authored contest;",
        "- cancel actions, whose complete native remove set is deterministically owned;",
        "- separate-mode bundles, whose bits already represent independent outcomes.",
        "- random-one bundles, whose group caches one selected member and one shared contest;",
        "- multi-bit all-or-nothing bundles, whose group shares one contest across every bit.",
        "",
        "Every inherited bit must have one `retained-as-carrier` rule with `ActionType=-1`. Conditions",
        "are forbidden and evaluation errors clear the inherited bit fail-closed. Nightmare and Toot",
        "use `random-one`; Poisonous Frog uses `all-or-nothing`. The two Dead-bearing actions remain",
        "outside generic status ownership and require the lifecycle owner.",
        "",
    ])
    ok = dispatch_ok and finalizer_ok and inventory_ok and formula_text_ok and partition_ok
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()
    if not args.exe.exists():
        raise SystemExit(f"executable not found: {args.exe}")
    if not args.catalog.exists():
        raise SystemExit(f"ability catalog not found: {args.catalog}")
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-formula38-carrier-analysis.md"
    report, ok = render(args.exe, args.catalog, output)
    if not args.check_only:
        output.write_text(report, encoding="utf-8", newline="\n")
        print(f"wrote {output}")
    print("all formula-0x38 carrier checks PASS" if ok else "one or more formula-0x38 carrier checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
