#!/usr/bin/env python3
"""Verify the current-build native Magick Counter spell-copy payload path."""
from __future__ import annotations

import argparse
import hashlib
import time
from pathlib import Path

import pefile


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = Path(
    r"D:/SteamLibrary/steamapps/common/FINAL FANTASY TACTICS - The Ivalice Chronicles/FFT_enhanced.exe"
)

ANCHORS = (
    (0x3099E4, "E8 23 C9 D1 FF", "copies the 20-byte incoming order record to stack+0x20"),
    (0x309B55, "0F B7 7C 24 22", "loads incoming orderRecord+2 ability id into DI"),
    (0x309B66, "66 89 3D 0B 6C 4A 00", "publishes that ability id to word RVA 0x7B0778"),
    (0x30B981, "A8 04 74 24", "routes reaction bit unit+0x95 bit 0x04 to Magick Counter"),
    (0x30B99F, "B8 B3 01 00 00", "selects exact reaction id 435"),
    (0x30B82B, "0F B7 05 46 4F 4A 00", "reloads the incoming ability id from RVA 0x7B0778"),
    (0x30BB3C, "66 89 43 28", "stores the copied id at result+0x28 = unit+0x1E6"),
    (0x28312A, "44 0F B7 83 E6 01 00 00", "pass 2 loads the copied spell id from unit+0x1E6"),
    (0x283120, "BA 0B 00 00 00", "selects typed-order kind 0x0B for the copied spell"),
)


def rva_bytes(pe: pefile.PE, raw: bytes, rva: int, size: int) -> bytes:
    return raw[pe.get_offset_from_rva(rva) : pe.get_offset_from_rva(rva) + size]


def render(exe: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    checks = []
    for rva, expected_hex, meaning in ANCHORS:
        expected = bytes.fromhex(expected_hex)
        checks.append((rva, meaning, rva_bytes(pe, raw, rva, len(expected)) == expected))
    ok = all(passed for _, _, passed in checks)

    lines = [
        "# DCL native Magick Counter payload analysis",
        "",
        "Generated by `tools/analyze_dcl_magick_counter.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Output: `{output}`",
        "",
        "## Anchor verification",
        "",
        "| RVA | Result | Meaning |",
        "| ---: | --- | --- |",
    ]
    for rva, meaning, passed in checks:
        lines.append(f"| `0x{rva:X}` | {'PASS' if passed else 'FAIL'} | {meaning} |")
    lines.extend(
        [
            "",
            "## Native contract",
            "",
            "The calc path copies the incoming order record, reads its exact ability id from `+2`, and",
            "publishes it at word RVA `0x7B0778`. When Magick Counter `435` is selected, the reaction",
            "dispatcher copies that word into reactor `unit+0x1E6`. Pass 2 then builds a typed order of",
            "kind `0x0B` with `unit+0x1E6` as its payload. Native Magick Counter is therefore an exact",
            "incoming-spell copy path, not a generic magic-flavoured basic attack.",
            "",
            "## DCL implementation boundary",
            "",
            "The final Rod Counter must not retain this payload. Its effect is one basic Rod bolt with",
            "the DCL Rod formula and Magic Evade, so it needs a basic-action carrier/order rather than",
            "the native copied-spell payload. Counter `442` already authors type `1`, payload `0` against",
            "the incoming source and is the stronger carrier candidate once the trigger producer and",
            "execution provenance are proven. Replacing only the mirrored actor action id after queue",
            "commit remains insufficient until the VM worker's dependence on the typed order is proven.",
            "",
        ]
    )
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-magick-counter-analysis.md"
    report, ok = render(args.exe, output)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all Magick Counter checks PASS" if ok else "one or more Magick Counter checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
