#!/usr/bin/env python3
"""Verify the current-build selector route for blank Reaction carrier 443."""
from __future__ import annotations

import argparse
import hashlib
import sqlite3
import time
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_64, Cs


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = Path(
    r"D:/SteamLibrary/steamapps/common/FINAL FANTASY TACTICS - The Ivalice Chronicles/FFT_enhanced.exe"
)
DEFAULT_OVERRIDE_DB = ROOT / "work" / "override_ability.sqlite"
CARRIER_ID = 443

ANCHORS = (
    (0x30B935, "44 8A 81 96 00 00 00", "loads reaction-set byte unit+0x96"),
    (0x30B837, "41 B3 08", "loads mask 0x08 later reused for Counter in unit+0x96"),
    (0x30B958, "45 84 C3", "tests unit+0x96 against the Counter mask"),
    (0x30B977, "B8 BA 01 00 00", "selects exact reaction id 442 when the Counter bit passes"),
    (0x30B827, "66 89 43 10", "stages the selected id at result+0x10 = unit+0x1CE"),
    (0x282E55, "44 8B 15 98 81 5E 01", "loads incoming-source/exclusion index global RVA 0x186AFF4"),
    (0x282E9A, "48 0F BF B3 CE 01 00 00", "reads the candidate exact id from unit+0x1CE"),
    (0x282F1E, "66 89 77 02", "writes candidate id to the staged order record"),
    (0x282F22, "66 89 35 C7 80 5E 01", "publishes the exact reaction id globally"),
    (0x282F73, "48 8D 0D 86 D0 D7 FF", "enters the generic-reaction ability-flag route"),
    (0x282F7A, "F6 84 0E 8A F5 67 00 30", "rejects generic records whose flags contain 0x30"),
    (0x282F88, "0F B7 43 20", "generic route begins from the reactor tile X"),
    (0x282FE6, "0F B6 43 4F", "writes the selected target tile X"),
    (0x283003, "E9 C4 01 00 00", "generic route skips the special materialization/helper branch"),
    (0x2831CC, "66 41 89 36 8B C5 40 88 2F", "generic route joins common selector finalization"),
    (0x206414, "89 83 8C 01 00 00", "mirrors selected id to actor+0x18C"),
    (0x20641A, "66 89 83 42 01 00 00", "mirrors selected id to actor+0x142"),
    (0x206421, "40 88 B3 D3 01 00 00", "post-selector commit boundary"),
)


def rva_bytes(pe: pefile.PE, raw: bytes, rva: int, size: int) -> bytes:
    return raw[pe.get_offset_from_rva(rva) : pe.get_offset_from_rva(rva) + size]


def override_span(path: Path) -> tuple[int | None, int | None, int | None, str]:
    if not path.exists():
        return None, None, None, "database missing"
    try:
        with sqlite3.connect(path) as connection:
            row = connection.execute(
                "SELECT COUNT(*), MIN(Key), MAX(Key) FROM OverrideAbilityActionData"
            ).fetchone()
        return int(row[0]), int(row[1]), int(row[2]), "ok"
    except Exception as exc:
        return None, None, None, f"{type(exc).__name__}: {exc}"


def render(exe: Path, override_db: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    checks = []
    for rva, expected_hex, meaning in ANCHORS:
        expected = bytes.fromhex(expected_hex)
        checks.append((rva, meaning, rva_bytes(pe, raw, rva, len(expected)) == expected))

    md = Cs(CS_ARCH_X86, CS_MODE_64)
    scan_start, scan_end = 0x30B935, 0x30BB40
    instructions = list(md.disasm(
        rva_bytes(pe, raw, scan_start, scan_end - scan_start),
        pe.OPTIONAL_HEADER.ImageBase + scan_start,
    ))
    dispatcher_omits_carrier_bit = not any(
        ins.mnemonic == "test" and ins.op_str.replace(" ", "") in {"r8b,4", "r8b,0x4"}
        for ins in instructions
    )
    generic_flag = rva_bytes(pe, raw, 0x67F58A + CARRIER_ID, 1)[0]
    selector_accepts_carrier = (generic_flag & 0x30) == 0
    count, minimum, maximum, db_status = override_span(override_db)
    override_excludes_carrier = db_status == "ok" and maximum is not None and maximum < CARRIER_ID
    ok = (
        all(passed for _, _, passed in checks)
        and dispatcher_omits_carrier_bit
        and selector_accepts_carrier
        and override_excludes_carrier
    )

    lines = [
        "# DCL blank Reaction carrier 443 analysis",
        "",
        "Generated by `tools/analyze_dcl_blank_reaction_carrier.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Override database: `{override_db}`",
        f"- Output: `{output}`",
        "",
        "## Anchor verification",
        "",
        "| RVA | Result | Meaning |",
        "| ---: | --- | --- |",
    ]
    for rva, meaning, passed in checks:
        lines.append(f"| `0x{rva:X}` | {'PASS' if passed else 'FAIL'} | {meaning} |")
    lines.extend([
        f"| `0x30B935..0x30BB40` | {'PASS' if dispatcher_omits_carrier_bit else 'FAIL'} | dispatcher omits the equipped bit corresponding to carrier 443 |",
        f"| `0x{0x67F58A + CARRIER_ID:X}` | {'PASS' if selector_accepts_carrier else 'FAIL'} | generic selector flag is `0x{generic_flag:02X}`; mask `0x30` is clear |",
        "",
        "## Override-table boundary",
        "",
        f"- SQLite check: `{db_status}`.",
        f"- Row span: count `{count}`, min `{minimum}`, max `{maximum}`.",
        f"- Carrier 443 excluded from `OverrideAbilityActionData`: **{'PASS' if override_excludes_carrier else 'FAIL'}**.",
        "",
        "## Generic carrier contract",
        "",
        "Carrier `443` is structurally accepted by the pass-2 generic selector when staged in",
        "`unit+0x1CE`, but its equipped bit has no native dispatcher branch and its generic order",
        "starts from the reactor tile and skips special materialization RVA `0x2831BD`. It is therefore",
        "a useful neutral **owner identity** for trigger production, but not a source-target delivery",
        "carrier. Synthetic delivery must be configured separately with native semantics appropriate",
        "to the intended effect. No ability name or effect policy follows from carrier `443` itself.",
        "",
        "The adjacent reaction-set mapping is operationally significant: `unit+0x96 & 0x08` stages",
        "Counter `442`, while carrier `443` corresponds to `unit+0x96 & 0x04` and is omitted by the",
        "dispatcher. A live-unit fixture that changes equipped `442` to `443` must clear `0x08` and",
        "set `0x04`; changing only the equipped word leaves native Counter staging enabled.",
        "",
    ])
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--override-db", type=Path, default=DEFAULT_OVERRIDE_DB)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-blank-reaction-carrier-analysis.md"
    report, ok = render(args.exe, args.override_db, output)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("blank Reaction carrier checks PASS" if ok else "blank Reaction carrier checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
