#!/usr/bin/env python3
"""Verify the current-build battle-state pipeline that consumes a queued Reaction actor."""
from __future__ import annotations

import argparse
import hashlib
import time
from dataclasses import dataclass
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_64, Cs
from capstone.x86 import X86_OP_MEM, X86_REG_RIP

import analyze_dcl_reaction_dispatch as dispatch


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = dispatch.DEFAULT_EXE
BATTLE_STATE_RVA = 0xC6B1CC


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected: str
    meaning: str


ANCHORS = (
    Anchor("state-global-load", 0x211B23, "8B 0D A3 96 A5 00", "dispatcher loads the battle-state dword"),
    Anchor("state-range-24", 0x212065, "83 F9 24 0F 8F 91 03 00 00", "routes states above 0x24"),
    Anchor("state-29-branch", 0x21242A, "83 F9 01 0F 85 B9 16 00 00", "final compare selecting state 0x29"),
    Anchor("state-29-update", 0x212433, "E8 48 54 FF FF", "state 0x29 enters the common battle update"),
    Anchor("state-29-to-2a", 0x21246D, "C7 05 55 8D A5 00 2A 00 00 00", "state 0x29 advances to 0x2A"),
    Anchor("state-2a-actor", 0x2127A2, "E8 F5 DF 04 00", "state 0x2A resolves the current actor"),
    Anchor("state-2a-reaction-id", 0x2127D6, "48 63 8E 8C 01 00 00", "state 0x2A reads actor+0x18C"),
    Anchor("state-2b-vm-poll", 0x212D50, "E8 CF 15 06 00", "state 0x2B calls the first VM-owned worker"),
    Anchor("state-2b-vm-apply", 0x212D69, "E8 EA 39 FF FF", "state 0x2B calls the second VM-owned worker"),
    Anchor("state-2c-actor", 0x212C29, "E8 6E DB 04 00", "state 0x2C resolves the current actor"),
    Anchor("state-2c-to-2d", 0x212C3A, "C7 05 88 85 A5 00 2D 00 00 00", "state 0x2C advances to 0x2D"),
    Anchor("state-2c-action-id", 0x212C9B, "44 0F B7 88 42 01 00 00", "state 0x2C reads actor+0x142"),
    Anchor("state-2d-cleanup-call", 0x212C1F, "E8 2C A0 FF FF", "state 0x2D enters the real-code cleanup function"),
    Anchor("cleanup-action-id", 0x20CD17, "0F B7 93 42 01 00 00", "cleanup reads actor+0x142"),
    Anchor("cleanup-target-count", 0x20CCCD, "8A 83 A9 01 00 00", "cleanup reads actor+0x1A9 target count"),
    Anchor("cleanup-target-list", 0x20CCDA, "48 8D B3 AA 01 00 00", "cleanup addresses actor+0x1AA target indices"),
)

STATE_WRITES = (
    ("queue-to-29", 0x2063C0, 0x29),
    ("state-29-to-2a", 0x21246D, 0x2A),
    ("state-2c-to-2d", 0x212C3A, 0x2D),
)


def parse_hex(value: str) -> bytes:
    return bytes.fromhex(value)


def hex_bytes(value: bytes) -> str:
    return " ".join(f"{byte:02X}" for byte in value)


def rip_target(md: Cs, pe: pefile.PE, raw: bytes, rva: int) -> int | None:
    code = dispatch.rva_bytes(pe, raw, rva, 16)
    instruction = next(iter(md.disasm(code, pe.OPTIONAL_HEADER.ImageBase + rva)), None)
    if instruction is None:
        return None
    for operand in instruction.operands:
        if operand.type == X86_OP_MEM and operand.mem.base == X86_REG_RIP:
            return instruction.address + instruction.size + operand.mem.disp - pe.OPTIONAL_HEADER.ImageBase
    return None


def render_report(exe: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    md = Cs(CS_ARCH_X86, CS_MODE_64)
    md.detail = True

    anchors_ok = True
    rows: list[str] = []
    for anchor in ANCHORS:
        expected = parse_hex(anchor.expected)
        actual = dispatch.rva_bytes(pe, raw, anchor.rva, len(expected))
        ok = actual == expected
        anchors_ok &= ok
        result = "PASS" if ok else f"FAIL (`{hex_bytes(actual)}`)"
        rows.append(f"| `{anchor.name}` | `0x{anchor.rva:X}` | {result} | `{anchor.expected}` | {anchor.meaning} |")

    load_target = rip_target(md, pe, raw, 0x211B23)
    write_rows: list[str] = []
    state_targets_ok = load_target == BATTLE_STATE_RVA
    for name, rva, value in STATE_WRITES:
        target = rip_target(md, pe, raw, rva)
        ok = target == BATTLE_STATE_RVA
        state_targets_ok &= ok
        target_text = f"`0x{target:X}`" if target is not None else "none"
        write_rows.append(f"| `{name}` | `0x{rva:X}` | `0x{value:X}` | {target_text} |")

    lines = [
        "# DCL queued-Reaction execution-state analysis",
        "",
        "Generated by `tools/analyze_dcl_reaction_execution.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Battle-state global: `0x{BATTLE_STATE_RVA:X}`",
        f"- Output: `{output}`",
        "",
        "## Byte anchors",
        "",
        "| Name | RVA | Result | Expected bytes | Meaning |",
        "| --- | ---: | --- | --- | --- |",
        *rows,
        "",
        "## Shared battle-state authority",
        "",
        f"- Dispatcher load target: `{f'0x{load_target:X}' if load_target is not None else 'none'}`.",
        "",
        "| Transition | RVA | Value | RIP target |",
        "| --- | ---: | ---: | ---: |",
        *write_rows,
        "",
        f"All checked transitions use the dispatcher global: **{'PASS' if state_targets_ok else 'FAIL'}**.",
        "",
        "## State windows",
        "",
        "### State `0x29` setup and transition",
        "",
        *dispatch.disassembly(md, pe, raw, 0x21242A, 0x58),
        "",
        "### State `0x2A` actor/reaction presentation inputs",
        "",
        *dispatch.disassembly(md, pe, raw, 0x2127A2, 0x65),
        "",
        "### State `0x2B` VM-owned execution workers",
        "",
        *dispatch.disassembly(md, pe, raw, 0x212D50, 0x28),
        "",
        "### States `0x2C` / `0x2D` transition",
        "",
        *dispatch.disassembly(md, pe, raw, 0x212C1F, 0x95),
        "",
        "### Real-code cleanup action/target reads",
        "",
        *dispatch.disassembly(md, pe, raw, 0x20CCCD, 0x65),
        "",
        "## Static interpretation",
        "",
        "- **Strong:** the accepted queue path and the dispatcher use the same battle-state global.",
        "  The queued actor enters state `0x29`, whose real-code handler advances explicitly to `0x2A`.",
        "  The dispatcher also has adjacent handlers for `0x2B`, `0x2C`, and `0x2D`; `0x2C` advances",
        "  explicitly to `0x2D`, while the transitions into `0x2B`/`0x2C` remain VM-owned.",
        "- **Strong:** state `0x2A` resolves the current actor and reads `actor+0x18C`; state `0x2C`",
        "  and the state-`0x2D` cleanup path read `actor+0x142`.",
        "- **Strong:** the cleanup path owns a target list at `actor+0x1A9/+0x1AA` and iterates those",
        "  unit indices after consulting the action id at `+0x142`.",
        "- **Proven live:** `+0x18C` preserves Reaction presentation identity while `+0x142` becomes the",
        "  executable carrier action. Counter retains `442` at `+0x18C` and resolves Basic Attack `0`",
        "  at `+0x142`; Dual Wield emits two state-`0x2C` rows for one accepted commit.",
        "- **Proven static:** `0x206421` is the accepted pass-2 commit/cardinality boundary, not the",
        "  final action/target rewrite site. RVA `0x2063BD` occurs earlier, after the selector has",
        "  materialized the complete unit order and before actor construction; replacement and source",
        "  retargeting bind to that order, while state `0x2C` audits delivered strike transactions.",
        "",
    ]
    return "\n".join(lines), anchors_ok and state_targets_ok


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-reaction-execution-analysis.md"
    report, ok = render_report(args.exe, output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all queued-Reaction execution checks PASS" if ok else "one or more queued-Reaction execution checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
