#!/usr/bin/env python3
"""Validate the current-build native Reaction-window completion convergence."""
from __future__ import annotations

import argparse
import hashlib
import time
from dataclasses import dataclass
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_64, Cs

import analyze_dcl_calc_provenance as provenance
import analyze_dcl_reaction_dispatch as dispatch


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = dispatch.DEFAULT_EXE
REACTION_QUEUE_RVA = 0x206344
POST_CHAIN_CLEANUP_RVA = 0x206050
STATE_2F_HANDLER_RVA = 0x20CFEC
TRACE_HANDLER_RVA = 0xD90CDD2
WINDOW_COMPLETE_RVA = 0xD90CFA2
RESUME_OWNER_RVA = 0x205F28
BATTLE_STATE_RVA = 0xC6B1CC


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected: str
    meaning: str


ANCHORS = (
    Anchor("dispatcher-state-2f", 0x212AC1, "E8 26 A5 FF FF", "state 0x2F calls its native handler thunk"),
    Anchor("state-2f-trace-thunk", STATE_2F_HANDLER_RVA, "E9 E1 FD 6F 0D", "the thunk enters the complete state-0x2F trace handler"),
    Anchor("queue-call", 0xD90CF99, "E8 A6 93 8F F2", "the action cleanup scans the shared native action/Reaction queue"),
    Anchor("queue-result-branch", 0xD90CF9E, "85 C0 75 05", "accepted work exits while an empty scan falls through"),
    Anchor("window-complete", WINDOW_COMPLETE_RVA, "E8 A9 90 8F F2", "empty first scan or exhausted chain enters post-chain cleanup"),
    Anchor("post-chain-thunk", POST_CHAIN_CLEANUP_RVA, "E9 CB D2 5C 0D", "post-chain cleanup enters its trace implementation"),
    Anchor("post-chain-resume", 0xD7D33B5, "E8 6E 2B A3 F2", "post-chain cleanup calls the native state-resume owner"),
    Anchor("resume-state-28", 0xD7D0A81, "C7 05 41 A7 49 F3 28 00 00 00", "the owner advances the battle dispatcher to state 0x28"),
    Anchor("queue-empty-return", 0x2066F7, "33 C0 E9 6F FD FF FF", "an exhausted three-pass queue returns zero"),
    Anchor("queue-accepted-return", 0x20646A, "41 8B C6 48 8B 4D F8", "an accepted queue path returns one"),
)


def _hex(raw: bytes) -> str:
    return " ".join(f"{byte:02X}" for byte in raw)


def rel32_target(pe: pefile.PE, raw: bytes, rva: int, opcode: int) -> int | None:
    encoded = dispatch.rva_bytes(pe, raw, rva, 5)
    if len(encoded) != 5 or encoded[0] != opcode:
        return None
    return rva + 5 + int.from_bytes(encoded[1:], "little", signed=True)


def render_report(exe: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    md = Cs(CS_ARCH_X86, CS_MODE_64)

    rows: list[str] = []
    anchors_ok = True
    for anchor in ANCHORS:
        expected = bytes.fromhex(anchor.expected)
        actual = dispatch.rva_bytes(pe, raw, anchor.rva, len(expected))
        passed = actual == expected
        anchors_ok &= passed
        rows.append(
            f"| `{anchor.name}` | `0x{anchor.rva:X}` | "
            f"{'PASS' if passed else f'FAIL (`{_hex(actual)}`)'} | {anchor.meaning} |"
        )

    edges = (
        ("state-0x2F handler", 0x212AC1, 0xE8, STATE_2F_HANDLER_RVA),
        ("state-0x2F trace thunk", STATE_2F_HANDLER_RVA, 0xE9, TRACE_HANDLER_RVA),
        ("queue scan", 0xD90CF99, 0xE8, REACTION_QUEUE_RVA),
        ("empty-chain cleanup", WINDOW_COMPLETE_RVA, 0xE8, POST_CHAIN_CLEANUP_RVA),
        ("post-chain trace thunk", POST_CHAIN_CLEANUP_RVA, 0xE9, 0xD7D3320),
        ("post-chain resume owner", 0xD7D33B5, 0xE8, RESUME_OWNER_RVA),
        ("resume-owner trace thunk", RESUME_OWNER_RVA, 0xE9, 0xD7D0A70),
    )
    edge_rows: list[str] = []
    edges_ok = True
    for name, caller, opcode, expected in edges:
        actual = rel32_target(pe, raw, caller, opcode)
        passed = actual == expected
        edges_ok &= passed
        edge_rows.append(
            f"| {name} | `0x{caller:X}` | "
            f"{'none' if actual is None else f'`0x{actual:X}`'} | `0x{expected:X}` | "
            f"{'PASS' if passed else 'FAIL'} |"
        )

    queue_callers = provenance.all_direct_callers(pe, raw, REACTION_QUEUE_RVA)
    cleanup_callers = provenance.all_direct_callers(pe, raw, POST_CHAIN_CLEANUP_RVA)
    graph_ok = queue_callers == [0x2121F7, 0xD90CF99] and cleanup_callers == [WINDOW_COMPLETE_RVA]

    lines = [
        "# DCL Reaction-window completion analysis",
        "",
        "Generated by `tools/analyze_dcl_reaction_window_completion.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Output: `{output}`",
        "",
        "## Byte anchors",
        "",
        "| Name | RVA | Result | Meaning |",
        "| --- | ---: | --- | --- |",
        *rows,
        "",
        "## Direct edges",
        "",
        "| Edge | Caller | Actual target | Expected target | Result |",
        "| --- | ---: | ---: | ---: | --- |",
        *edge_rows,
        "",
        f"- Queue callers: {', '.join(f'`0x{rva:X}`' for rva in queue_callers)}.",
        f"- Post-chain cleanup callers: {', '.join(f'`0x{rva:X}`' for rva in cleanup_callers)}.",
        f"- Complete caller graph: **{'PASS' if graph_ok else 'FAIL'}**.",
        "",
        "## Native transaction read",
        "",
        "```text",
        "state 0x2F action cleanup",
        "  -> queue 0x206344",
        "     accepted (eax=1) -> state 0x29 and deliver the accepted native action",
        "     empty    (eax=0) -> 0xD90CFA2",
        "  -> post-chain cleanup 0x206050",
        "  -> resume owner 0x205F28",
        "  -> state 0x28",
        "```",
        "",
        "The same state-`0x2F` handler runs after the ordinary outer action and after each delivered",
        "native Reaction. Therefore the first empty scan and the terminal empty scan after one or",
        "more accepted Reactions converge at `0xD90CFA2`. The accepted pass-2 boundary cannot provide",
        "this guarantee because it does not fire for an empty window and can fire several times in a chain.",
        "",
        "At `0xD90CFA2`, `rbx` still owns the current execution actor and `eax == 0`; native actor/list",
        "cleanup and the state-`0x28` write have not run yet. A managed hook may therefore acknowledge",
        "only an already-payment-committed singleton canonical ActionInstance, then settle and retire it.",
        "The actor can be the outer source on an empty first scan or the last reactor after a chain, so",
        "source equality is not a valid completion guard; ownership must come from the pending canonical",
        "ledger ticket and battle generation.",
        "",
        f"Battle-state global: `0x{BATTLE_STATE_RVA:X}`. The boundary is static-proven and remains live-gated.",
        "",
        "## Disassembly windows",
        "",
        "### State-0x2F dispatch",
        "",
        *dispatch.disassembly(md, pe, raw, 0x212A98, 0x38),
        "",
        "### Action cleanup and empty-queue convergence",
        "",
        *dispatch.disassembly(md, pe, raw, 0xD90CF79, 0x3E),
        "",
        "### Post-chain cleanup and state resume",
        "",
        *dispatch.disassembly(md, pe, raw, 0xD7D3320, 0xC8),
        "",
        *dispatch.disassembly(md, pe, raw, 0xD7D0A70, 0x28),
        "",
    ]
    return "\n".join(lines), anchors_ok and edges_ok and graph_ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()
    if not args.exe.exists():
        raise SystemExit(f"executable not found: {args.exe}")
    output = Path("(check-only)") if args.check_only else (
        args.output or ROOT / "work" / f"{int(time.time())}-dcl-reaction-window-completion-analysis.md"
    )
    report, ok = render_report(args.exe, output)
    if not args.check_only:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(report, encoding="utf-8", newline="\n")
        print(f"wrote {output}")
    print("all Reaction-window completion anchors PASS" if ok else "Reaction-window completion analysis FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
