#!/usr/bin/env python3
"""Fail closed on the guarded post-materialization Reaction order rewrite."""
from __future__ import annotations

import argparse
import time
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MOD = ROOT / "codemod" / "fftivc.generic.chronicle.codemod" / "Mod.cs"
DEFAULT_VALIDATOR = ROOT / "codemod" / "fftivc.generic.chronicle.codemod" / "RuntimeSettingsValidator.cs"


@dataclass(frozen=True)
class Anchor:
    name: str
    owner: str
    needle: str
    meaning: str


ANCHORS = (
    Anchor("settings-switch", "mod", "public bool DclReactionOrderRewriteEnabled { get; set; } = false;", "controller is disabled by default"),
    Anchor("settings-log-only", "mod", "public bool DclReactionOrderRewriteLogOnly { get; set; } = true;", "writes are log-only by default"),
    Anchor("shared-byte-guard", "validator", "accepted-order rewrite requires DclReactionMaterializationProbeEnabled", "controller requires the exact-byte-guarded audit hook"),
    Anchor("carrier-range", "validator", "carrier id must be a native Reaction id in 422..453", "one exact native carrier owns each rewrite"),
    Anchor("bounded-writes", "validator", "maximum accepted-order writes must be within 1..32", "live writes are bounded"),
    Anchor("live-original-guards", "validator", "live accepted-order writes require exact expected native action type and ability id guards", "live mutation cannot wildcard the native order shape"),
    Anchor("exact-carrier", "mod", '$"cmp word [rbp-2Eh], {carrierId}"', "exact Reaction id gates the controller"),
    Anchor("selected-lower-bound", "mod", '"cmp r9d, 0"', "negative selected indices fail closed"),
    Anchor("selected-upper-bound", "mod", '"cmp r9d, 20"', "selected unit-table indices stay within the native table"),
    Anchor("original-type-guard", "mod", '$"cmp byte [rcx+1], {_settings.DclReactionOrderRewriteExpectedActionType}"', "optional native type guard precedes writes"),
    Anchor("original-id-guard", "mod", '$"cmp word [rcx+2], {_settings.DclReactionOrderRewriteExpectedAbilityId}"', "optional native payload guard precedes writes"),
    Anchor("source-upper-bound", "mod", '"cmp edx, 20"', "incoming source indices stay within the native table"),
    Anchor("write-cap-check", "mod", '$"cmp ebx, {maxWrites}"', "the live write counter is checked before mutation"),
    Anchor("type-write", "mod", '$"mov byte [rcx+1], {_settings.DclReactionOrderRewriteActionType}"', "executable order type is replaced"),
    Anchor("payload-write", "mod", '$"mov word [rcx+2], {_settings.DclReactionOrderRewriteAbilityId}"', "executable payload is replaced"),
    Anchor("target-mode-write", "mod", '"mov byte [rcx+0Ah], 5"', "retarget preserves unit/tile delivery mode"),
    Anchor("target-index-write", "mod", '"mov byte [rcx+0Bh], dl"', "incoming source becomes the target unit index"),
    Anchor("target-x-write", "mod", '"movzx ebx, byte [rdi+4Fh]"', "source x is copied to order+0x0C"),
    Anchor("target-layer-write", "mod", '"movzx ebx, byte [rdi+51h]"', "source layer bit is copied to order+0x0E"),
    Anchor("target-y-write", "mod", '"movzx ebx, byte [rdi+50h]"', "source y is copied to order+0x10"),
    Anchor("write-count", "mod", '$"add dword [rax+{RM_REWRITE_WRITE_COUNT}], 1"', "successful writes consume the bounded counter"),
    Anchor("audit-original", "mod", '$"mov dword [rsi+{RM_ORIGINAL_HEAD}], r8d"', "the pre-rewrite order head is audited"),
    Anchor("audit-final", "mod", '$"mov qword [rsi+{RM_ORDER_00}], rbx"', "the final complete order is audited"),
    Anchor("preserve-rdi", "mod", '"push rdi"', "coordinate-copy scratch register is preserved"),
    Anchor("restore-rdi", "mod", '"pop rdi"', "coordinate-copy scratch register is restored"),
)


def analyze(mod_text: str, validator_text: str) -> list[tuple[Anchor, bool]]:
    owners = {"mod": mod_text, "validator": validator_text}
    return [(anchor, anchor.needle in owners[anchor.owner]) for anchor in ANCHORS]


def render(mod_path: Path, validator_path: Path, output: Path) -> tuple[str, bool]:
    mod_text = mod_path.read_text(encoding="utf-8")
    validator_text = validator_path.read_text(encoding="utf-8")
    results = analyze(mod_text, validator_text)
    ok = all(passed for _, passed in results)
    rows = [
        f"| `{anchor.name}` | {'PASS' if passed else 'FAIL'} | {anchor.meaning} |"
        for anchor, passed in results
    ]
    report = "\n".join([
        "# DCL Reaction accepted-order rewrite analysis",
        "",
        "Generated by `tools/analyze_dcl_reaction_order_rewrite.py`.",
        "",
        f"- Runtime source: `{mod_path}`",
        f"- Validator source: `{validator_path}`",
        f"- Output: `{output}`",
        "",
        "| Anchor | Result | Contract |",
        "| --- | --- | --- |",
        *rows,
        "",
        "## Contract",
        "",
        "The controller runs only at accepted boundary `0x2063BD`. It matches one exact Reaction id,",
        "optionally verifies the carrier's native executable type/payload, and then replaces the order",
        "type/payload and/or its complete source target. Source retarget copies unit index plus x/layer/y",
        "coordinates from native unit offsets `+0x4F/+0x51.bit7/+0x50`. Invalid indices, native-order",
        "mismatch, or an exhausted write cap leave the order unchanged and produce an audited status.",
        "",
        f"Overall offline gate: **{'PASS' if ok else 'FAIL'}**.",
        "",
    ])
    return report, ok


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mod", type=Path, default=DEFAULT_MOD)
    parser.add_argument("--validator", type=Path, default=DEFAULT_VALIDATOR)
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-reaction-order-rewrite-analysis.md"
    report, ok = render(args.mod, args.validator, output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("reaction accepted-order rewrite PASS" if ok else "reaction accepted-order rewrite FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
