#!/usr/bin/env python3
"""Verify the current-build real-code Regenerate reaction staging window."""
from __future__ import annotations

import argparse
import hashlib
import time
from pathlib import Path

import pefile


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = Path(
    r"D:/SteamLibrary/steamapps/common/FINAL FANTASY TACTICS - The Ivalice Chronicles/FFT_enhanced.exe"
)

ANCHORS = (
    (0x30B7EF, "48 8B 0D 72 F7 55 01 48 8B 1D 73 F7 55 01", "loads reaction unit and unit+0x1BE result record"),
    (0x30B7FD, "8A 91 94 00 00 00", "loads reaction-set byte unit+0x94 into DL"),
    (0x30B8E0, "41 B2 02", "retains bit 0x02 as the Regenerate reaction bit"),
    (0x30BA8E, "41 84 D2 74 14", "tests unit+0x94 bit 0x02"),
    (0x30BA93, "40 38 7B 27 0F 8D A3 00 00 00", "requires signed result flag < 0, i.e. HP-damage bit 0x80"),
    (0x30BA9D, "B8 AC 01 00 00", "selects exact reaction id 428"),
    (0x30BB34, "66 89 43 10", "stages id 428 at result+0x10 = unit+0x1CE"),
    (0x30BB38, "0F B7 43 06 66 89 43 28", "copies staged HP debit to unit+0x1E6 reaction payload"),
)


def rva_bytes(pe: pefile.PE, raw: bytes, rva: int, size: int) -> bytes:
    return raw[pe.get_offset_from_rva(rva) : pe.get_offset_from_rva(rva) + size]


def render(exe: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    checks = []
    for rva, expected_hex, meaning in ANCHORS:
        expected = bytes.fromhex(expected_hex)
        checks.append((rva, meaning, rva_bytes(pe, raw, rva, len(expected)) == expected))
    ok = all(passed for _, _, passed in checks)

    lines = [
        "# DCL native Regenerator staging analysis",
        "",
        "Generated by `tools/analyze_dcl_regenerator.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Output: `{output}`",
        "",
        "## Anchor verification",
        "",
        "| RVA | Result | Meaning |",
        "| ---: | --- | --- |",
    ]
    for rva, meaning, passed in checks:
        lines.append(f"| `0x{rva:X}` | {'PASS' if passed else 'FAIL'} | {meaning} |")
    lines.extend(
        [
            "",
            "## Native contract and boundary",
            "",
            "The hookable staging branch selects Regenerate `428` when reaction bit",
            "`unit+0x94 & 0x02` is present and result flag `unit+0x1E5` has HP-damage bit `0x80`.",
            "It stages id `428` at `unit+0x1CE` and copies the staged HP debit into `unit+0x1E6`.",
            "There is no explicit current-HP/survivor test inside this branch; any lethal-hit rejection",
            "or actual Regen status delivery belongs to surrounding/VM-owned processing.",
            "",
            "The final White Mage Regenerator trigger is therefore near-native for a landed HP-damage",
            "result, but survivor timing remains a bounded live gate. The DCL Caution chance can reuse",
            "the exact-id Brave gate without replacing the effect if live proof confirms that lethal",
            "hits do not leave an invalid Regen reaction behind.",
            "",
        ]
    )
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-regenerator-analysis.md"
    report, ok = render(args.exe, output)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all Regenerator checks PASS" if ok else "one or more Regenerator checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
