#!/usr/bin/env python3
"""Verify how the current build selects Nature's Wrath terrain payloads and riders."""
from __future__ import annotations

import argparse
import csv
import hashlib
import time
from collections import Counter
from pathlib import Path

import pefile


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = Path(
    r"D:/SteamLibrary/steamapps/common/FINAL FANTASY TACTICS - The Ivalice Chronicles/FFT_enhanced.exe"
)
DEFAULT_CATALOG = ROOT / "work" / "wotl_ability_action_baseline.csv"
TERRAIN_TABLE_RVA = 0x67F750
EXPECTED_TERRAIN_PAYLOADS = bytes.fromhex(
    "7E 86 86 80 80 87 82 81 7E 85 85 85 82 87 7F 7F "
    "7F 7F 89 7E 84 81 88 81 88 83 86 83 84 84 83 84 "
    "83 88 81 83 80 84 83 80 84 89 83 83 81 7F 83 83 "
    "83 83 83 83 83 83 83 83 83 83 83 83 83 83 83 83"
)

ANCHORS = (
    (0x2830D0, "0F B6 4B 50", "loads reactor Y"),
    (0x2830DB, "0F B6 05 88 7C 9E 00", "loads map width from RVA 0xC6AD6A"),
    (0x2830E5, "0F B6 43 51 C1 E8 07 C1 E0 08", "adds reactor map-level bit as tile-plane 0x100"),
    (0x2830F1, "0F B6 43 4F 03 C8", "adds reactor X"),
    (0x2830F7, "0F B6 8C CA B0 DC D8 00 83 E1 3F", "reads tile byte 0 and masks terrain id to 0..63"),
    (0x283105, "44 0F B6 84 11 50 F7 67 00", "maps terrain id through the 64-byte payload table"),
    (0x28310E, "41 8D 51 11", "selects typed-order kind 0x11 for Geomancy"),
)


def load_catalog(path: Path) -> dict[int, dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return {int(row["id_dec"]): row for row in csv.DictReader(handle)}


def rva_bytes(pe: pefile.PE, raw: bytes, rva: int, size: int) -> bytes:
    return raw[pe.get_offset_from_rva(rva) : pe.get_offset_from_rva(rva) + size]


def render(exe: Path, catalog_path: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    catalog = load_catalog(catalog_path)

    checks: list[tuple[int, str, str, bool]] = []
    for rva, expected_hex, meaning in ANCHORS:
        expected = bytes.fromhex(expected_hex)
        checks.append((rva, expected_hex, meaning, rva_bytes(pe, raw, rva, len(expected)) == expected))
    actual_table = rva_bytes(pe, raw, TERRAIN_TABLE_RVA, 64)
    table_ok = actual_table == EXPECTED_TERRAIN_PAYLOADS
    ids_ok = all(126 <= value <= 137 and value in catalog for value in actual_table)
    ok = all(passed for _, _, _, passed in checks) and table_ok and ids_ok

    counts = Counter(actual_table)
    lines = [
        "# DCL native Nature's Wrath mechanism analysis",
        "",
        "Generated by `tools/analyze_dcl_natures_wrath.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Ability catalog: `{catalog_path}`",
        f"- Output: `{output}`",
        "",
        "## Anchor verification",
        "",
        "| RVA | Result | Meaning |",
        "| ---: | --- | --- |",
    ]
    for rva, _, meaning, passed in checks:
        lines.append(f"| `0x{rva:X}` | {'PASS' if passed else 'FAIL'} | {meaning} |")
    lines.extend(
        [
            f"| `0x{TERRAIN_TABLE_RVA:X}` | {'PASS' if table_ok else 'FAIL'} | exact 64-byte terrain-to-action table |",
            "",
            "## Terrain payload catalog",
            "",
            "| Action id | Ability | Terrain ids using it | Native status rider |",
            "| ---: | --- | ---: | --- |",
        ]
    )
    for ability_id in sorted(counts):
        row = catalog[ability_id]
        terrain_ids = ", ".join(str(index) for index, value in enumerate(actual_table) if value == ability_id)
        status = row.get("inflict_statuses") or "none"
        lines.append(
            f"| `{ability_id}` | {row.get('name_ivc') or row.get('name_wotl') or '(unnamed)'} | "
            f"{terrain_ids} | {status} |"
        )

    lines.extend(
        [
            "",
            "## Native contract",
            "",
            "The pass-2 Nature's Wrath branch computes `tileIndex = level*256 + y*mapWidth + x` from",
            "the **reactor's own tile**, reads `tileTable[tileIndex].terrainType & 0x3F`, maps that",
            "terrain id through the 64-byte table at RVA `0x67F750`, and stages the resulting normal",
            "Geomancy ability id `126..137` as a typed order of kind `0x11`.",
            "",
            "This is not a rider-free special damage action. It reuses the ordinary Geomancy payload,",
            "whose ability data carries its normal status rider. The final DCL Nature's Wrath therefore",
            "already has native own-tile terrain selection, but its `no status rider, no Scar` rule needs",
            "reaction-aware status suppression. Global data removal would also remove the authored rider",
            "from active Geomancy and is not equivalent.",
            "",
            "## Implementation boundary",
            "",
            "Damage can keep the selected payload id and flow through the existing per-ability formula",
            "map. Status suppression can reuse the durable DCL status-output controls only after action",
            "provenance distinguishes a Nature's Wrath reaction execution from an ordinary cast of the",
            "same payload. Cadence remains a separate once-per-attacker-action commit concern.",
            "",
        ]
    )
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-natures-wrath-analysis.md"
    report, ok = render(args.exe, args.catalog, output)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all Nature's Wrath checks PASS" if ok else "one or more Nature's Wrath checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
