#!/usr/bin/env python3
"""Verify Dragon's Gift's species gate, paired numeric transaction, and cancel rider."""
from __future__ import annotations

import argparse
import csv
import hashlib
import struct
import time
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_64, Cs

import analyze_dcl_reaction_dispatch as dispatch
import build_neuter_data as neuter


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = dispatch.DEFAULT_EXE
DEFAULT_CATALOG = ROOT / "work" / "wotl_ability_action_baseline.csv"
DISPATCH_TABLE_RVA = 0x682BC8
FORMULA_ID = 0x5B
HANDLER_RVA = 0x309210
EXPECTED_STATUSES = (
    "Darkness", "Confusion", "Silence", "Oil", "Berserk", "Frog",
    "Poison", "Stop", "Sleep", "DontMove", "DontAct",
)
STATUS_BITS = (
    (1, 0x20, "Darkness"), (1, 0x10, "Confusion"), (1, 0x08, "Silence"),
    (2, 0x80, "Oil"), (2, 0x08, "Berserk"), (2, 0x02, "Frog"),
    (3, 0x80, "Poison"), (3, 0x02, "Stop"), (4, 0x10, "Sleep"),
    (4, 0x08, "DontMove"), (4, 0x04, "DontAct"),
)
HANDLER_BYTES = bytes.fromhex(
    "48 83 EC 28 48 8B 05 4D 1D 56 01 4C 8B 05 4E 1D 56 01 8A 88 8E 01 00 00 "
    "33 C0 80 E9 0F 80 F9 01 76 0D 41 88 00 41 C6 40 02 07 66 41 89 40 2C "
    "41 38 00 74 39 48 8B 05 2D 1D 56 01 0F B7 48 32 B8 CD CC CC CC F7 E1 "
    "48 8B 05 03 1D 56 01 C1 EA 02 66 89 50 06 66 03 D2 C6 40 27 80 C6 00 01 "
    "66 41 89 50 08 41 C6 40 27 40 E8 C3 D6 FF FF 48 83 C4 28 C3"
)


def dispatch_target(pe: pefile.PE, raw: bytes) -> int:
    entry = dispatch.rva_bytes(pe, raw, DISPATCH_TABLE_RVA + FORMULA_ID * 8, 8)
    return struct.unpack("<Q", entry)[0] - pe.OPTIONAL_HEADER.ImageBase


def load_catalog(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return [row for row in csv.DictReader(handle) if row.get("formula_hex", "").upper() == "0X5B"]


def render(exe: Path, catalog_path: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    md = Cs(CS_ARCH_X86, CS_MODE_64)
    target = dispatch_target(pe, raw)
    actual_handler = dispatch.rva_bytes(pe, raw, HANDLER_RVA, len(HANDLER_BYTES))
    rows = load_catalog(catalog_path)
    catalog_ok = (
        len(rows) == 1
        and rows[0]["id_dec"] == "252"
        and rows[0]["inflict_status_mode"] == "Cancel"
        and tuple(rows[0]["inflict_statuses"].split("|")) == EXPECTED_STATUSES
        and rows[0].get("aoe") == "0"
    )
    allowlist_ok = neuter.DCL_SUPPORT_STATUS_RIDER_ABILITY_IDS == (252,)
    handler_ok = actual_handler == HANDLER_BYTES
    dispatch_ok = target == HANDLER_RVA

    lines = [
        "# DCL Dragon's Gift transaction analysis", "",
        "Generated by `tools/analyze_dcl_dragon_gift.py`.", "",
        "## Inputs", "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Ability catalog: `{catalog_path}`",
        f"- Output: `{output}`", "",
        "## Mechanical checks", "",
        f"- Formula `0x5B` dispatches to `0x{HANDLER_RVA:X}`: **{'PASS' if dispatch_ok else 'FAIL'}** (actual `0x{target:X}`).",
        f"- The complete handler byte window matches the current build: **{'PASS' if handler_ok else 'FAIL'}**.",
        f"- Formula `0x5B` has exactly ability 252, Cancel mode, single target, and the expected 11 statuses: **{'PASS' if catalog_ok else 'FAIL'}**.",
        f"- The support-rider neuter allowlist contains exactly ability 252: **{'PASS' if allowlist_ok else 'FAIL'}**.",
        "", "## Static interpretation", "",
        "- **Strong:** the handler accepts only monster graphic-set ids 15 and 16; all other targets return with an inactive result.",
        "- **Strong:** an eligible target receives a target HP credit at `result+0x06` and the source receives twice that amount as an HP debit at the paired result `+0x08`.",
        "- **Strong:** the eligible path unconditionally calls the common status finalizer after staging both numeric records.",
        "- Clearing only ability 252's `InflictStatus` therefore preserves the Dragon eligibility gate and paired heal/sacrifice transaction while the managed packet owns every cancel bit.",
        "", "## Managed remove packet", "",
        "| Packet byte | Mask | Status |", "| ---: | ---: | --- |",
        *(f"| {byte_index} | `0x{mask:02X}` | {name} |" for byte_index, mask, name in STATUS_BITS),
        "", "## Handler disassembly", "",
        *dispatch.disassembly(md, pe, raw, HANDLER_RVA, len(HANDLER_BYTES)), "",
    ]
    return "\n".join(lines), dispatch_ok and handler_ok and catalog_ok and allowlist_ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()
    if not args.exe.exists():
        raise SystemExit(f"executable not found: {args.exe}")
    if not args.catalog.exists():
        raise SystemExit(f"ability catalog not found: {args.catalog}")
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-dragon-gift-analysis.md"
    report, ok = render(args.exe, args.catalog, output)
    if not args.check_only:
        output.write_text(report, encoding="utf-8", newline="\n")
        print(f"wrote {output}")
    print("all Dragon's Gift checks PASS" if ok else "one or more Dragon's Gift checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
