#!/usr/bin/env python3
"""Verify the current-build scope used by DCL reaction-chance virtualization."""
from __future__ import annotations

import argparse
import hashlib
import time
from dataclasses import dataclass
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_64, Cs


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = Path(
    r"D:/SteamLibrary/steamapps/common/FINAL FANTASY TACTICS - The Ivalice Chronicles/FFT_enhanced.exe"
)
FUNCTION_ENTRY_RVA = 0x3099AC
RESTORE_HOOK_RVA = 0x309FA1
FUNCTION_RET_RVA = 0x309FB0
FUNCTION_SIZE = FUNCTION_RET_RVA - FUNCTION_ENTRY_RVA + 1


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected: str
    meaning: str


ANCHORS = (
    Anchor(
        "compute-action-result-entry",
        FUNCTION_ENTRY_RVA,
        "48 89 5C 24 18 55 56 57",
        "guarded calc-entry hook shared by the DCL pipeline",
    ),
    Anchor(
        "reaction-restore-epilogue",
        RESTORE_HOOK_RVA,
        "48 83 C4 40 41 5F 41 5E",
        "guarded epilogue hook that restores the real Brave byte",
    ),
    Anchor(
        "compute-action-result-return",
        FUNCTION_RET_RVA,
        "C3",
        "the sole linear-disassembly return in computeActionResult",
    ),
    Anchor("reaction-gate-r1", 0x30BDEE, "E8 75 D0 F6 FF", "real-code gate; exact id is held in r11d"),
    Anchor("reaction-gate-r2", 0x30BE44, "E8 1F D0 F6 FF", "real-code gate; exact id is held in ebx"),
    Anchor("reaction-gate-r3", 0x30BE9A, "E8 C9 CF F6 FF", "real-code gate; exact id is held in ebx"),
    Anchor("reaction-gate-r4", 0x30BEDA, "E8 89 CF F6 FF", "real-code gate; exact id is held in r11d"),
    Anchor(
        "reaction-order-record-id",
        0x282F1E,
        "66 89 77 02",
        "stages the exact Reaction id at order-record+2 before native reaction evaluation",
    ),
    Anchor(
        "reaction-eval-global-id",
        0x282F22,
        "66 89 35 C7 80 5E 01",
        "mirrors the same exact Reaction id into the reaction-evaluation global",
    ),
    Anchor(
        "reaction-formula-global-read",
        0x3095EF,
        "48 0F BF 0D F9 19 56 01",
        "native reaction formula dispatch reads the exact evaluation id",
    ),
    Anchor(
        "reaction-incoming-source-read",
        0x282FCB,
        "48 63 05 22 80 5E 01",
        "Counter staging reads the preserved incoming actor index from dword[0x14186AFF4]",
    ),
    Anchor(
        "reaction-record-source-id",
        0x282FD5,
        "88 47 0B",
        "Counter staging writes that incoming actor index into reaction order-record+0xB",
    ),
)


def parse_hex(value: str) -> bytes:
    return bytes.fromhex(value)


def hex_bytes(value: bytes) -> str:
    return " ".join(f"{byte:02X}" for byte in value)


def rva_bytes(pe: pefile.PE, raw: bytes, rva: int, size: int) -> bytes:
    offset = pe.get_offset_from_rva(rva)
    return raw[offset : offset + size]


def render_report(exe: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    image_base = pe.OPTIONAL_HEADER.ImageBase

    anchor_rows: list[str] = []
    anchors_ok = True
    for anchor in ANCHORS:
        expected = parse_hex(anchor.expected)
        actual = rva_bytes(pe, raw, anchor.rva, len(expected))
        ok = actual == expected
        anchors_ok &= ok
        status = "PASS" if ok else f"FAIL (`{hex_bytes(actual)}`)"
        anchor_rows.append(
            f"| `{anchor.name}` | `0x{anchor.rva:X}` | {status} | `{anchor.expected}` | {anchor.meaning} |"
        )

    md = Cs(CS_ARCH_X86, CS_MODE_64)
    body = rva_bytes(pe, raw, FUNCTION_ENTRY_RVA, FUNCTION_SIZE)
    instructions = list(md.disasm(body, image_base + FUNCTION_ENTRY_RVA))
    contiguous = bool(instructions) and instructions[-1].address + instructions[-1].size == image_base + FUNCTION_RET_RVA + 1
    ret_rvas = [
        instruction.address - image_base
        for instruction in instructions
        if instruction.mnemonic.startswith("ret")
    ]
    sole_ret_ok = contiguous and ret_rvas == [FUNCTION_RET_RVA]

    epilogue = rva_bytes(pe, raw, RESTORE_HOOK_RVA, FUNCTION_RET_RVA - RESTORE_HOOK_RVA + 1)
    epilogue_rows = ["```text"]
    for instruction in md.disasm(epilogue, image_base + RESTORE_HOOK_RVA):
        rva = instruction.address - image_base
        rendered = f"{instruction.mnemonic} {instruction.op_str}".strip()
        epilogue_rows.append(f"{rva:08X}: {hex_bytes(instruction.bytes):<28} {rendered}")
    epilogue_rows.append("```")

    lines = [
        "# DCL Reaction Virtualization Scope Analysis",
        "",
        "Generated by `tools/analyze_dcl_reaction_scope.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- PE image base: `0x{image_base:X}`",
        f"- Output: `{output}`",
        "",
        "## Byte anchors",
        "",
        "| Name | RVA | Result | Expected bytes | Meaning |",
        "| --- | ---: | --- | --- | --- |",
        *anchor_rows,
        "",
        "## Function-boundary check",
        "",
        f"- Linear disassembly: RVA `0x{FUNCTION_ENTRY_RVA:X}` through `0x{FUNCTION_RET_RVA:X}`.",
        f"- Decoding reaches the expected final byte without a gap: **{'PASS' if contiguous else 'FAIL'}**.",
        f"- Return instructions: {', '.join(f'`0x{rva:X}`' for rva in ret_rvas) or 'none'}.",
        f"- Sole guarded return at `0x{FUNCTION_RET_RVA:X}`: **{'PASS' if sole_ret_ok else 'FAIL'}**.",
        "",
        "## Static interpretation",
        "",
        "- **Strong:** `computeActionResult` has one linearly decoded return in the current executable.",
        "  Installing the restore callback at the guarded epilogue covers every ordinary return path",
        "  for explicitly marked VM-internal avoidance reactions.",
        "- **Proven:** live reaction tests show that the engine consumes `unit+0x2B` as its native",
        "  Brave-percent gate and that the reaction-evaluation global carries ids such as Mana Shield",
        "  and Shirahadori while those reactions are evaluated.",
        "- **Strong:** current-build reaction staging writes the exact id to `orderRecord+2` and the",
        "  reaction-evaluation global before native formula dispatch reads it. Calc-entry already receives",
        "  that order-record pointer, so VM chance virtualization can classify equipped or innate reactions",
        "  by the actual evaluation id rather than by the defender's equipped slot.",
        "- **Strong:** the four real-code roll gates retain the exact evaluated Reaction id in `r11d`",
        "  or `ebx`. Their managed shim can replace only the chance while preserving native effects/RNG.",
        "- **Strong:** native Counter staging reads `dword[0x14186AFF4]` as the incoming actor index,",
        "  selects that unit, and writes its index and coordinates into the reaction order record.",
        "  Reaction formulas can therefore receive the original source plus action type/id from the",
        "  fresh per-target calc cache or the source unit's `+0x1A1/+0x1A2` order record.",
        "- **Strong:** substituting `unit+0x2B` after the DCL hit/forecast callback and restoring it at",
        "  the sole exit gives VM-internal avoidance such as Shirahadori an authored chance while",
        "  leaving the permanent Brave trait, native reaction effect, and native RNG ownership unchanged.",
        "- No persistent Brave write is required: a thread-local frame restores the byte at the guarded",
        "  sole epilogue even when the evaluated Reaction is innate or derived.",
        "",
        "## Restore epilogue",
        "",
        *epilogue_rows,
        "",
    ]
    return "\n".join(lines), anchors_ok and sole_ret_ok


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-reaction-scope-analysis.md"
    report, ok = render_report(args.exe, output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report, encoding="utf-8")
    print(f"wrote {output}")
    print("all anchors and scope checks PASS" if ok else "one or more anchors/scope checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
