#!/usr/bin/env python3
"""Verify the native outer-action TargetBatch and repeat boundaries used by canonical DCL admission."""
from __future__ import annotations

import argparse
import hashlib
import time
from dataclasses import dataclass
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_64, Cs


ROOT = Path(__file__).resolve().parents[1]
GAME_DIRS = (
    Path(r"D:/SteamLibrary/steamapps/common/FINAL FANTASY TACTICS - The Ivalice Chronicles"),
    Path(r"C:/Program Files (x86)/Steam/steamapps/common/FINAL FANTASY TACTICS - The Ivalice Chronicles"),
)
DEFAULT_EXE = next((path / "FFT_enhanced.exe" for path in GAME_DIRS if (path / "FFT_enhanced.exe").exists()),
                   GAME_DIRS[0] / "FFT_enhanced.exe")


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected: str
    meaning: str


ANCHORS = (
    Anchor("outer-sweep-entry", 0x281CE8,
           "48 89 5C 24 18 55 56 57 41 54 41 55 41 56 41 57",
           "entry of the one result-producer invocation that owns the target sweep"),
    Anchor("target-list-builder", 0x281EBC,
           "49 8B D6 48 8D 4D D8 E8 8C 08 00 00",
           "passes the source unit and local 21-byte target list to selector 0x282754"),
    Anchor("selected-unit-read", 0x281E36,
           "0F B6 15 55 E9 52 00 80 FA 15",
           "reads selected unit byte RVA 0x7B0792 before target-batch expansion"),
    Anchor("source-order-record", 0x281ED6,
           "48 8D 05 23 E1 D7 FF 4C 8D B0 80 3E 85 01 4C 03 F6 49 8B CE",
           "derives source unit+0x1A0 and passes that complete order record to the pre-sweep helper"),
    Anchor("batch-ready", 0x281EF7,
           "49 8B DD 8A 54 1D D8 80 FA FF 74 0F",
           "the complete local target list exists before the first target calculation"),
    Anchor("per-target-calc", 0x281F0D,
           "E8 9A 7A 08 00 48 FF C3 48 83 FB 15 7C DF",
           "calls computeActionResult and advances the 21-entry target loop"),
    Anchor("repeat-continuation", 0x2821EC,
           "8A 05 71 E5 52 00 02 C3 3A 05 68 E5 52 00 88 05 63 E5 52 00 0F 92 C0 88 47 18",
           "increments repeat index, compares repeat count, and publishes the continuation flag"),
    Anchor("outer-sweep-epilogue", 0x282219,
           "48 8B 9C 24 A0 00 00 00 48 83 C4 50 41 5F 41 5E 41 5D 41 5C 5F 5E 5D C3",
           "sole normal epilogue after target calculation and continuation publication"),
)


def rva_bytes(pe: pefile.PE, raw: bytes, rva: int, size: int) -> bytes:
    offset = pe.get_offset_from_rva(rva)
    return raw[offset:offset + size]


def disassembly(md: Cs, pe: pefile.PE, raw: bytes, image_base: int, rva: int, size: int) -> list[str]:
    code = rva_bytes(pe, raw, rva, size)
    return [f"- `0x{ins.address - image_base:X}`: `{ins.mnemonic} {ins.op_str}`"
            for ins in md.disasm(code, image_base + rva)]


def exception_owner(pe: pefile.PE, rva: int) -> tuple[int, int] | None:
    pe.parse_data_directories(directories=[pefile.DIRECTORY_ENTRY["IMAGE_DIRECTORY_ENTRY_EXCEPTION"]])
    for entry in pe.DIRECTORY_ENTRY_EXCEPTION:
        if entry.struct.BeginAddress <= rva < entry.struct.EndAddress:
            return entry.struct.BeginAddress, entry.struct.EndAddress
    return None


def render(exe: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=False)
    image_base = pe.OPTIONAL_HEADER.ImageBase
    rows: list[str] = []
    ok = True
    for anchor in ANCHORS:
        expected = bytes.fromhex(anchor.expected)
        actual = rva_bytes(pe, raw, anchor.rva, len(expected))
        passed = actual == expected
        ok &= passed
        result = "PASS" if passed else "FAIL (`" + " ".join(f"{byte:02X}" for byte in actual) + "`)"
        rows.append(f"| `{anchor.name}` | `0x{anchor.rva:X}` | {result} | `{anchor.expected}` | {anchor.meaning} |")

    owner = exception_owner(pe, 0x281EF7)
    owner_ok = owner == (0x281CE8, 0x282231)
    ok &= owner_ok
    md = Cs(CS_ARCH_X86, CS_MODE_64)
    lines = [
        "# DCL outer-action TargetBatch boundary analysis",
        "",
        "Generated by `tools/analyze_dcl_outer_action_batch.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Output: `{output}`",
        f"- Exception owner: `{f'0x{owner[0]:X}..0x{owner[1]:X}' if owner else 'missing'}` ({'PASS' if owner_ok else 'FAIL'})",
        "",
        "## Byte anchors",
        "",
        "| Name | RVA | Result | Expected bytes | Meaning |",
        "| --- | ---: | --- | --- | --- |",
        *rows,
        "",
        "## TargetBatch preparation and sweep",
        "",
        *disassembly(md, pe, raw, image_base, 0x281EBC, 0x6A),
        "",
        "## Repeat continuation",
        "",
        *disassembly(md, pe, raw, image_base, 0x2821EC, 0x1C),
        "",
        "## Interpretation",
        "",
        "- **Strong:** function `0x281CE8..0x282231` owns one outer result-production sweep.",
        "- **Strong:** selector `0x282754` finishes the local 21-byte target list before `0x281EF7`;",
        "  the following loop skips `0xFF` entries and calls `computeActionResult` once per member.",
        "- **Strong:** `0x281EF7` is therefore an admission boundary for the complete native",
        "  TargetBatch, earlier than every per-target calculation and native result rewrite.",
        "- **Strong:** RVA `0x7B0792` is read immediately before expansion as a selected-unit byte.",
        "  Admission retains it separately from the affected TargetBatch; family-specific policy",
        "  decides whether it is a declared unit target, area center unit, or nonapplicable.",
        "- **Strong:** `0x281ED6..0x281EEA` derives the reusable source `unit+0x1A0` order record.",
        "  Admission snapshots its staged target words as X at `+0x0C`, map level at `+0x0E`, and",
        "  Y at `+0x10`; the tuple is retained separately from selected-unit and affected-batch identity.",
        "- **Strong:** after the complete sweep, `0x2821EC` reads and increments repeat index RVA",
        "  `0x7B0763`, compares repeat count RVA `0x7B0762`, stores the new index, and writes the",
        "  continuation flag. The pre-increment index seen during the sweep is its Strike identity.",
        "- The order-record pointer is not an ActionInstance identity: it is the reusable source-unit",
        "  order record at `unit+0x1A0`. Canonical admission instead owns a monotonic sweep serial and binds",
        "  ordered native repeats to one ActionInstance through exact count/index continuity.",
        "- `RandomFire` remains excluded from canonical admission until the complete repeated target",
        "  sequence is selected by DCL before the first result; native just-in-time selection cannot",
        "  satisfy the normalized TargetBatch snapshot contract.",
        "",
    ]
    return "\n".join(lines), ok


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-outer-action-batch-analysis.md"
    report, ok = render(args.exe, output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all outer-action TargetBatch checks PASS" if ok else "one or more outer-action TargetBatch checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
