#!/usr/bin/env python3
"""Verify the current-build Auto-Potion item selection and inventory-consumption surfaces."""
from __future__ import annotations

import argparse
import csv
import hashlib
import time
from dataclasses import dataclass
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_64, Cs

import analyze_dcl_reaction_dispatch as dispatch


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = dispatch.DEFAULT_EXE
DEFAULT_ITEMS = ROOT / "work" / "item_catalog.csv"
ITEM_LINE_RVA = 0x7154B8
AUTO_POTION_ID = 441


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected: str
    meaning: str


ANCHORS = (
    Anchor("auto-potion-branch", 0x283026, "F6 83 EE 01 00 00 30", "checks reactor unit+0x1EE special inventory flags"),
    Anchor("auto-potion-fallback-item", 0x28302F, "B8 F0 00 00 00", "special path selects item id 240"),
    Anchor("auto-potion-item-table", 0x283039, "48 8D 0D 78 24 49 00", "addresses the three-word Potion-line table"),
    Anchor("auto-potion-inventory-check", 0x28304A, "46 38 BC 02 00 7C 1A 01", "checks inventory count for each listed item id"),
    Anchor("auto-potion-selected-item", 0x283068, "66 89 47 08", "writes selected item id at reactor unit+0x1A8"),
    Anchor("auto-potion-order-type", 0x28306C, "48 8B CF C6 47 01 06", "sets order type 6"),
    Anchor("auto-potion-action-id", 0x28309D, "B9 B9 01 00 00", "selects exact Reaction id 441"),
    Anchor("auto-potion-action-store", 0x2830A2, "66 89 8B A2 01 00 00", "writes 441 to reactor unit+0x1A2"),
    Anchor("item-consume-special-bypass", 0x281684, "F6 86 EE 01 00 00 30", "checks the same unit+0x1EE flags before inventory mutation"),
    Anchor("item-consume-count-read", 0x281692, "43 8A 84 05 00 7C 1A 01", "reads inventory count indexed by selected item id"),
    Anchor("item-consume-decrement", 0x2816B2, "2A CB 43 88 8C 05 00 7C 1A 01", "subtracts the bounded consume amount and writes inventory"),
)


def parse_hex(value: str) -> bytes:
    return bytes.fromhex(value)


def hex_bytes(value: bytes) -> str:
    return " ".join(f"{byte:02X}" for byte in value)


def load_item_names(path: Path) -> dict[int, str]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return {int(row["item_id"]): row["name"] for row in csv.DictReader(handle)}


def render_report(exe: Path, items_path: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    md = Cs(CS_ARCH_X86, CS_MODE_64)
    names = load_item_names(items_path)

    rows: list[str] = []
    anchors_ok = True
    for anchor in ANCHORS:
        expected = parse_hex(anchor.expected)
        actual = dispatch.rva_bytes(pe, raw, anchor.rva, len(expected))
        ok = actual == expected
        anchors_ok &= ok
        result = "PASS" if ok else f"FAIL (`{hex_bytes(actual)}`)"
        rows.append(
            f"| `{anchor.name}` | `0x{anchor.rva:X}` | {result} | `{anchor.expected}` | {anchor.meaning} |"
        )

    item_ids = [
        int.from_bytes(dispatch.rva_bytes(pe, raw, ITEM_LINE_RVA + index * 2, 2), "little")
        for index in range(3)
    ]
    item_line_ok = item_ids == [240, 241, 242]
    helper_callers = dispatch.direct_callers(pe, raw, 0x281434)
    callers_ok = 0x283098 in helper_callers

    lines = [
        "# DCL Auto-Potion static mechanism analysis",
        "",
        "Generated by `tools/analyze_dcl_auto_potion.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Item catalog: `{items_path}`",
        f"- Output: `{output}`",
        "",
        "## Byte anchors",
        "",
        "| Name | RVA | Result | Expected bytes | Meaning |",
        "| --- | ---: | --- | --- | --- |",
        *rows,
        "",
        "## Native eligible item line",
        "",
        f"Table RVA `0x{ITEM_LINE_RVA:X}`: **{'PASS' if item_line_ok else 'FAIL'}**.",
        "",
        "| Priority | Item id | Catalog name |",
        "| ---: | ---: | --- |",
    ]
    for priority, item_id in enumerate(item_ids, start=1):
        lines.append(f"| {priority} | `{item_id}` | {names.get(item_id, '(unknown)')} |")

    lines.extend([
        "",
        "The selector scans this table in order and takes the first item whose inventory byte is",
        "nonzero. The `unit+0x1EE & 0x30` special path selects Potion `240` without the inventory scan.",
        "The selected item id is stored at `unit+0x1A8`; order type is `6`; exact Reaction id `441`",
        "is stored at `unit+0x1A2` before the order-validation helper runs.",
        "",
        "## Order helper linkage",
        "",
        f"Direct callers of VM-entry helper `0x281434`: {', '.join(f'`0x{rva:X}`' for rva in helper_callers) or 'none'}.",
        f"Auto-Potion caller `0x283098` present: **{'PASS' if callers_ok else 'FAIL'}**.",
        "",
        "## Item selection window",
        "",
        *dispatch.disassembly(md, pe, raw, 0x283026, 0x9A),
        "",
        "## Inventory mutation window",
        "",
        *dispatch.disassembly(md, pe, raw, 0x28167B, 0x100),
        "",
        "## Static interpretation",
        "",
        "- **Proven-data/Strong-code:** native Auto-Potion is Potion-line only: Potion, Hi-Potion,",
        "  then X-Potion, with first-available priority. No Elixir, Phoenix Down, or Remedy id appears",
        "  in the selector table.",
        "- **Strong:** the selected inventory item is explicit in the typed reaction order at",
        "  `unit+0x1A8`, while the Reaction/action id remains `441` at `unit+0x1A2`.",
        "- **Strong candidate:** the real-code item executor reads the inventory byte indexed by its",
        "  selected item id and contains a one-unit decrement/write guarded by execution/mode flags.",
        "  The VM boundary prevents a complete static proof that every Auto-Potion execution reaches",
        "  this exact decrement instruction.",
        "- Post-damage timing, survivor-only behavior, one-per-own-cycle cadence, and Item Lore",
        "  exclusion remain separate gates. X-Potion eligibility is a design calibration choice, not",
        "  a missing engine mechanism.",
        "",
    ])
    return "\n".join(lines), anchors_ok and item_line_ok and callers_ok


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--items", type=Path, default=DEFAULT_ITEMS)
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-auto-potion-analysis.md"
    report, ok = render_report(args.exe, args.items, output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all Auto-Potion anchors and table checks PASS" if ok else "one or more Auto-Potion checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
