#!/usr/bin/env python3
"""Verify the current-build Vigilance staging route and its native-effect boundary."""
from __future__ import annotations

import argparse
import hashlib
import time
from pathlib import Path

import pefile


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = Path(
    r"D:/SteamLibrary/steamapps/common/FINAL FANTASY TACTICS - The Ivalice Chronicles/FFT_enhanced.exe"
)

ANCHORS = (
    (0x30B535, "4C 8B 35 2C FA 55 01", "saves the live reaction-unit global before stack simulation"),
    (0x30B611, "48 89 05 50 F9 55 01", "redirects that global to the stack-copy simulation unit"),
    (0x30B7FD, "8A 91 94 00 00 00", "loads reaction-set byte unit+0x94"),
    (0x30B837, "41 B3 08 41 84 D3", "selects unit+0x94 bit 0x08 for Vigilance"),
    (0x30B83F, "80 3D 30 4F 4A 00 15", "rejects the disallowed incoming action class"),
    (0x30B84C, "44 84 2D 47 4F 4A 00", "requires incoming result flag 0x10"),
    (0x30B859, "B8 AA 01 00 00", "selects exact reaction id 426"),
    (0x30B827, "66 89 43 10", "stages the selected reaction id at result+0x10"),
    (0x30B82B, "0F B7 05 46 4F 4A 00", "loads the incoming action id as reaction payload"),
    (0x30BB3C, "66 89 43 28", "stores the payload at result+0x28"),
    (0x30BB52, "4C 89 35 0F F4 55 01", "restores the live reaction-unit global"),
    (0x30BB4A, "66 39 7B 10 40 0F 95 C7", "returns true only when a reaction id was staged"),
)


def rva_bytes(pe: pefile.PE, raw: bytes, rva: int, size: int) -> bytes:
    offset = pe.get_offset_from_rva(rva)
    return raw[offset : offset + size]


def render(exe: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    checks = []
    for rva, expected_hex, meaning in ANCHORS:
        expected = bytes.fromhex(expected_hex)
        checks.append((rva, meaning, rva_bytes(pe, raw, rva, len(expected)) == expected))
    ok = all(passed for _, _, passed in checks)

    lines = [
        "# DCL native Vigilance analysis",
        "",
        "Generated by `tools/analyze_dcl_vigilance.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Output: `{output}`",
        "",
        "## Anchor verification",
        "",
        "| RVA | Result | Meaning |",
        "| ---: | --- | --- |",
    ]
    for rva, meaning, passed in checks:
        lines.append(f"| `0x{rva:X}` | {'PASS' if passed else 'FAIL'} | {meaning} |")

    lines.extend(
        [
            "",
            "## Native contract",
            "",
            "The current real-code dispatcher evaluates Vigilance from `unit+0x94 & 0x08` inside",
            "a stack-copy simulation of the current battle globals. On an eligible incoming result it",
            "stages exact reaction id `426` at `result+0x10`, mirrors the incoming action id to",
            "`result+0x28`, restores all redirected globals, and returns only a boolean to its caller.",
            "No evade byte, hit percentage, Dodge value, or status byte is changed in this real-code",
            "window. The actual native effect is therefore downstream/VM-owned.",
            "",
            "## Historical primary-source corroboration",
            "",
            "FFTPatcher's vanilla PSP resources identify effect slot `176` as `Beef Up/Vigilance`;",
            "the matching PSX resources identify it as `Gather Power/Caution`. Its PSX assembly-patch",
            "catalog replaces Caution's original Defending-status write with other status masks. This",
            "is Strong continuity evidence that native Vigilance is the renamed Caution/Defending",
            "reaction, not a hidden numeric evasion modifier. IVC's VM-owned effect still needs a live",
            "capture if exact native timing matters.",
            "",
            "## DCL boundary",
            "",
            "The final Thief design raises DCL Dodge for only the qualifying incoming attack and allows",
            "it once per Thief turn-cycle. Native Defending is persistent state with different timing,",
            "so it cannot implement that contract unchanged. The final mechanism must participate in",
            "the managed physical-contest decision before its defense roll, reserve the cadence without",
            "consuming it during forecast/AI evaluation, commit consumption only for execution, and avoid",
            "also queuing native Defending. Calc-provenance classification is the remaining timing gate.",
            "",
        ]
    )
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-vigilance-analysis.md"
    report, ok = render(args.exe, output)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all Vigilance checks PASS" if ok else "one or more Vigilance checks FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
