#!/usr/bin/env python3
"""Verify the current-build native Mana Shield staging and HP/MP apply semantics."""
from __future__ import annotations

import argparse
import hashlib
import time
from dataclasses import dataclass
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_64, Cs


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = Path(
    r"D:/SteamLibrary/steamapps/common/FINAL FANTASY TACTICS - The Ivalice Chronicles/FFT_enhanced.exe"
)


@dataclass(frozen=True)
class Anchor:
    name: str
    rva: int
    expected_hex: str
    meaning: str

    @property
    def expected(self) -> bytes:
        return bytes.fromhex(self.expected_hex)


ANCHORS = (
    Anchor(
        "reaction-unit-and-result-record",
        0x30B7EF,
        "48 8B 0D 72 F7 55 01 48 8B 1D 73 F7 55 01",
        "loads the current reaction unit and its target-local result record",
    ),
    Anchor(
        "mana-shield-reaction-bit",
        0x30B935,
        "44 8A 81 96 00 00 00",
        "loads reaction-set byte unit+0x96; bit 0 is reaction id 445",
    ),
    Anchor(
        "mana-shield-branch",
        0x30B9A9,
        "45 84 C1 74 40",
        "enters the Mana Shield branch when unit+0x96 bit 0 is set",
    ),
    Anchor(
        "read-staged-hp-debit",
        0x30B9AE,
        "0F B7 43 06 66 85 C0",
        "requires a nonzero staged HP debit at result+0x06 = unit+0x1C4",
    ),
    Anchor(
        "require-any-current-mp",
        0x30B9BB,
        "66 39 79 34",
        "requires only current MP != 0; it does not compare MP with damage",
    ),
    Anchor(
        "transfer-damage-to-mp-debit",
        0x30B9C5,
        "66 01 43 0A B8 E7 03 00 00 66 39 43 0A 7E 04 66 89 43 0A",
        "adds the full HP debit to staged MP debit and caps that debit at 999",
    ),
    Anchor(
        "set-mp-result-and-clear-hp",
        0x30B9D8,
        "80 63 27 5F B8 BD 01 00 00 80 4B 27 20 66 89 7B 06",
        "selects MP-result flag 0x20, stages reaction 445, and clears HP debit",
    ),
    Anchor(
        "apply-hp-mp-inputs",
        0x30A5D7,
        "0F BF 45 06 0F B7 57 30 44 0F B7 7F 32 0F BF 4D 08 44 0F B7 47 34",
        "reads staged HP debit/credit and current HP/MaxHP/current MP",
    ),
    Anchor(
        "apply-mp-clamp",
        0x30A5F9,
        "0F BF 45 0A 41 3B CF 44 0F 4E F9 0F BF 4D 0C 2B C8 42 8D 04 01",
        "computes currentMP + stagedMpCredit - stagedMpDebit before clamping",
    ),
    Anchor(
        "write-clamped-mp",
        0x30A634,
        "66 89 47 34",
        "writes the clamped MP value to unit+0x34",
    ),
)


def rva_bytes(pe: pefile.PE, raw: bytes, rva: int, size: int) -> bytes:
    offset = pe.get_offset_from_rva(rva)
    return raw[offset : offset + size]


def disassembly(md: Cs, pe: pefile.PE, raw: bytes, rva: int, size: int) -> list[str]:
    result = ["```text"]
    blob = rva_bytes(pe, raw, rva, size)
    for instruction in md.disasm(blob, pe.OPTIONAL_HEADER.ImageBase + rva):
        here = instruction.address - pe.OPTIONAL_HEADER.ImageBase
        result.append(f"{here:08X}: {instruction.mnemonic:<8} {instruction.op_str}".rstrip())
    result.append("```")
    return result


def render(exe: Path, output: Path) -> tuple[str, bool]:
    raw = exe.read_bytes()
    pe = pefile.PE(data=raw, fast_load=True)
    md = Cs(CS_ARCH_X86, CS_MODE_64)

    checks: list[tuple[Anchor, bytes, bool]] = []
    for anchor in ANCHORS:
        actual = rva_bytes(pe, raw, anchor.rva, len(anchor.expected))
        checks.append((anchor, actual, actual == anchor.expected))
    ok = all(passed for _, _, passed in checks)

    lines = [
        "# DCL native Mana Shield mechanism analysis",
        "",
        "Generated by `tools/analyze_dcl_mana_shield.py`.",
        "",
        "## Inputs",
        "",
        f"- Executable: `{exe}`",
        f"- SHA-256: `{hashlib.sha256(raw).hexdigest().upper()}`",
        f"- Output: `{output}`",
        "",
        "## Anchor verification",
        "",
        "| Anchor | RVA | Result | Meaning |",
        "| --- | ---: | --- | --- |",
    ]
    for anchor, _, passed in checks:
        lines.append(
            f"| `{anchor.name}` | `0x{anchor.rva:X}` | {'PASS' if passed else 'FAIL'} | {anchor.meaning} |"
        )

    lines.extend(
        [
            "",
            "## Native contract",
            "",
            "The reaction unit is `qword[0x14186AF68]`. Its target-local result record is",
            "`qword[0x14186AF70] = unit+0x1BE`, so record `+0x06/+0x0A/+0x27/+0x10` are unit",
            "`+0x1C4/+0x1C8/+0x1E5/+0x1CE` respectively.",
            "",
            "When reaction id 445 is equipped, staged HP debit is nonzero, and current MP is merely",
            "nonzero, the native branch:",
            "",
            "1. adds the complete staged HP debit to staged MP debit;",
            "2. caps the staged MP debit at 999;",
            "3. clears result bits `0x80` and `0x20`, then sets MP-result bit `0x20`;",
            "4. clears the staged HP debit; and",
            "5. stages exact reaction id `445` at unit `+0x1CE`.",
            "",
            "The later apply path independently clamps `currentMP + credit - debit` into",
            "`0..MaxMP`; it never restores HP damage when the MP debit exceeds current MP. Therefore",
            "**one remaining MP point can natively prevent the entire HP hit**. This is a Strong",
            "current-build engine fact, not a balanced proportional shield.",
            "",
            "## DCL implementation boundary",
            "",
            "The existing combined pre-clamp formula context already exposes `dcl.oldMpDebit`,",
            "`target.mp`, `target.maxMp`, staged HP/MP formulas, and the current action context. It can",
            "calculate a bounded authored HP/MP split. A complete replacement also needs coherent",
            "result-flag/presentation ownership when both HP and MP change or when a native redirect is",
            "rejected for insufficient MP. Ratio and all-or-partial absorption remain design/calibration",
            "decisions; the native one-MP full shield must not be mistaken for the final DCL rule.",
            "",
            "## Relevant disassembly",
            "",
            "### Mana Shield staging",
            "",
            *disassembly(md, pe, raw, 0x30B9A9, 0x45),
            "",
            "### Shared HP/MP apply",
            "",
            *disassembly(md, pe, raw, 0x30A5D7, 0x61),
            "",
        ]
    )
    return "\n".join(lines), ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = args.output or ROOT / "work" / f"{int(time.time())}-dcl-mana-shield-analysis.md"
    report, ok = render(args.exe, output)
    output.write_text(report, encoding="utf-8", newline="\n")
    print(f"wrote {output}")
    print("all Mana Shield anchors PASS" if ok else "one or more Mana Shield anchors FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
