#!/usr/bin/env python3
"""Build the data-layer "neuter placeholder" for the Generic Chronicle battle runtime.

Why this exists (see docs/modding/06 section 1 and docs/modding/07 Test 1b):
The reactive HP reconciler in the code mod cannot PREVENT death - the engine fires the
death state the instant vanilla damage brings HP to 0, before our poll wakes. The fix is
to make vanilla damage harmless and predictable so the engine never kills / never shows a
wrong number, and our C# engine owns the real outcome. Test D proved the data lever works
(the exe reads OverrideAbilityActionData Formula/X/Y, and ItemWeaponData Power).

This script currently emits the WEAPON neuter (physical attacks), which is pure TableData
XML and needs no external tool. It re-points every weapon to Power=1 so any weapon-power
based attack (PA*WP, WP*WP, (PA+Sp)/2*WP, ...) deals a tiny, non-lethal, but still non-zero
delta the reconciler can observe and rewrite.

Coverage / gaps (documented honestly):
  - Covers: every attack that scales with weapon Power (most human physical attacks).
  - Does NOT cover: bare-hands / monster innate attacks (no weapon power term) and spell
    damage. Those need the OverrideAbilityActionData NXD neuter (separate pass; needs the
    base per-ability Formula/X/Y, which is exe-hardcoded, plus FF16Tools).

Usage:
    python tools/build_neuter_data.py
Output (repo data-mod source, deploy with deploy.ps1):
    mod/fftivc.generic.chronicle/FFTIVC/tables/enhanced/ItemWeaponData.xml
"""
from __future__ import annotations
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TEMPLATE = Path(
    r"C:/Reloaded-II/Mods/fftivc.utility.modloader/TableData/ItemWeaponData.xml"
)
OUT = REPO / "mod/fftivc.generic.chronicle/FFTIVC/tables/enhanced/ItemWeaponData.xml"

NEUTER_POWER = 1  # tiny but non-zero so the reconciler still observes a delta


def build_weapon_neuter() -> str:
    if not TEMPLATE.exists():
        sys.exit(f"ERROR: weapon template not found: {TEMPLATE}")
    tree = ET.parse(TEMPLATE)
    root = tree.getroot()
    entries = root.find("Entries")
    if entries is None:
        sys.exit("ERROR: <Entries> not found in weapon template")

    edited = []
    for w in entries.findall("ItemWeapon"):
        wid_el = w.find("Id")
        pow_el = w.find("Power")
        if wid_el is None or pow_el is None:
            continue
        wid = int(wid_el.text)
        power = int(pow_el.text)
        if power <= NEUTER_POWER:
            continue  # already tiny / "nothing equipped" (Power 0) - leave as inherited
        edited.append(wid)

    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "",
        "<!--",
        "  GENERATED by tools/build_neuter_data.py - do not hand-edit.",
        "  Data-layer NEUTER PLACEHOLDER (docs/modding/06 section 1, docs/modding/07 Test 1b).",
        "  Every weapon Power is forced to 1 so vanilla physical attacks are tiny and non-lethal;",
        "  the code-mod reconciler owns the real damage result. Only <Id> + <Power> are shipped so",
        "  the loader merges per-property and nothing else is disturbed.",
        f"  Weapons neutered: {len(edited)} (Power>1 in vanilla). Bare-hands/monster/spell damage",
        "  is NOT covered here - that needs the OverrideAbilityActionData NXD neuter.",
        "-->",
        "",
        "<ItemWeaponTable>",
        "  <Version>1</Version>",
        "  <Entries>",
    ]
    for wid in edited:
        lines.append("    <ItemWeapon>")
        lines.append(f"      <Id>{wid}</Id>")
        lines.append(f"      <Power>{NEUTER_POWER}</Power>")
        lines.append("    </ItemWeapon>")
    lines.append("  </Entries>")
    lines.append("</ItemWeaponTable>")
    lines.append("")
    return "\n".join(lines), len(edited)


def main() -> None:
    xml, count = build_weapon_neuter()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(xml, encoding="utf-8")
    print(f"[neuter] wrote {OUT}")
    print(f"[neuter] weapons neutered to Power={NEUTER_POWER}: {count}")


if __name__ == "__main__":
    main()
