#!/usr/bin/env python3
"""Generate a focused report for known neuter gap candidates.

This is not a balance report. It answers: which local data levers currently touch Materia Blade,
Gravity/percent-like abilities, and Cloud Limits, and which ones still need live proof because
their formulas may ignore Power/X/Y.
"""
from __future__ import annotations

import argparse
import csv
import sqlite3
import xml.etree.ElementTree as ET
from pathlib import Path

import build_neuter_data as neuter

REPO = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO / "work" / "neuter_gap_targets.md"
ITEM_CATALOG = REPO / "work" / "item_catalog.csv"
BASELINE_ABILITIES = REPO / "work" / "baseline_abilities.csv"

GAP_ABILITY_IDS = [42, 43, 73, 222, 257, 258, 259, 260, 261, 262, 263, 264]
GAP_ITEM_NAMES = {"Materia Blade", "Materia Blade Plus"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate or check the neuter gap target report.")
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in report is stale.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUT)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    report = build_report()
    if args.check:
        if not args.output.exists():
            print(f"missing report: {args.output}")
            return 1
        actual = args.output.read_text(encoding="utf-8")
        if actual != report:
            print(f"stale report: {args.output} (run python tools/report_neuter_gap_targets.py)")
            return 1
        print("neuter gap target report is current")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


def build_report() -> str:
    items = load_items()
    abilities = load_abilities()
    flags = load_ability_flags()
    base_rows = load_override_rows(neuter.BASE_OVERRIDE_SQLITE)
    neuter_rows = load_override_rows(neuter.NEUTER_OVERRIDE_SQLITE)
    generated_weapon_power = load_generated_weapon_power()
    damaging = set(neuter.classify_damaging_abilities())
    bands = neuter.classify_damaging_ability_bands()

    materia_rows = [row for row in items if row.get("name") in GAP_ITEM_NAMES]

    lines: list[str] = [
        "# Neuter Gap Targets",
        "",
        "Generated by `tools/report_neuter_gap_targets.py`. Do not hand-edit.",
        "",
        "This report tracks the current data levers for the known risky families: Materia Blade /",
        "Materia Blade Plus, Gravity-style percent damage, Lich, Gravija, and Cloud Limits.",
        "",
        "## Materia Blade / Materia Blade Plus",
        "",
        "| Item | Item Id | ItemWeaponData Id | Weapon Formula | Vanilla Power | Generated Power | Options Ability | Conclusion |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
    ]
    for row in materia_rows:
        data_id = to_int(row.get("additional_data_id"))
        generated = generated_weapon_power.get(data_id, "inherited")
        conclusion = (
            "shares weapon-data row; current sparse ItemWeaponData Power override should cover this basic attack"
            if data_id == 32
            else "unexpected weapon-data id; inspect live"
        )
        lines.append(
            "| "
            f"{row.get('name')} | {row.get('item_id')} | {data_id} | "
            f"{row.get('weapon_formula')} | {row.get('weapon_power')} | {generated} | "
            f"{row.get('weapon_options_ability_id')} | {conclusion} |"
        )

    lines.extend(
        [
            "",
            "Local conclusion: `Materia Blade` (`item_id=32`) and `Materia Blade Plus` (`item_id=256`)",
            "both point to `ItemWeaponData.Id=32`, `Formula=1`, `Power=10`, `OptionsAbilityId=0`.",
            "The generated uniform neuter emits `Id=32 Power=1`. If a live basic attack still produces",
            "large damage with the data mod deployed, the next hypothesis is not a missing Materia Blade",
            "row; it is either a deployment/load-order issue or a special attack path that ignores this",
            "weapon Power field.",
            "",
            "## Ability Gap Candidates",
            "",
            "| Id | Name | Flags | Override Row | Neutered by HP heuristic | Base Formula/X/Y/CT | Neuter X/Y | Sentinel Band | Risk / Next Live Proof |",
            "| ---: | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )

    for ability_id in GAP_ABILITY_IDS:
        ability = abilities.get(ability_id, {})
        ability_flags = flags.get(ability_id, "")
        base = base_rows.get(ability_id)
        cur = neuter_rows.get(ability_id)
        present = base is not None
        is_neutered = ability_id in damaging and present
        risk = risk_note(ability_id, ability.get("Name", ""), ability_flags, is_neutered, present)
        lines.append(
            "| "
            f"{ability_id} | {ability.get('Name', '')} | `{ability_flags or 'none'}` | "
            f"{'yes' if present else 'no'} | {'yes' if is_neutered else 'no'} | "
            f"{format_base(base)} | {format_xy(cur)} | {bands.get(ability_id, 'n/a')} | {risk} |"
        )

    lines.extend(
        [
            "",
            "## Offline Read",
            "",
            "- Gravity/Lich rows are in `OverrideAbilityActionData` and are selected by the HP heuristic,",
            "  so the current builder writes their `X/Y`. If they remain large live, their formula likely",
            "  ignores X/Y and needs a specific data lever or runtime special-case.",
            "- `Gravija` (`222`) is suspicious: local `AbilityData` lacks the HP flag, so the current HP",
            "  heuristic does not neuter it despite the name. This needs a live spot-check or a manual",
            "  include list.",
            "- Most Cloud Limit HP actions (`257`, `258`, `259`, `260`, `261`, `264`) are selected by the",
            "  HP heuristic and get `X/Y` rewritten. `Finishing Touch` (`262`) and `Omnislash` (`263`) do",
            "  not have the HP flag locally, so they are not covered by the generic rule.",
            "- The clean next offline improvement is a small explicit include/override table for known",
            "  exceptions once live confirms which of these ignore the generic `X/Y` path.",
            "",
        ]
    )
    return "\n".join(lines)


def load_items() -> list[dict[str, str]]:
    with ITEM_CATALOG.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def load_abilities() -> dict[int, dict[str, str]]:
    with BASELINE_ABILITIES.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    return {to_int(row.get("Id")): row for row in rows}


def load_ability_flags() -> dict[int, str]:
    root = ET.parse(neuter.ABILITY_TEMPLATE).getroot()
    entries = root.find("Entries")
    result: dict[int, str] = {}
    if entries is None:
        return result
    for ability in entries.findall("Ability"):
        result[to_int(ability.findtext("Id"))] = ability.findtext("AIBehaviorFlags", "")
    return result


def load_override_rows(path: Path) -> dict[int, dict[str, int]]:
    with sqlite3.connect(path) as con:
        con.row_factory = sqlite3.Row
        rows = con.execute("SELECT Key, Formula, X, Y, CT FROM OverrideAbilityActionData ORDER BY Key").fetchall()
    return {
        int(row["Key"]): {
            "Formula": int(row["Formula"]),
            "X": int(row["X"]),
            "Y": int(row["Y"]),
            "CT": int(row["CT"]),
        }
        for row in rows
    }


def load_generated_weapon_power() -> dict[int, int]:
    root = ET.parse(neuter.OUT).getroot()
    entries = root.find("Entries")
    if entries is None:
        return {}
    result: dict[int, int] = {}
    for row in entries.findall("ItemWeapon"):
        result[to_int(row.findtext("Id"))] = to_int(row.findtext("Power"))
    return result


def risk_note(ability_id: int, name: str, flags: str, is_neutered: bool, present: bool) -> str:
    if not present:
        return "outside override table"
    if ability_id in {42, 43, 73}:
        return "percent/Gravity-like; prove whether formula reads X/Y"
    if ability_id == 222:
        return "name suggests Gravity but HP flag absent; not selected by generic neuter"
    if ability_id in {262, 263}:
        return "Cloud Limit without HP flag; not selected by generic neuter"
    if 257 <= ability_id <= 264:
        return "Cloud Limit; selected if HP flag present, but formula may ignore X/Y" if is_neutered else "Cloud Limit not selected by HP heuristic"
    if not is_neutered:
        return "not selected by HP heuristic"
    if "HP" not in flags:
        return "no HP flag despite suspicious name"
    return "covered by generic X/Y neuter; live spot-check still required"


def format_base(row: dict[str, int] | None) -> str:
    if row is None:
        return "missing"
    return f"`F={row['Formula']}, X={row['X']}, Y={row['Y']}, CT={row['CT']}`"


def format_xy(row: dict[str, int] | None) -> str:
    if row is None:
        return "missing"
    return f"`X={row['X']}, Y={row['Y']}`"


def to_int(value: object) -> int:
    if value is None:
        return -1
    text = str(value).strip()
    if not text:
        return -1
    return int(text)


if __name__ == "__main__":
    raise SystemExit(main())
