#!/usr/bin/env python3
"""Write a Markdown coverage report for the data-layer neuter placeholder."""
from __future__ import annotations

import argparse
import csv
import sqlite3
import xml.etree.ElementTree as ET
from pathlib import Path

import build_neuter_data as neuter

DEFAULT_OUT = neuter.REPO / "work" / "neuter_coverage.md"
BASELINE_ABILITIES = neuter.REPO / "work" / "baseline_abilities.csv"
THROW_IDS = set(range(382, 394))
JUMP_IDS = set(range(394, 406))
AIM_IDS = set(range(406, 414))


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("-o", "--output", type=Path, default=DEFAULT_OUT)
    return p.parse_args()


def main() -> int:
    args = parse_args()
    report = build_report()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


def build_report() -> str:
    ability_names = load_ability_names(BASELINE_ABILITIES)
    damaging = set(neuter.classify_damaging_abilities())
    override_rows = read_override_rows(neuter.NEUTER_OVERRIDE_SQLITE)
    base_rows = read_override_rows(neuter.BASE_OVERRIDE_SQLITE)
    present = set(override_rows)
    neutered = sorted(damaging & present)
    skipped = sorted(damaging - present)
    weapon_ids = read_weapon_neuter_ids(neuter.OUT)
    charge_aim_ids = read_charge_aim_neuter_ids(neuter.CHARGE_AIM_OUT)

    lines: list[str] = []
    lines.append("# Neuter Placeholder Coverage")
    lines.append("")
    lines.append("Generated by `tools/report_neuter_coverage.py`.")
    lines.append("")
    lines.append("## Sources")
    lines.append("")
    lines.append(f"- Weapon XML: `{neuter.OUT}`")
    lines.append(f"- Charge/Aim XML: `{neuter.CHARGE_AIM_OUT}`")
    lines.append(f"- Ability template: `{neuter.ABILITY_TEMPLATE}`")
    lines.append(f"- Base override sqlite: `{neuter.BASE_OVERRIDE_SQLITE}`")
    lines.append(f"- Neuter override sqlite: `{neuter.NEUTER_OVERRIDE_SQLITE}`")
    lines.append(f"- Ability NXD: `{neuter.ABILITY_NXD_OUT}`")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Surface | Coverage | Evidence |")
    lines.append("| --- | ---: | --- |")
    lines.append(f"| Weapon Power placeholder | {len(weapon_ids)} weapons | `Power={neuter.NEUTER_POWER}` in sparse `ItemWeaponData.xml` |")
    lines.append(f"| Aim/Charge Power placeholder | {len(charge_aim_ids)} abilities | `Power={neuter.NEUTER_CHARGE_AIM_POWER}` in sparse `AbilityChargeAimData.xml` |")
    lines.append(f"| Offensive HP abilities classified | {len(damaging)} abilities | `AIBehaviorFlags` has `HP` + `TargetEnemies`, not `TargetAllies` |")
    lines.append(f"| Ability rows neutered in override table | {len(neutered)} abilities | `X=Y={neuter.NEUTER_XY}` in 368-row `OverrideAbilityActionData` |")
    lines.append(f"| Offensive abilities outside override table | {len(skipped)} abilities | ability id absent from 368-row override table |")
    lines.append("")
    lines.append("## Spot Checks")
    lines.append("")
    lines.append("| Ability | Expected | Current X/Y | Base X/Y |")
    lines.append("| --- | --- | --- | --- |")
    for ability_id, expected in [(1, "healing untouched"), (2, "healing untouched"), (16, "damage neutered"), (20, "damage neutered"), (24, "damage neutered")]:
        cur = override_rows.get(ability_id)
        base = base_rows.get(ability_id)
        lines.append(
            "| "
            f"`{ability_id}` {ability_names.get(ability_id, '')} | {expected} | "
            f"{format_xy(cur)} | {format_xy(base)} |"
        )
    lines.append("")
    lines.append("## High-Id Fallback Coverage")
    lines.append("")
    if not skipped:
        lines.append("No classified offensive ability ids are outside the override table.")
    else:
        throw_skipped = sorted(set(skipped) & THROW_IDS)
        jump_skipped = sorted(set(skipped) & JUMP_IDS)
        aim_skipped = sorted(set(skipped) & AIM_IDS)
        unresolved = sorted(set(skipped) - THROW_IDS - JUMP_IDS - AIM_IDS)

        lines.append("These actions are outside the 368-row `OverrideAbilityActionData` table, so they cannot use the X/Y NXD neuter. They do have family-specific fallback levers:")
        lines.append("")
        lines.append("| Family | Ability Ids | Fallback lever | Offline evidence |")
        lines.append("| --- | --- | --- | --- |")
        lines.append(f"| Throw | {format_id_range(throw_skipped)} | weapon `Power={neuter.NEUTER_POWER}` | formula catalog says Throw is `Speed * WP`; thrown weapon/bomb categories are in `ItemWeaponData.xml` |")
        lines.append(f"| Jump | {format_id_range(jump_skipped)} | weapon `Power={neuter.NEUTER_POWER}` | formula catalog says Jump uses WP; `AbilityJumpData.xml` exposes only range/vertical |")
        lines.append(f"| Aim/Charge | {format_id_range(aim_skipped)} | charge `Power={neuter.NEUTER_CHARGE_AIM_POWER}` | `AbilityChargeAimData.xml` generated for Aim +2..+20; Aim +1 is already Power=1 |")
        lines.append("")
        lines.append("Rows still absent from every current fallback:")
        lines.append("")
        lines.append("| Ability Id | Name | Reason |")
        lines.append("| ---: | --- | --- |")
        if not unresolved:
            lines.append("| - | - | none in the classified high-id set |")
        else:
            for ability_id in unresolved:
                lines.append(f"| {ability_id} | {ability_names.get(ability_id, '')} | absent from override and no fallback table classified |")
    lines.append("")
    lines.append("## Residual Runtime Risks")
    lines.append("")
    lines.append("- Throw/Jump high-id coverage is inferred from the formula catalog and item-power tables; it still needs a live spot-check.")
    lines.append("- Any formula that ignores both `X` and `Y`, such as percent/Gravity-style effects, may still produce a non-placeholder result.")
    lines.append("- The placeholder only makes vanilla non-lethal. Custom lethal results must use the engine-owned `MinHpFloor=1` path; HP=0 and KO-flag byte writes are preserved only as historical/refuted probes.")
    lines.append("")
    return "\n".join(lines)


def load_ability_names(path: Path) -> dict[int, str]:
    if not path.exists():
        return {}
    names: dict[int, str] = {}
    with path.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            try:
                ability_id = int(row.get("Id", row.get("id", "")))
            except ValueError:
                continue
            names[ability_id] = clean_name(row.get("Name", row.get("name", "")))
    return names


def read_weapon_neuter_ids(path: Path) -> list[int]:
    root = ET.parse(path).getroot()
    entries = root.find("Entries")
    if entries is None:
        return []
    ids: list[int] = []
    for row in entries.findall("ItemWeapon"):
        ids.append(int(row.findtext("Id", "-1")))
    return ids


def read_charge_aim_neuter_ids(path: Path) -> list[int]:
    root = ET.parse(path).getroot()
    entries = root.find("Entries")
    if entries is None:
        return []
    ids: list[int] = []
    for row in entries.findall("AbilityChargeAim"):
        ids.append(int(row.findtext("Id", "-1")))
    return ids


def format_id_range(ids: list[int]) -> str:
    if not ids:
        return "none"
    if ids == list(range(ids[0], ids[-1] + 1)):
        return f"`{ids[0]}-{ids[-1]}` ({len(ids)})"
    return ", ".join(f"`{ability_id}`" for ability_id in ids)


def read_override_rows(path: Path) -> dict[int, dict[str, int]]:
    with sqlite3.connect(path) as con:
        con.row_factory = sqlite3.Row
        rows = con.execute("SELECT Key, X, Y FROM OverrideAbilityActionData ORDER BY Key").fetchall()
    return {int(row["Key"]): {"X": int(row["X"]), "Y": int(row["Y"])} for row in rows}


def format_xy(row: dict[str, int] | None) -> str:
    if row is None:
        return "missing"
    return f"`X={row['X']}, Y={row['Y']}`"


def clean_name(name: str) -> str:
    return name.replace("\u00c2\u00b1", "+/-").replace("\u00b1", "+/-")


if __name__ == "__main__":
    raise SystemExit(main())
