namespace fftivc.generic.chronicle.codemod;

internal readonly record struct DclApproachTile(int X, int Y, int Layer)
{
    public bool IsNativeTile => X is >= 0 and <= 255 && Y is >= 0 and <= 255 && Layer is 0 or 1;

    public bool IsCardinalNeighbor(DclApproachTile other)
        => Math.Abs(X - other.X) + Math.Abs(Y - other.Y) == 1;
}

/// <summary>
/// Immutable data copied synchronously at the native route boundary before another route byte is
/// consumed. Sequence is generated by the native control block. RouteSignature identifies the
/// accepted 128-byte route together with its starting tile; it is not a balance or job concept.
/// </summary>
internal readonly record struct DclApproachBoundary(
    long BattleGeneration,
    long Sequence,
    nint MoverPtr,
    int MoverTableIndex,
    int MoverCharId,
    ulong RouteSignature,
    int RouteLength,
    int RouteCursor,
    DclApproachTile Tile)
{
    public bool IsValid =>
        BattleGeneration > 0 &&
        Sequence > 0 &&
        MoverPtr != 0 &&
        MoverTableIndex is >= 0 and < 21 &&
        MoverCharId >= 0 &&
        RouteLength is >= 1 and <= 127 &&
        RouteCursor >= 0 &&
        RouteCursor <= RouteLength &&
        Tile.IsNativeTile;
}

internal readonly record struct DclApproachTransition(
    DclApproachBoundary Boundary,
    DclApproachTile PreviousTile,
    DclApproachTile EnteredTile);

/// <summary>
/// Job-free reservation for one reactor. OwnerReactionId selects authored cadence/taxonomy while
/// DeliveryReactionId selects a native delivery carrier. The coordinator never chooses either id.
/// </summary>
internal readonly record struct DclApproachCandidate(
    nint ReactorPtr,
    int ReactorTableIndex,
    int ReactorCharId,
    int OwnerReactionId,
    int DeliveryReactionId);

internal readonly record struct DclApproachEligibilityDecision(bool Eligible, string Reason);

/// <summary>
/// Trigger taxonomy only. The caller owns geometry and supplies the before/after reach verdicts;
/// this keeps map height/LoS policy separate and lets the same mechanism serve any authored owner.
/// </summary>
internal static class DclApproachEligibility
{
    public static DclApproachEligibilityDecision Evaluate(
        bool moverAndReactorAreOpposing,
        bool moverAlive,
        bool reactorAlive,
        bool exactOwnerEquipped,
        bool previousTileInReach,
        bool enteredTileInReach)
    {
        if (!moverAndReactorAreOpposing)
            return new(false, "not-opposing");
        if (!moverAlive)
            return new(false, "mover-not-alive");
        if (!reactorAlive)
            return new(false, "reactor-not-alive");
        if (!exactOwnerEquipped)
            return new(false, "owner-not-equipped");
        if (previousTileInReach)
            return new(false, "already-in-reach");
        if (!enteredTileInReach)
            return new(false, "still-outside-reach");
        return new(true, "entered-reach");
    }

    public static bool IsWithinHorizontalReach(
        DclApproachTile source,
        DclApproachTile target,
        int minimumReach,
        int maximumReach,
        bool requireSameLayer)
    {
        if (!source.IsNativeTile || !target.IsNativeTile || minimumReach < 0 || maximumReach < minimumReach)
            return false;
        if (requireSameLayer && source.Layer != target.Layer)
            return false;

        int distance = Math.Abs(source.X - target.X) + Math.Abs(source.Y - target.Y);
        return distance >= minimumReach && distance <= maximumReach;
    }
}

/// <summary>
/// Pass-2 mailbox coexistence policy. The native selector skips the current source index before it
/// reads unit+0x1CE, so a native word there is inert for this invocation and must be preserved.
/// Every other native word, and every private synthetic reservation, remains a hard conflict.
/// </summary>
internal static class DclApproachMailboxPolicy
{
    public static bool IsCompatible(
        int slotIndex,
        int moverTableIndex,
        int nativeReactionId,
        bool syntheticReserved)
        => slotIndex is >= 0 and < 21 &&
           moverTableIndex is >= 0 and < 21 &&
           !syntheticReserved &&
           (nativeReactionId == 0 || slotIndex == moverTableIndex);
}

internal enum DclApproachPhase
{
    Idle,
    Baseline,
    AwaitingDecision,
    Armed,
    QueueRunning,
    AwaitingResume,
    Released,
    Resumed,
    Aborted,
}

internal readonly record struct DclApproachDecision(
    DclApproachPhase Phase,
    bool ShouldPause,
    bool ShouldStage,
    bool Replayed,
    DclApproachTransition? Transition,
    IReadOnlyList<DclApproachCandidate> Candidates,
    string Reason);

/// <summary>
/// Pure fail-closed state machine for a movement-step Reaction transaction. The native hook owns
/// synchronous snapshot/pause/queue/resume control; this class owns identity, idempotency, and the
/// permission to stage or rewrite. Any mismatch releases or aborts without granting a native write.
/// </summary>
internal sealed class DclApproachCoordinator
{
    private static readonly IReadOnlyList<DclApproachCandidate> NoCandidates = Array.Empty<DclApproachCandidate>();

    private readonly object _gate = new();
    private DclApproachBoundary? _baseline;
    private DclApproachTransition? _transition;
    private DclApproachCandidate[] _candidates = Array.Empty<DclApproachCandidate>();
    private readonly HashSet<int> _committedReactorIndices = new();
    private DclApproachDecision _lastDecision = EmptyDecision("idle");
    private long _deadlineTick;

    public DclApproachPhase Phase { get; private set; } = DclApproachPhase.Idle;

    /// <summary>
    /// True while Approach owns the shared pass-2 queue/mailbox transaction. A synthetic hit
    /// Reaction must not reserve that same queue until the Approach transaction releases or resumes.
    /// </summary>
    public bool BlocksSyntheticReservations()
    {
        lock (_gate)
            return Phase is DclApproachPhase.Armed or DclApproachPhase.QueueRunning or
                DclApproachPhase.AwaitingResume;
    }

    public DclApproachDecision ObserveBoundary(DclApproachBoundary boundary)
    {
        lock (_gate)
        {
            if (!boundary.IsValid)
                return AbortInternal(boundary, "invalid-boundary");

            if (_transition is { } active && active.Boundary.Sequence == boundary.Sequence)
            {
                if (active.Boundary != boundary)
                    return AbortInternal(boundary, "sequence-content-mismatch");

                bool pause = Phase is DclApproachPhase.AwaitingDecision or DclApproachPhase.Armed;
                _lastDecision = _lastDecision with { ShouldPause = pause, Replayed = true };
                return _lastDecision;
            }

            if (IsTransactionActive(Phase))
                return AbortInternal(boundary, "pending-boundary-diverged");

            if (_baseline is not { } previous)
                return SetBaseline(boundary, boundary.RouteCursor == 0 ? "route-origin" : "missing-route-origin");

            if (!SameRoute(previous, boundary))
                return SetBaseline(boundary, boundary.RouteCursor == 0 ? "new-route-origin" : "route-identity-changed");

            if (boundary.RouteCursor == previous.RouteCursor && boundary.Tile == previous.Tile)
                return SetBaseline(boundary, "same-step-boundary");

            if (boundary.RouteCursor != previous.RouteCursor + 1 ||
                !previous.Tile.IsCardinalNeighbor(boundary.Tile))
                return SetBaseline(boundary, "non-cardinal-or-discontinuous-step");

            var transition = new DclApproachTransition(boundary, previous.Tile, boundary.Tile);
            _transition = transition;
            _candidates = Array.Empty<DclApproachCandidate>();
            _committedReactorIndices.Clear();
            _deadlineTick = 0;
            Phase = DclApproachPhase.AwaitingDecision;
            _lastDecision = new DclApproachDecision(
                Phase,
                ShouldPause: true,
                ShouldStage: false,
                Replayed: false,
                transition,
                NoCandidates,
                "awaiting-eligibility");
            return _lastDecision;
        }
    }

    public DclApproachDecision Resolve(
        long sequence,
        IReadOnlyList<DclApproachCandidate> candidates,
        bool battleStateIsMovement,
        bool nativeReactionMailboxesCompatible,
        long nowTick,
        long deadlineTick)
    {
        lock (_gate)
        {
            if (_transition is not { } transition || transition.Boundary.Sequence != sequence ||
                Phase != DclApproachPhase.AwaitingDecision)
                return CurrentDecision("no-matching-awaiting-transaction");

            if (!battleStateIsMovement)
                return AbortInternal(transition.Boundary, "movement-state-lost");
            if (deadlineTick < nowTick)
                return AbortInternal(transition.Boundary, "decision-deadline-expired");
            if (!nativeReactionMailboxesCompatible)
                return AbortInternal(transition.Boundary, "native-mailbox-conflict");

            if (candidates.Count == 0)
                return ReleaseInternal("no-eligible-reactor");

            string? candidateError = ValidateCandidates(transition.Boundary, candidates);
            if (candidateError is not null)
                return AbortInternal(transition.Boundary, candidateError);

            _candidates = candidates.ToArray();
            _deadlineTick = deadlineTick;
            Phase = DclApproachPhase.Armed;
            _lastDecision = new DclApproachDecision(
                Phase,
                ShouldPause: true,
                ShouldStage: true,
                Replayed: false,
                transition,
                Array.AsReadOnly(_candidates),
                "armed");
            return _lastDecision;
        }
    }

    public bool TryBeginQueue(
        long sequence,
        DclApproachBoundary liveBoundary,
        bool battleStateIsMovement,
        bool stagedMailboxesMatch,
        long nowTick,
        out IReadOnlyList<DclApproachCandidate> candidates)
    {
        lock (_gate)
        {
            candidates = NoCandidates;
            if (_transition is not { } transition ||
                Phase != DclApproachPhase.Armed ||
                transition.Boundary.Sequence != sequence ||
                transition.Boundary != liveBoundary ||
                !battleStateIsMovement ||
                !stagedMailboxesMatch ||
                nowTick > _deadlineTick)
            {
                AbortInternal(liveBoundary, "queue-revalidation-failed");
                return false;
            }

            Phase = DclApproachPhase.QueueRunning;
            candidates = Array.AsReadOnly(_candidates);
            _lastDecision = _lastDecision with
            {
                Phase = Phase,
                ShouldPause = true,
                ShouldStage = false,
                Replayed = false,
                Reason = "queue-running",
            };
            return true;
        }
    }

    public DclApproachDecision ObserveQueueResult(long sequence, bool accepted)
    {
        lock (_gate)
        {
            if (_transition is not { } transition || transition.Boundary.Sequence != sequence ||
                Phase != DclApproachPhase.QueueRunning)
                return CurrentDecision("queue-result-mismatch");

            if (!accepted)
                return ReleaseInternal("queue-empty-or-rejected");

            Phase = DclApproachPhase.AwaitingResume;
            _lastDecision = _lastDecision with
            {
                Phase = Phase,
                ShouldPause = false,
                ShouldStage = false,
                Replayed = false,
                Reason = "awaiting-owned-resume",
            };
            return _lastDecision;
        }
    }

    public bool TryRecordCommit(
        long sequence,
        nint reactorPtr,
        int reactorCharId,
        int reactorTableIndex,
        int sourceTableIndex)
    {
        lock (_gate)
        {
            if (_transition is not { } transition ||
                transition.Boundary.Sequence != sequence ||
                Phase is not (DclApproachPhase.QueueRunning or DclApproachPhase.AwaitingResume) ||
                sourceTableIndex != transition.Boundary.MoverTableIndex)
                return false;

            bool owned = _candidates.Any(candidate =>
                candidate.ReactorPtr == reactorPtr &&
                candidate.ReactorCharId == reactorCharId &&
                candidate.ReactorTableIndex == reactorTableIndex);
            if (!owned)
            {
                AbortInternal(transition.Boundary, "foreign-reaction-commit");
                return false;
            }

            return _committedReactorIndices.Add(reactorTableIndex);
        }
    }

    public bool TryRewriteResume(
        long sequence,
        DclApproachBoundary liveBoundary,
        int nativeTerminalState,
        out int replacementState)
    {
        lock (_gate)
        {
            replacementState = nativeTerminalState;
            if (_transition is not { } transition ||
                transition.Boundary.Sequence != sequence ||
                Phase != DclApproachPhase.AwaitingResume ||
                nativeTerminalState != 0x28 ||
                transition.Boundary != liveBoundary ||
                _committedReactorIndices.Count == 0)
                return false;

            replacementState = 0x11;
            Phase = DclApproachPhase.Resumed;
            _baseline = transition.Boundary;
            _lastDecision = _lastDecision with
            {
                Phase = Phase,
                ShouldPause = false,
                ShouldStage = false,
                Replayed = false,
                Reason = "owned-route-resume",
            };
            return true;
        }
    }

    public void Clear()
    {
        lock (_gate)
            ResetInternal("cleared");
    }

    public bool Forget(nint unitPtr)
    {
        if (unitPtr == 0)
            return false;

        lock (_gate)
        {
            bool ownsState = _baseline?.MoverPtr == unitPtr ||
                _transition?.Boundary.MoverPtr == unitPtr ||
                _candidates.Any(candidate => candidate.ReactorPtr == unitPtr);
            if (!ownsState)
                return false;

            ResetInternal("unit-forgotten");
            return true;
        }
    }

    private DclApproachDecision SetBaseline(DclApproachBoundary boundary, string reason)
    {
        _baseline = boundary;
        _transition = null;
        _candidates = Array.Empty<DclApproachCandidate>();
        _committedReactorIndices.Clear();
        _deadlineTick = 0;
        Phase = DclApproachPhase.Baseline;
        _lastDecision = new DclApproachDecision(
            Phase,
            ShouldPause: false,
            ShouldStage: false,
            Replayed: false,
            Transition: null,
            NoCandidates,
            reason);
        return _lastDecision;
    }

    private DclApproachDecision ReleaseInternal(string reason)
    {
        if (_transition is { } transition)
            _baseline = transition.Boundary;
        Phase = DclApproachPhase.Released;
        _lastDecision = _lastDecision with
        {
            Phase = Phase,
            ShouldPause = false,
            ShouldStage = false,
            Replayed = false,
            Reason = reason,
        };
        return _lastDecision;
    }

    private DclApproachDecision AbortInternal(DclApproachBoundary boundary, string reason)
    {
        if (boundary.IsValid)
            _baseline = boundary;
        _transition = null;
        _candidates = Array.Empty<DclApproachCandidate>();
        _committedReactorIndices.Clear();
        _deadlineTick = 0;
        Phase = DclApproachPhase.Aborted;
        _lastDecision = new DclApproachDecision(
            Phase,
            ShouldPause: false,
            ShouldStage: false,
            Replayed: false,
            Transition: null,
            NoCandidates,
            reason);
        return _lastDecision;
    }

    private DclApproachDecision CurrentDecision(string reason)
        => _lastDecision with { Replayed = true, Reason = reason };

    private static bool IsTransactionActive(DclApproachPhase phase)
        => phase is DclApproachPhase.AwaitingDecision or DclApproachPhase.Armed or
            DclApproachPhase.QueueRunning or DclApproachPhase.AwaitingResume;

    private static bool SameRoute(DclApproachBoundary left, DclApproachBoundary right)
        => left.BattleGeneration == right.BattleGeneration &&
            left.MoverPtr == right.MoverPtr &&
            left.MoverTableIndex == right.MoverTableIndex &&
            left.MoverCharId == right.MoverCharId &&
            left.RouteSignature == right.RouteSignature &&
            left.RouteLength == right.RouteLength;

    private static string? ValidateCandidates(
        DclApproachBoundary boundary,
        IReadOnlyList<DclApproachCandidate> candidates)
    {
        var pointers = new HashSet<nint>();
        var indices = new HashSet<int>();
        foreach (var candidate in candidates)
        {
            if (candidate.ReactorPtr == 0 || candidate.ReactorTableIndex is < 0 or >= 21 ||
                candidate.ReactorCharId < 0)
                return "invalid-reactor-identity";
            if (candidate.ReactorPtr == boundary.MoverPtr ||
                candidate.ReactorTableIndex == boundary.MoverTableIndex)
                return "mover-cannot-react-to-own-approach";
            if (candidate.OwnerReactionId is < 422 or > 453 ||
                candidate.DeliveryReactionId is < 422 or > 453)
                return "invalid-reaction-id";
            if (!pointers.Add(candidate.ReactorPtr) || !indices.Add(candidate.ReactorTableIndex))
                return "duplicate-reactor";
        }
        return null;
    }

    private static DclApproachDecision EmptyDecision(string reason)
        => new(
            DclApproachPhase.Idle,
            ShouldPause: false,
            ShouldStage: false,
            Replayed: false,
            Transition: null,
            NoCandidates,
            reason);

    private void ResetInternal(string reason)
    {
        _baseline = null;
        _transition = null;
        _candidates = Array.Empty<DclApproachCandidate>();
        _committedReactorIndices.Clear();
        _deadlineTick = 0;
        Phase = DclApproachPhase.Idle;
        _lastDecision = EmptyDecision(reason);
    }
}
